### PR TITLE
Fix bootstrap update test.

### PR DESCRIPTION
**Pull request by codisart**

### CODE REVIEW

**Comment by greysteil** [comment]
Hero. As you can see, the specs hit the registry, which isn’t ideal!

**Comment by codisart** [comment]
Maybe the test should go check the last tag released by bootstrap independently from the code ?

**Comment by greysteil** [comment]
Agreed - just pushed [this commit](https://github.com/dependabot/dependabot-core/commit/ce55eb896316adb5a60c78344374d2735f925012) which should fix it.

**Comment by codisart** [comment]
The only way I see to make all the specs run offline it is by set up for your tests a fake file server mocking the dependencies manager apis or servers. You can use http://www.mbtest.org/ for something like this. But in my opinion, that since the feature of your bot are almost all remote, it is coherent for me to test in real the file fetching as a "api contract testing" or "end to end test" allowing you to be sure that nothing broke.

**Comment by greysteil** [comment]
Yeah, that's exactly what I was thinking, although hadn't seen mountebank. I'm with you on maintaining some end-to-end tests, too.

Regardless, setting the above is a lower priority than GitLab, getting Java out of beta, and a host of other things - the tests on Dependabot aren't normally flaky, and have pretty good coverage.

**Pull request merged**
