### PR TITLE
Remove the dependency_has_directory feature flag

### PR DESCRIPTION
**Pull request by Nishnha**
### What are you trying to accomplish?

Remove the dependency_has_directory feature flag
Used in:
- https://github.com/dependabot/dependabot-core/pull/9988
- https://github.com/dependabot/dependabot-core/pull/9938

### Anything you want to highlight for special attention from reviewers?

The flag was already rolled out to 100% with no new sentry errors.

### How will you know you've accomplished your goal?

No new sentry errors after this deploys.

### Checklist

- [ ] I have run the complete test suite to ensure all tests and linters pass.
- [ ] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [ ] I have written clear and descriptive commit messages.
- [ ] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [ ] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by Nishnha** [comment]
Hmm for some reason the go smoke test went from updating a PR to creating a PR

```
-    - type: update_pull_request
+    - type: create_pull_request
```

**Comment by dotLou** [comment]
https://github.com/dependabot/dependabot-core/issues/10118#issuecomment-2211272403

This is probably relevant for the group updates - there's some issues with the recent changes here that stop grouped rebases and recreate operations from functioning

**Comment by boomshakalakah** [comment]
> Hmm for some reason the go smoke test went from updating a PR to creating a PR. 
> 
> ```
> -    - type: update_pull_request
> +    - type: create_pull_request
> ```
> 
> Same with one of the specs 
> 
> ```
> updater | 2024/06/24 14:49:05 INFO Results:
> updater | +--------------------------------------------------------------------------------------+
> updater | |                         Changes to Dependabot Pull Requests                          |
> updater | +---------+----------------------------------------------------------------------------+
> updater | | created | dependency-a ( from 1.2.3 to 1.2.5 ), dependency-b ( from 2.2.3 to 2.2.5 ) |
> updater | +---------+----------------------------------------------------------------------------+
> proxy | 2024/06/24 14:49:06 Skipping sending metrics because api endpoint is empty
> proxy | 2024/06/24 14:49:06 8/12 calls cached (66%)
> > stderr 'updated \| dependency-a \( from 1.2.3 to 1.2.5 \), dependency-b \( from 2.2.3 to 2.2.5 \)'
> ```

@Nishnha I don't think you introduced a bug. I think your changes exposed an existing bug (listed above). That looks a lot like what I'm seeing in production.

**Comment by jakecoffman** [comment]
The feature flag is removed and I rolled back some changes to fix the rebase issues across these PRs:
- https://github.com/dependabot/dependabot-core/pull/10224
- https://github.com/dependabot/dependabot-core/pull/10228
- https://github.com/dependabot/dependabot-core/pull/10252
- https://github.com/dependabot/dependabot-core/pull/10270

So this PR is no longer needed.

**Pull request closed without merging**
