### PR TITLE
Fix: Run workflow on pull requests as well

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs the previously introduced workflow on pull request events as well

Follows #2363.

### CODE REVIEW

**Comment by localheinz** [comment]
@feelepxyz @jurre 

We cannot use secrets in workflows triggered by pushes from forks:

https://github.com/dependabot/dependabot-core/blob/0610325ea0d7044dfca68c89febec635078467b4/.github/workflows/ci.yml#L11-L13

**Comment by feelepxyz** [comment]
> We cannot use secrets in workflows triggered by pushes from forks:

Oh yeah I think we'll need to switch to repo scoped github packages instead which should also work on the fork.

**Comment by jurre** [comment]
> We cannot use secrets in workflows triggered by pushes from forks:

Will look into that and make sure that works 👍 

Regarding the proposed change, why do we need to also build on `pull_request`? Every push is already built, it would be the exact same build as for the latest push of a PR right?

**Comment by feelepxyz** [comment]
> Regarding the proposed change, why do we need to also build on `pull_request`? Every push is already built, it would be the exact same build as for the latest push of a PR right?

Looks like `push` isn't triggered for forks: https://github.com/dependabot/dependabot-core/pull/2372

**Comment by localheinz** [comment]
@jurre 

> Will look into that and make sure that works 👍

👍 

> Regarding the proposed change, why do we need to also build on pull_request? Every push is already built, it would be the exact same build as for the latest push of a PR right?

Perhaps it would make sense to build pushes to `main` only?

```diff
-  - pull_request
+  pull_request: null
-  - push
+  push:
+    - main  
```

**Comment by jurre** [comment]
> Perhaps it would make sense to build pushes to main only?

A workflow that I've been using more recently is pushing a branch to get CI to run, but hold off with opening a pull request until it's in a shape that I'm happy with and CI is passing, so I'd like to keep building on `push` for all branches, I think building on both `push` and `pull_request` is probably fine, just a little bit wasteful.

**Comment by localheinz** [comment]
Thank you, @feelepxyz and @jurre!

**Pull request merged**
