### PR TITLE
[python][pip-compile] Add --strip-extras by default when resolving versions

### LINKED ISSUE #6550: [python][pip-compile] Dependabot cannot resolve dependency version if the lockfile is used as constraints in other manifest files.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip/pip-compile

### Package manager version

pip 22.3.1 pip-compile 6.12.1

### Language version

3.7.5

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

I expected dependabot to strip the extras out of this file since it is being used as a constraint to another file which dependabot will attempt to generate.

Instead dependabot does not strip the extras out of the produced file which means that the process fails with 
```
pip._internal.exceptions.InstallationError: Constraints cannot have extras
```
Here is the code where dependabot runs `pip-compile` to resolve the version.
https://github.com/dependabot/dependabot-core/blob/0a94b90bbeb7157f3aada32b08e40a3c2adda548/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L76-L101

Given the manifest files below, notice how if we update a `.in` file that is being used as a `-c` to another file, then `pip-compile` will fail to run on that file. 

# Suggestion
There is a `pip-tools` discussion around making `--strip-extras` the default behavior: https://github.com/jazzband/pip-tools/issues/1613. Therefore, pass `--strip-extras` by default in the two `pip-compile` calls here: 

https://github.com/dependabot/dependabot-core/blob/0a94b90bbeb7157f3aada32b08e40a3c2adda548/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L83

https://github.com/dependabot/dependabot-core/blob/0a94b90bbeb7157f3aada32b08e40a3c2adda548/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L98

PR here #6551
 

## Alternative to suggestion
dependabot supports parsing `--strip-extras` in the file_updater, it should support it in the version resolver as well:
https://github.com/dependabot/dependabot-core/blob/0a94b90bbeb7157f3aada32b08e40a3c2adda548/python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb#L442

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

```
updater | ERROR <job_592338820> Error processing click (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_592338820> Using indexes:
updater | <job_592338820>   https://pypi.org/simple
updater | <job_592338820> 
updater | <job_592338820>                           ROUND 1                           
updater | <job_592338820> /usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/pip/_internal/req/req_install.py:877: PipDeprecationWarning: DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
updater | <job_592338820>   issue=8210,
updater | <job_592338820> Traceback (most recent call last):
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/bin/pip-compile", line 8, in <module>
updater | <job_592338820>     sys.exit(cli())
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
updater | <job_592338820>     return self.main(*args, **kwargs)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/click/core.py", line 1055, in main
updater | <job_592338820>     rv = self.invoke(ctx)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
updater | <job_592338820>     return ctx.invoke(self.callback, **ctx.params)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/click/core.py", line 760, in invoke
updater | <job_592338820>     return __callback(*args, **kwargs)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
updater | <job_592338820>     return f(get_current_context(), *args, **kwargs)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/piptools/scripts/compile.py", line 580, in cli
updater | <job_592338820>     results = resolver.resolve(max_rounds=max_rounds)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/piptools/resolver.py", line 592, in resolve
updater | <job_592338820>     compatible_existing_constraints=compatible_existing_constraints,
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/piptools/resolver.py", line 625, in _do_resolve
updater | <job_592338820>     check_supported_wheels=not self.options.target_dir,
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
updater | <job_592338820>     collected = self.factory.collect_root_requirements(root_reqs)
updater | <job_592338820>   File "/usr/local/.pyenv/versions/3.7.16/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 481, in collect_root_requirements
updater | <job_592338820>     raise InstallationError(problem)
updater | <job_592338820> pip._internal.exceptions.InstallationError: Constraints cannot have extras
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:224:in `run_command'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:282:in `run_pip_compile_command'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:82:in `block (3 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:76:in `each'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:76:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:57:in `resolvable?'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker.rb:39:in `latest_resolvable_version'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_592338820> /home/dependabot/python/lib/dependabot/python/update_checker.rb:108:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | ERROR <job_592338820> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:486:in `requirements_to_unlock'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:259:in `check_and_create_pull_request'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_592338820> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_592338820> bin/update_files.rb:23:in `<main>'
```

### Smallest manifest that reproduces the issue

requirements-shared.in
```
play-scraper
```

requirements-shared.txt. This is what dependabot will generate because it doesn't pass `--strip-extras`. Notice **requests[security]**
```
#
# This file is autogenerated by pip-compile with python 3.7
# To update, run:
#
#    pip-compile --output-file=requirements-shared.txt requirements-shared.in
#
beautifulsoup4==4.11.1
    # via play-scraper
certifi==2022.12.7
    # via requests
charset-normalizer==3.0.1
    # via requests
idna==3.4
    # via requests
lxml==4.9.2
    # via play-scraper
play-scraper==0.6.0
    # via -r requirements-shared.in
requests[security]==2.28.2
    # via
    #   play-scraper
    #   requests-futures
requests-futures==1.0.0
    # via play-scraper
soupsieve==2.3.2.post1
    # via beautifulsoup4
urllib3==1.26.14
    # via requests
```
requirements-uses.in
```
-c requirements-shared.txt

click
```
Note: command below is what dependabot will effectively be running.
```
$ pip-compile requirements-uses.in --dry-run --resolver=backtracking
/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py:877: PipDeprecationWarning: DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
  issue=8210,
Traceback (most recent call last):
  File "/home/discord/dependabot-script/ttt123123/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 580, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/piptools/resolver.py", line 592, in resolve
    compatible_existing_constraints=compatible_existing_constraints,
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/piptools/resolver.py", line 625, in _do_resolve
    check_supported_wheels=not self.options.target_dir,
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/discord/dependabot-script/ttt123123/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 481, in collect_root_requirements
    raise InstallationError(problem)
pip._internal.exceptions.InstallationError: Constraints cannot have extras
```

### PR DESCRIPTION
**Pull request by nwalsh1995**
Closes #6550

### CODE REVIEW

**Review by pavera — APPROVED** [review]
I verified this option is available in pip-compile > 6.2.0 (minimum we'll run is 6.4.0). Thanks for the PR @nwalsh1995!

**Comment by deivid-rodriguez** [comment]
I kindly set this as draft until we resolve comments at https://github.com/dependabot/dependabot-core/issues/6550#issuecomment-1410860005 and below 🙏.

**Comment by nwalsh1995** [comment]
@deivid-rodriguez since this solves the case where dependabot pulls in extras during a run and causes conflicts, can we merge this?

**Comment by deivid-rodriguez** [comment]
Sorry, let me check your comment on this issue now. If it fixes the problem, for sure we can merge it. It'd be nice to add a spec for the issue this is fixing, so we don't regress in the future.

**Comment by deivid-rodriguez** [comment]
Just checked the other example you provided and it fixes things, indeed!

I did investigate a bit more and I think it may be an issue with pip-compile? I did try a patch to pip-tools that seems to fix the issue:

```diff
diff --git a/piptools/resolver.py b/piptools/resolver.py
index 750e6c9..ea86e66 100644
--- a/piptools/resolver.py
+++ b/piptools/resolver.py
@@ -521,6 +521,8 @@ class BacktrackingResolver(BaseResolver):
             # Mark direct/primary/user_supplied packages
             for ireq in self.constraints:
                 ireq.user_supplied = True
+                if ireq.constraint:
+                    ireq.extras = set()  # pip does not support extras in constraints
 
             # Pass compiled requirements from `requirements.txt`
             # as constraints to resolver
```

But did not manage to write a test that fails without the change.

**Comment by nwalsh1995** [comment]
@deivid-rodriguez just tested both nwalsh1995/depbot-example and nwalsh1995/depbot-example2 with your patch and they both run without errors! 🎉 

Do you want to make a PR to pip-tools for my issue https://github.com/jazzband/pip-tools/issues/1806 ?

**Comment by deivid-rodriguez** [comment]
This is getting fixed [upstream](https://github.com/jazzband/pip-tools/pull/1808) :)

Pip-tools has a fast release cadence and we are using the latest, so we can probably close this and wait for the fix to be released upstream. Is that ok @nwalsh1995?

**Comment by nwalsh1995** [comment]
> so we can probably close this and wait for the fix to be released upstream

That sounds fine. Unfortunately we cannot use dependabot while we are waiting for the fix to go through so hopefully it is merged quickly :/

**Comment by deivid-rodriguez** [comment]
Alright, let me close this for now. Since the PR was proposed by an upstream maintainer, I think it should be fine! But if it takes too long we can reopen this.

**Comment by deivid-rodriguez** [comment]
Super confused about my own assestation that the PR was proposed by a maintainer, not sure where I got that from. Anyways, let's see how it moves forward.

**Pull request closed without merging**
