### PR TITLE
Running without scripts interfere Composer plugins

### LINKED ISSUE #4030: Composer plugin changes are not applied to lockfile
When a composer plugin modifies dependencies, those plugin changes are not accounted for in the `composer.lock` file generated by Dependabot.

In this particular case, [wikimedia/composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) is used to merge dependencies from a sub-project into the root dependencies.
The PR created by dependabot doesn't appear to execute the plugin, resulting in packages being removed from the lock file.

**Package ecosystem**
composer
**Package manager version**
composer 2.1.3
**Language version**
PHP 7.4
**Manifest location and content prior to update**
https://github.com/gapple/dpbot-merge/blob/main/composer.json
https://github.com/gapple/dpbot-merge/blob/main/composer.lock
**dependabot.yml content**
https://github.com/gapple/dpbot-merge/blob/main/.github/dependabot.yml
**Updated dependency**
n/a
**What you expected to see, versus what you actually saw**
The `composer.lock` file changes in the dependabot PR removes the `gapple/structured-fields` library, which is merged from `/sub/composer.json`.
**Native package manager behavior**
Composer includes the `gapple/structured-fields` package information from `/sub/composer.json` in `/composer.lock`
**Images of the diff or a link to the PR, issue or logs**
https://github.com/gapple/dpbot-merge/pull/1
**🕹 Bonus points: Smallest manifest that reproduces the issue**

I created a minimal repository to replicate the issue: https://github.com/gapple/dpbot-merge

### PR DESCRIPTION
**Pull request by T2L**
Fixes #4030

### CODE REVIEW

**Comment by T2L** [comment]
As per https://github.com/composer/composer/pull/9942 and @Seldaek comment https://github.com/dependabot/dependabot-core/issues/4030#issuecomment-885485761, dependabot should update used Composer version

**Comment by jurre** [comment]
Thanks for contributing to Dependabot

I'm OK with the composer version update but have some concerns regarding running scripts that I mentioned [here](https://github.com/dependabot/dependabot-core/issues/4030#issuecomment-974144991)

Could you split the PR up so we can evaluate running scripts separately?

**Comment by T2L** [comment]
@jurre here you go

**Comment by jurre** [comment]
Cheers! Would you update the PR title and decription to match the latest changes?

Fwiw, the version of composer that we use to update dependencies is actually [managed by composer itself](https://github.com/dependabot/dependabot-core/blob/906887b3b24bc2e86a29b8652123dc51317ff6a2/composer/helpers/v2/composer.json#L5), this will only update the version of composer we use to install those dependencies, I think. But still good to keep it up to date :sparkles:

**Comment by jurre** [comment]
I've pulled these changes into this PR: https://github.com/dependabot/dependabot-core/pull/4395

**Pull request closed without merging**
