### PR TITLE
build(deps): bump Yarn to 4.3.1

### PR DESCRIPTION
**Pull request by yeikel**

### CODE REVIEW

**Comment by arusahni** [comment]
@yeikel Thank you for pushing this forward! It looks like a fix for failing check may have been merged in a few months ago (#9405). I wonder if a rebase would make this PR turn green?

**Comment by yeikel** [comment]
> @yeikel Thank you for pushing this forward! It looks like a fix for failing check may have been merged in a few months ago (#9405). I wonder if a rebase would make this PR turn green?

Main is already using `4.1.1` after https://github.com/dependabot/dependabot-core/pull/9405/files

**Comment by yeikel** [comment]
https://github.com/dependabot/dependabot-core/pull/11123

**Comment by jeffwidman** [comment]
Actually @yeikel thanks for pointing me towards this, I hadn't seen it before.

Interesting that it's failing a smoke test, but that same smoke test is passing on a newer version of Yarn:
* https://github.com/dependabot/dependabot-core/pull/11123

**Comment by yeikel** [comment]
> Actually @yeikel thanks for pointing me towards this, I hadn't seen it before.
> 
> Interesting that it's failing a smoke test, but that same smoke test is passing on a newer version of Yarn:
> 
>     * [Bump yarn to 4.5.3 #11123](https://github.com/dependabot/dependabot-core/pull/11123)

The error failure is a bit misleading/hard to interpret because the diff seems identical to me? Maybe running it manually will show more info

```diff
--- smoke.yaml
+++ result.yaml
@@ -6520,7 +6520,7 @@
                   operation: update
                   support_file: false
                   type: file
-            pr-title: Bump @types/lodash from 4.14.189 to 4.14.191
+            pr-title: bump @types/lodash from 4.14.189 to 4.14.191
             pr-body: |
                 Bumps [@types/lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/lodash) from 4.14.189 to 4.14.191.
                 <details>
@@ -6531,7 +6531,7 @@
                 </details>
                 <br />
             commit-message: |-
-                Bump @types/lodash from 4.14.189 to 4.14.191
+                bump @types/lodash from 4.14.189 to 4.14.191
 
                 Bumps [@types/lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/lodash) from 4.14.189 to 4.14.191.
                 - [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)


```

**Pull request closed without merging**
