### PR TITLE
Garry hurley jr/enable rspec file path

### PR DESCRIPTION
**Pull request by GarryHurleyJr**
### What are you trying to accomplish?
The rspec rubocop rule to check file paths is disabled.  We are re-enabling it to ensure better code coverage for the tests.

### Anything you want to highlight for special attention from reviewers?
This is a first pass at fixing this issue.

### How will you know you've accomplished your goal?
The rubocop check runs effectively and all tests are checked against it.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Review by sachin-sandhu — APPROVED** [review]
Approving based on:

1. CI test case coverage
2. Confirmed with @GarryHurleyJr that test coverage already in place.

**Review by landongrindheim — CHANGES_REQUESTED** [review]
In its current state, this is moving the exclusion down from line 96 to line 401. I'm assuming you meant to address the violations, but that's not being done.

**Comment by GarryHurleyJr** [comment]
> In its current state, this is moving the exclusion down from line 96 to line 401. I'm assuming you meant to address the violations, but that's not being done.

Actually, that is the wrong exclusion.  I created the branch wrong and had to revert some changes that were in my local and had to do with a different PR.  I will go back to that other PR once this is merged and fix it there.

**Comment by abdulapopoola** [comment]
This PR seems to be a noop; any reason why it is to be merged?

**Comment by GarryHurleyJr** [comment]
> This PR seems to be a noop; any reason why it is to be merged?

This PR was created incorrectly.  I will close it and create a new one.

**Pull request closed without merging**
