### PR TITLE
Bump nodejs to 16 and npm to 8

### LINKED ISSUE #4359: upgrade NodeJS to new LTS.
I would like to see usage of NodeJS LTS (v16) in the docker image, currently v14 (previous active LTS, now maintanance LTS) gets installed. 

Overview of releases and LTS state: https://nodejs.org/en/about/releases/

Is this something i should open a pull request for?

### PR DESCRIPTION
**Pull request by shu-mutou**
Fixes #4359

### CODE REVIEW

**Comment by jurre** [comment]
I think npm 8 breaks some tests, see also https://github.com/dependabot/dependabot-core/pull/4531

**Comment by shu-mutou** [comment]
Close this in favor of #4531

**Comment by shu-mutou** [comment]
Thanks @jurre !! I'm looking forward to be fixed this in your PR!!

**Comment by jurre** [comment]
Thanks @shu-mutou, I'm not sure when I'll have time to work on it but I'll make sure to update here when I do

**Comment by shu-mutou** [comment]
Rebased after #4630.

**Comment by jurre** [comment]
We are now on node16 and npm8 🎉 so I'm going to close this PR, this definitely helped move things forward though, so thanks!

**Pull request closed without merging**
