### PR TITLE
Fix issue with parsing docker images with a tag in the <prefix>_<year><month><day>.<version> format

### PR DESCRIPTION
**Pull request by jpinz**
Fix issue with parsing docker images with a tag in the <prefix>_<year><month><day>.<version> format.
Included specs to test with.
We were facing issues with the `version-update:semver-major` ignore condition, and this appears to fix it.

### CODE REVIEW

**Comment by jpinz** [comment]
Appears that this is blocked until #8192 is merged

**Comment by brettfo** [comment]
The contents of this PR are up-to-date as of internal commit `2e96bf2eb56375549b882b9c370d39ead2d2a5f7`.

**Comment by JamieMagee** [comment]
@jpinz Can you recreate this from a branch instead of a fork please?

**Comment by jpinz** [comment]
> @jpinz Can you recreate this from a branch instead of a fork please?

Done! #8500

**Pull request closed without merging**
