### PR TITLE
[composer] Fix: Do not use deprecated methods

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] stops using deprecated methods

Slightly related to #2353.

💁‍♂️ For reference, see https://github.com/composer/composer/pull/8957.

### CODE REVIEW

**Comment by jurre** [comment]
Thanks @localheinz, could you rebase this (or merge in master) to trigger CI?

**Comment by localheinz** [comment]
@feelepxyz @jurre 

Looks like we still have issues with pushing images, see https://github.com/dependabot/dependabot-core/pull/2354/checks:

Screen Shot 2020-07-29 at 11 42 31

**Comment by jurre** [comment]
> Looks like we still have issues with pushing images, see https://github.com/dependabot/dependabot-core/pull/2354/checks:

Yeah :( we're aware of it, it works on the fork but not on the pull_request, actions will try to push to `dependabot` with your token, and won't have access.

I have some thoughts on how to improve this (push to artifacts instead of GPR), but I won't have time for it this week. I can see the build passing on your fork for the `push` event though, so will merge it in later 👍

**Comment by localheinz** [comment]
Thank you, @feelepxyz and @jurre!

**Pull request merged**
