### PR TITLE
properly resolve nuget search query when the api is versioned

### PR DESCRIPTION
**Pull request by brettfo**
From [this comment](https://github.com/dependabot/dependabot-core/pull/8502#issuecomment-1840756122), a NuGet repository's `:search_url` can't be found if it has a version suffix like `/3.0.0`, etc.  This PR checks in priority order for the specific `SearchQueryService` value.

### CODE REVIEW

**Review by jakecoffman — APPROVED** [review]
Thanks for the quick PR!

I confirmed this fixes `dependabot update nuget udap-tools/udap-dotnet`. 

@brettfo Do you want someone from your team to approve as well or should I go ahead and deploy this?

**Comment by brettfo** [comment]
This fix was pretty straight forward, it can be merged.

**Comment by jakecoffman** [comment]
Looks like it didn't fix this case: `dependabot update nuget SonarSource/sonar-scanner-msbuild`

**Comment by jakecoffman** [comment]
Again this seems like an improvement to the error rate so I'll merge it.

**Comment by brettfo** [comment]
@jakecoffman Just created PR #8538 that should cover this.

**Pull request merged**
