### PR TITLE
Add subdirectory value while preparing pyproject.toml if subdirectory key exists

### PR DESCRIPTION
**Pull request by VictoryKon**

### CODE REVIEW

**Comment by sysradium** [comment]
I can confirm the issue. If we out dependency is actually in a subdirectory poetry fails to install it, because dependabot does not add `subdirectory` into a auto-generate `pyproject.yaml`

**Comment by sysradium** [comment]
Anyone?

**Comment by deivid-rodriguez** [comment]
Can you share example dependency manifests that reproduce this problem?

**Comment by VictoryKon** [comment]
> Can you share example dependency manifests that reproduce this problem?

In my case the pyproject.toml file in the project contains the dependency defined in the following form:
```
[tool.poetry.dependencies]  
 
my_library = {git = "https://github.com/<organisation url>/<repo url>", rev = "v1.2.0", subdirectory = "python"} 
```
The `pyproject.yaml` file generated by the dependabot does not contain the `subdirectory` at all, that's why poetry fails to identify the dependency.

**Comment by deivid-rodriguez** [comment]
I still don't understand the problem well. What is dependabot doing, is it _removing_ the `directory` key from the `pyproject.toml` file?

It seems your solution is looking at the `directory` option in the lockfile, so I guess `poetry.lock` is also involved? What do you mean by `pyproject.yaml`, is that a typo for `pyproject.toml`.

Ideally this would have an accompanying test that shows the problem. But if that's hard (which I understand, our specs are quite tricky), I think creating a small real test repository that shows the problem would help a lot.

A

**Comment by sysradium** [comment]
@deivid-rodriguez no. The thing is that dependabot creates a temp directory, where it places a processed version of `pyproject.toml`. It reformats it, removes some things and so on and then tries running update command in a venv. That is when things fail, since poetry is unable install a package, because dependabot removed `subdirectory` from `pyproject.toml`.

**Comment by deivid-rodriguez** [comment]
Ok, that's starting to make sense. So the error is a crash while checking for updates, not a bad PR. That points to an error in `UpdateChecker`. Is that the case? You haven't even copied a backtrace for us, so I assumed this was not an error but a bad PR.

I know it's easier to try to explain the problem, but for us it's really much better to have a sample repository where we can see it. Could you please create that?

By the way, specs seems to be failing somewhere near where this problem should be happening. It may be a flaky failure, but I've never seen it before and it does look suspicious.

**Comment by sysradium** [comment]
@deivid-rodriguez 

It is coming from a private org that's why we can't share the exact case 1:1. We were in a big rush trying to fix the thing.
Here us a stacktrace I found on our slack:
```
updater | 2023/10/05 10:39:00 ERROR <job_731085678> Creating virtualenv app-U0giz7ek-py3.11 in /home/dependabot/.cache/pypoetry/virtualenvs
updater | 
updater | Unable to determine package info for path: /home/dependabot/.cache/pypoetry/virtualenvs/app-U0giz7ek-py3.11/src/events
updater | 
updater | Command ['/tmp/tmpm9w6jxkp/.venv/bin/python', '-'] errored with the following return code 1
updater | 
updater | Output:
updater | Traceback (most recent call last):
updater |   File "<stdin>", line 9, in <module>
updater |   File "/tmp/tmpm9w6jxkp/.venv/lib/python3.11/site-packages/build/__init__.py", line 267, in __init__
updater |     _validate_source_directory(srcdir)
updater |   File "/tmp/tmpm9w6jxkp/.venv/lib/python3.11/site-packages/build/__init__.py", line 135, in _validate_source_directory
updater |     raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
updater | build.BuildException: Source /home/dependabot/.cache/pypoetry/virtualenvs/app-U0giz7ek-py3.11/src/events does not appear to be a Python project: no pyproject.toml or setup.py
updater | 
updater | 
updater | Input:
updater | import build
updater | import build.env
updater | import pyproject_hooks
updater | 
updater | source = '/home/dependabot/.cache/pypoetry/virtualenvs/app-U0giz7ek-py3.11/src/events'
updater | dest = '/tmp/tmpm9w6jxkp/dist'
updater | 
updater | with build.env.IsolatedEnvBuilder() as env:
updater |     builder = build.ProjectBuilder(
updater |         srcdir=source,
updater |         scripts_dir=env.scripts_dir,
updater |         python_executable=env.executable,
updater |         runner=pyproject_hooks.quiet_subprocess_runner,
updater |     )
updater |     env.install(builder.build_system_requires)
updater |     env.install(builder.get_requires_for_build('wheel'))
updater |     builder.metadata_path(dest)
updater | 
updater | No fallback setup.py file was found to generate egg_info.
```
It does not give you a stacktrace per se, but since you already have a PR.

As you can see it tries to install a package at `src/events` however it should be `src/events/python`.
We command it fails on is:
```
pyenv exec poetry update pytz --lock --no-interaction
```

**Comment by deivid-rodriguez** [comment]
Ok!

I'm going to go through some common Python errors we see in our error tracker next week, so I'll probably find this particular issue happening on a public repo. I'll use that chance to be able to reproduce this problem and review this PR and maybe add a test to it.

**Comment by sysradium** [comment]
Just to add more context https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/helpers.rb#L16
This is where I added a `debugger` statement.
I downloaded dependabot docker image, dropped into cli there and:
* Ran dependabot update
* Kept skipping breakpoint till `command` became `pyenv exec poetry update pytz --lock --no-interaction` (the one I saw failing in "stacktrace")
* I ran `Open3.capture3("pwd")` to see what is the working directory it tries to execute `poetry` command in
* This gave a temp folder dependabot created, where it placed processed `pyproject` file
* I manually went to that folder, ran `pyenv exec poetry update pytz --lock --no-interaction`
* It gave a failure. I started investigating `pyproject.toml` file which was there. Was surprised to see that it looks differently from our original one. Started investigating it and found out that the main difference is the absence of `subdirectory`

**Comment by sysradium** [comment]
@deivid-rodriguez 

Good day. By chance any news on this PR?

**Comment by deivid-rodriguez** [comment]
No, not yet. Just reiterate that a public repository that illustrates the bug being fixed here will speed things up.

**Comment by sysradium** [comment]
@deivid-rodriguez 

A friendly bump.

For your convenience I prepared a testing repo which shows the problem.
Imaginary service which imports a library:
https://github.com/sysradium/dependabot-service/

A library with a subdirectory:
https://github.com/sysradium/dependabot-subdir-lib 

To see the problem:
```
> gcl git@github.com:sysradium/dependabot-service.git

> cd ./dependabot-service

> dependabot update pip sysradium/dependabot-service --commit main

    cli | 2023/10/24 13:00:38 Adding missing credentials-metadata into job definition
    cli | 2023/10/24 13:00:38 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:63dc6cee93db02fb70e39e7278f4a90fd0b39376572f9813032dfa89672014e1
    cli | 2023/10/24 13:00:38 using image ghcr.io/dependabot/dependabot-updater-pip at sha256:a16af7aba8898b8148f6f5709bd64399ca19f043bd9793a77953277bf774feeb
  proxy | 2023/10/24 13:00:38 proxy starting, commit: fd948d06eb7d332426f2a1577cd4f69a0d7cf522
  proxy | 2023/10/24 13:00:38 initializing metrics client: No address passed and autodetection from environment failed
  proxy | 2023/10/24 13:00:38 GitHubAPIHandler has no app access tokens
updater | Updating certificates in /etc/ssl/certs...
  proxy | 2023/10/24 13:00:38 Listening (:1080)
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | done.
updater | 2023/10/24 13:00:39 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/10/24 13:00:40 INFO Starting job processing
  proxy | 2023/10/24 13:00:40 [002] GET https://api.github.com:443/repos/sysradium/dependabot-service/contents/?ref=main
  proxy | 2023/10/24 13:00:40 [002] 200 https://api.github.com:443/repos/sysradium/dependabot-service/contents/?ref=main
  proxy | 2023/10/24 13:00:40 [004] GET https://api.github.com:443/repos/sysradium/dependabot-service/contents/pyproject.toml?ref=main
  proxy | 2023/10/24 13:00:40 [004] 200 https://api.github.com:443/repos/sysradium/dependabot-service/contents/pyproject.toml?ref=main
  proxy | 2023/10/24 13:00:40 [006] GET https://api.github.com:443/repos/sysradium/dependabot-service/contents/poetry.lock?ref=main
  proxy | 2023/10/24 13:00:41 [006] 200 https://api.github.com:443/repos/sysradium/dependabot-service/contents/poetry.lock?ref=main
updater | 2023/10/24 13:00:41 INFO Finished job processing
updater | 2023/10/24 13:00:41 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/10/24 13:00:41 INFO Starting job processing
  proxy | 2023/10/24 13:00:43 [007] POST http://host.docker.internal:60804/update_jobs/cli/update_dependency_list
{"data":{"dependencies":[{"name":"jinja2","requirements":[],"version":"3.0.3"},{"name":"markupsafe","requirements":[],"version":"2.1.3"},{"name":"protobuf","requirements":[],"version":"4.23.2"},{"name":"validate-email","requirements":[],"version":"1.3"}],"dependency_files":["/pyproject.toml","/poetry.lock"]},"type":"update_dependency_list"}
  proxy | 2023/10/24 13:00:43 [007] 200 http://host.docker.internal:60804/update_jobs/cli/update_dependency_list
  proxy | 2023/10/24 13:00:43 [008] POST http://host.docker.internal:60804/update_jobs/cli/increment_metric
{"data":{"metric":"updater.started","tags":{"operation":"update_all_versions"}},"type":"increment_metric"}
  proxy | 2023/10/24 13:00:43 [008] 200 http://host.docker.internal:60804/update_jobs/cli/increment_metric
updater | 2023/10/24 13:00:43 INFO Starting update job for sysradium/dependabot-service
updater | 2023/10/24 13:00:43 INFO Checking all dependencies for version updates...
updater | 2023/10/24 13:00:43 INFO Checking if jinja2 3.0.3 needs updating
  proxy | 2023/10/24 13:00:43 [010] GET https://pypi.org:443/simple/jinja2/
  proxy | 2023/10/24 13:00:43 [010] 200 https://pypi.org:443/simple/jinja2/
updater | 2023/10/24 13:00:44 INFO Latest version is 3.1.2
  proxy | 2023/10/24 13:00:45 [012] GET https://github.com:443/sysradium/dependabot-subdir-lib.git/info/refs?service=git-upload-pack
  proxy | 2023/10/24 13:00:45 [012] 200 https://github.com:443/sysradium/dependabot-subdir-lib.git/info/refs?service=git-upload-pack
  proxy | 2023/10/24 13:00:45 [014] POST https://github.com:443/sysradium/dependabot-subdir-lib.git/git-upload-pack
  proxy | 2023/10/24 13:00:45 [014] 200 https://github.com:443/sysradium/dependabot-subdir-lib.git/git-upload-pack
  proxy | 2023/10/24 13:00:45 [016] POST https://github.com:443/sysradium/dependabot-subdir-lib.git/git-upload-pack
  proxy | 2023/10/24 13:00:45 [016] 200 https://github.com:443/sysradium/dependabot-subdir-lib.git/git-upload-pack
  proxy | 2023/10/24 13:00:47 [018] GET https://pypi.org:443/simple/build/
  proxy | 2023/10/24 13:00:47 [018] 200 https://pypi.org:443/simple/build/
  proxy | 2023/10/24 13:00:47 [020] GET https://files.pythonhosted.org:443/packages/58/91/17b00d5fac63d3dca605f1b8269ba3c65e98059e1fd99d00283e42a454f0/build-0.10.0-py3-none-any.whl
  proxy | 2023/10/24 13:00:47 [020] 200 https://files.pythonhosted.org:443/packages/58/91/17b00d5fac63d3dca605f1b8269ba3c65e98059e1fd99d00283e42a454f0/build-0.10.0-py3-none-any.whl
  proxy | 2023/10/24 13:00:47 [022] GET https://pypi.org:443/simple/pyproject-hooks/
  proxy | 2023/10/24 13:00:47 [022] 200 https://pypi.org:443/simple/pyproject-hooks/
  proxy | 2023/10/24 13:00:47 [024] GET https://files.pythonhosted.org:443/packages/d5/ea/9ae603de7fbb3df820b23a70f6aff92bf8c7770043254ad8d2dc9d6bcba4/pyproject_hooks-1.0.0-py3-none-any.whl
  proxy | 2023/10/24 13:00:47 [024] 200 https://files.pythonhosted.org:443/packages/d5/ea/9ae603de7fbb3df820b23a70f6aff92bf8c7770043254ad8d2dc9d6bcba4/pyproject_hooks-1.0.0-py3-none-any.whl
  proxy | 2023/10/24 13:00:47 [026] GET https://pypi.org:443/simple/packaging/
  proxy | 2023/10/24 13:00:48 [026] 200 https://pypi.org:443/simple/packaging/
  proxy | 2023/10/24 13:00:48 [028] GET https://files.pythonhosted.org:443/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  proxy | 2023/10/24 13:00:48 [028] 200 https://files.pythonhosted.org:443/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  proxy | 2023/10/24 13:00:48 [030] GET https://files.pythonhosted.org:443/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl
  proxy | 2023/10/24 13:00:48 [030] 200 https://files.pythonhosted.org:443/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl
  proxy | 2023/10/24 13:00:50 [031] POST http://host.docker.internal:60804/update_jobs/cli/record_update_job_error
{"data":{"error-type":"unknown_error","error-details":null},"type":"record_update_job_error"}
  proxy | 2023/10/24 13:00:50 [031] 200 http://host.docker.internal:60804/update_jobs/cli/record_update_job_error
updater | 2023/10/24 13:00:50 ERROR Error processing jinja2 (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/10/24 13:00:50 ERROR Creating virtualenv dependabot-service-uzoQjMJP-py3.11 in /home/dependabot/.cache/pypoetry/virtualenvs
updater |
updater | Unable to determine package info for path: /home/dependabot/.cache/pypoetry/virtualenvs/dependabot-service-uzoQjMJP-py3.11/src/dependabot-subdir-lib
updater |
updater | Command ['/tmp/tmp24sdv0ke/.venv/bin/python', '-'] errored with the following return code 1
updater |
updater | Output:
updater | Traceback (most recent call last):
updater |   File "<stdin>", line 9, in <module>
updater |   File "/tmp/tmp24sdv0ke/.venv/lib/python3.11/site-packages/build/__init__.py", line 267, in __init__
updater |     _validate_source_directory(srcdir)
updater |   File "/tmp/tmp24sdv0ke/.venv/lib/python3.11/site-packages/build/__init__.py", line 135, in _validate_source_directory
updater |     raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
updater | build.BuildException: Source /home/dependabot/.cache/pypoetry/virtualenvs/dependabot-service-uzoQjMJP-py3.11/src/dependabot-subdir-lib does not appear to be a Python project: no pyproject.toml or setup.py
updater |
updater |
updater | Input:
updater | import build
updater | import build.env
updater | import pyproject_hooks
updater |
updater | source = '/home/dependabot/.cache/pypoetry/virtualenvs/dependabot-service-uzoQjMJP-py3.11/src/dependabot-subdir-lib'
updater | dest = '/tmp/tmp24sdv0ke/dist'
updater |
updater | with build.env.IsolatedEnvBuilder() as env:
updater |     builder = build.ProjectBuilder(
updater |         srcdir=source,
updater |         scripts_dir=env.scripts_dir,
updater |         python_executable=env.executable,
updater |         runner=pyproject_hooks.quiet_subprocess_runner,
updater |     )
updater |     env.install(builder.build_system_requires)
updater |     env.install(builder.get_requires_for_build('wheel'))
updater |     builder.metadata_path(dest)
updater |
updater | No fallback setup.py file was found to generate egg_info.
updater | 2023/10/24 13:00:50 ERROR /home/dependabot/python/lib/dependabot/python/helpers.rb:23:in `run_poetry_command'
updater | 2023/10/24 13:00:50 ERROR /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:312:in `run_poetry_command'
updater | 2023/10/24 13:00:50 ERROR /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:150:in `run_poetry_update_command'
u
....
```

**Comment by deivid-rodriguez** [comment]
Thanks! That's really helpful, I can repro this now. Let me have a look!

**Comment by deivid-rodriguez** [comment]
Fix looks great, I just added a test using the example files you provided!

**Review by deivid-rodriguez — APPROVED** [review]

**Comment by sysradium** [comment]
@deivid-rodriguez let us merge then?

**Comment by deivid-rodriguez** [comment]
I will try to deploy & merge today. Just a little bit more patience, please.

**Comment by sysradium** [comment]
@deivid-rodriguez no problem. Just wanted to know if there is anything we should do to help you.
OK, than just waiting.
Thank you.

**Comment by deivid-rodriguez** [comment]
Thanks for your patience, this is now live!

**Pull request merged**
