### PR TITLE
Use correct global.json discovery logic when updating.

### PR DESCRIPTION
**Pull request by JoeRobich**
This change was brought up by https://github.com/dependabot/dependabot-core/pull/8812

We were locating an invalid Global.json and attempting an upgrade. However, this global.json was outside of the locations that would have it included in the build. An underlying issue was how we were discovering global.json path in the updater. This change moves us to locating global.json using appropriate discovery logic. 

> The .NET SDK looks for a global.json file in the current working directory (which isn't necessarily the same as the project directory) or one of its parent directories.
https://learn.microsoft.com/en-us/dotnet/core/tools/global-json

### CODE REVIEW

**Review by brettfo — APPROVED** [review]

**Comment by JoeRobich** [comment]
@JamieMagee Are you authorized to merge?

**Comment by JamieMagee** [comment]
@JoeRobich unfortunately not 😢

**Comment by JoeRobich** [comment]
@bdragon Hi, could I get a merge when you feel good about this change? Or, if someone else is on rotation, could you tag them in?

**Review by jakecoffman — APPROVED** [review]
I'll get this deployed, thanks!

**Pull request merged**
