### PR TITLE
Fix updating properties with name starting with "project"

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes https://github.com/dependabot/dependabot-core/issues/1859.
Fixes https://github.com/dependabot/dependabot-core/issues/2025.

### CODE REVIEW

**Review by jeffwidman — APPROVED** [review]

**Comment by jeffwidman** [comment]
Merging since CI is green, and we've got other PR's we want to keep moving so no sense merging those and then re-running CI here again.

**Comment by deivid-rodriguez** [comment]
I forgot to ask for a review from @soulus13 in case he'd be fine with having a quick look 🙏.

**Comment by jeffwidman** [comment]
Oh, good thought, I'd definitely appreciate your input @soulus13 since you know more about this ecosystem than myself + Deivid combined. 😄

**Comment by soulus13** [comment]
Hi @deivid-rodriguez , @jeffwidman , yep, this specific fix addresses the issue nicely and should not break anything 😃 There has been indeed no need to carve out the `pom` and `project` prefixes there when looking for value in the properties' paths (and not doing lookup in xml structure). A little bit on these "custom" cases for the properties could found in https://github.com/cko/predefined_maven_properties/blob/master/README.md and https://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html.

Still - i believe there is one more bug in the current implementation even after the fix:
- what `Dependabot::Maven::FileParser::PropertyValueFinder#sanitize_property_name` does - it removes the `pom` and `project` prefixes, as these are reserved prefixes to do a lookup on maven file - ok, that starts good and does make sense
- next it tries to do the lookup in the loop, slowly replacing the dots in the property names by slashes, one-by-one. That overcomplicates the things a bit, i think. You could see the pom structure here https://maven.apache.org/ref/3.0.3/maven-model/maven.html, and none of the xml's nodes have dots inside - thus it makes sense to replace them all with slashes right away for the xml structure lookup part (which is only this one `doc.at_xpath("/project/#{nm}")`)
- and then, if the replacement would be done only once - no need  for the loop to exist here at all 😃As in the current implementation we either find the result right away - or find it in the very last run of the loop anyway, when all the substitution is done, so it calls out for the simplification 😃 Unless i have missed something, for sure

**Comment by soulus13** [comment]
Ah, and one more thing i have forgotten to mention - current logic of looking up the value in profiles part (`doc.at_xpath("/project/profiles/profile/properties/#{nm}")`) is generally prone to errors, as profiles could have multiple nodes with properties, each of which could have the specific property defined, and it could have different versions inside:
```
    <profiles>
        <profile>
            <id>profileOne</id>
            <properties>
                <property>
                    <spring.aop.version>1.0.1</spring.aop.version>
                </property>
            </properties>
        </profile>
        <profile>
            <id>profileTwo</id>
            <properties>
                <property>
                    <property>
                        <spring.aop.version>2.0.2</spring.aop.version>
                    </property>
                </property>
            </properties>
        </profile>
    </profiles>
```

Current implementation would only find `1.0.1` version and be done with that, whereas `2.0.2` version could be vulnerable as well, leaving the project vulnerable. Not sure how often that really is a case - but technically it could be.

**Pull request merged**
