### PR TITLE
Support Poetry non-package mode

### PR DESCRIPTION
**Pull request by onlined**
Starting with version 1.8, Poetry has a non-package mode for projects using Poetry not for building and publishing packages but only for dependency management. `name`, `version`, `description` and `authors` fields are optional in non-package mode.

### CODE REVIEW

**Review by yeikel — COMMENTED** [review]
Please add a spec demonstrating this

**Comment by onlined** [comment]
@yeikel Added the spec

**Comment by yeikel** [comment]
> @yeikel Added the spec.

Thank you for taking the time. Let's wait for a review from the core team

**Comment by abdulapopoola** [comment]
Thanks @onlined ! This should get reviewed and if it passes that, should be deployed during the week, thanks again.

**Review by abdulapopoola — APPROVED** [review]

**Review by abdulapopoola — APPROVED** [review]

**Pull request merged**
