### PR TITLE
Add releases to list of changelog file strings

### PR DESCRIPTION
**Pull request by nipunn1313**
For example, this project puts their changelog in Releases.md
https://github.com/denoland/deno/blob/main/Releases.md

I think it is spiritually similar to "release" which is already on
the list.

### CODE REVIEW

**Comment by nipunn1313** [comment]
Was looking into adding tests, but was having trouble figuring out how to
- run tests
- find the tests for this

Not experienced with ruby, so would appreciate pointers.
Alternately, this may be the kind of small change that doesn't gain a lot of value from testing - so I'll let y'all make the judgement call.

**Comment by nipunn1313** [comment]
(or manual testing on existing projects - if that's possible)

**Comment by jurre** [comment]
Thanks, this makes sense to me!

You can run the tests from inside the docker development container, here's what I do:

```
bin/docker-dev-shell

cd common

bundle exec rspec spec/dependabot/metadata_finders/base/changelog_finder_spec.rb
```

Seems safe enough to not worry about a new test case for this, we don't test all the possible values in this array currently, and I can't really see a way for it to break things

**Comment by nipunn1313** [comment]
```
#24 4.228 Reading package lists...
#24 4.812 Ign:1 http://binaries.erlang-solutions.com/debian bionic InRelease
#24 4.824 Hit:2 https://apt.releases.hashicorp.com bionic InRelease
#24 4.828 Hit:3 http://binaries.erlang-solutions.com/debian bionic Release
#24 4.836 Hit:4 https://deb.nodesource.com/node_14.x bionic InRelease
#24 5.065 Hit:6 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu bionic InRelease
#24 5.065 Hit:7 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
#24 5.207 Hit:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
#24 5.349 Hit:9 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
#24 5.350 Hit:10 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
#24 5.492 Hit:11 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
#24 5.557 Reading package lists...
#24 6.087 Reading package lists...
#24 6.581 Building dependency tree...
#24 6.665 Reading state information...
#24 6.679 E: Unable to locate package terraform
------
executor failed running [/bin/bash -o pipefail -c apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"   && apt-get update -y   && apt-get install -y --no-install-recommends terraform=${TERRAFORM_VERSION}   && terraform -help   && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

Can't seem to create a docker-dev-shell
Spent 5 minute trying to understand the problem, but it seems really confusing.

Pulled main and problem persists.

**Comment by Nishnha** [comment]
all current tests in the changelog_finder_spec seem to pass
once this is merged it would be nice to see if we can pull the changelog from a releases.md file

Screen Shot 2022-01-10 at 3 57 48 PM

**Review by feelepxyz — APPROVED** [review]
LGTM 👍

**Pull request merged**
