### PR TITLE
[WIP] Add Rust support

### PR DESCRIPTION
**Pull request by greysteil**
That. Just a template for now.

### CODE REVIEW

**Comment by greysteil** [comment]
@adamisntdead - as discussed (on twitter). Dependabot works as follows:
- A `FileFetcher` fetches the relevant dependency files
- A `FileParser` parses those files, to see what versions you're running
- An `UpdateChecker` checks whether the version you're running is up-to-date, and if not whether you can update (given the version constraints of your other dependencies
- A `FileUpdater` updates your `Cargo.toml` and `Cargo.lock` appropriately if you can update
- A `MetadataFinder` finds details of the updated dependency's changelog, release notes, etc.

**What I need from you**

`FileFetcher`: Nothing
`FileParser`: Nothing
`MetadataFinder`: Nothing
`UpdateChecker`: We're probably going to need to shell out to Rust for this, so we can lean on Cargo to do the resolution. I might need your help tapping into some of its internals
`FileUpdater`: Same as for the `UpdateChecker`.

I'll plug away at the easy bits now, and tag you in when there's some Rust expertise required. Shouldn't take long...

**Comment by greysteil** [comment]
@adamisntdead - am I right in thinking that there's no concept of version conflicts in Rust? From what I've read, it looks like Cargo will give you multiple versions of a dependency if it can't resolve to a single one.

**Comment by adamisntdead** [comment]
Like I give two different versions for a dependency? So putting the same entry twice in the cargo.toml file?

**Comment by greysteil** [comment]
I'm thinking more when you've got two dependencies that each rely on the same sub-dependency, but demand different versions of it (that aren't compatible).

**Comment by adamisntdead** [comment]
I'm pretty sure it just gets the two different versions and uses them to compile the dependencies

**Comment by greysteil** [comment]
@adamisntdead - OK, I *think* this is working. It can't handle workspaces or path dependencies yet, and is bound to error on some setups I haven't imagined, but it should be good enough to run on a few test repos.

Any (very) simple setups you know of that we could trial it on?

Adding workspaces and path dependency support won't be too hard.

**Comment by adamisntdead** [comment]
If you want I can make a really simple lib with some tests and an outdated dependency and test it out?

**Comment by adamisntdead** [comment]
Should I just try add dependabot to the repo as normal?

**Comment by greysteil** [comment]
Perfect - I'll clone it and run it on my fork. 🤞

**Comment by greysteil** [comment]
OK, this is live and working nicely - https://github.com/greysteil/get-year/pull/4. Thanks for your help on it @adamisntdead!

**Pull request merged**
