### PR TITLE
Decouple Bundler native helper specs from standard runtime

### LINKED ISSUE #5670: Bundler requires test gems when parsing dependencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

bundler 2.4.0.dev

### Language version

ruby 2.7.6p219

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Hello, when running this:

```ruby
gitlab_bundler_parser = Dependabot::FileParsers.for_package_manager('bundler').new(dependency_files: files, source: gitlab_source, credentials: credentials)
dependencies = gitlab_bundler_parser.parse
```

I get an error, after adding `DEBUG_HELPERS=true` I see this is because this line:

```
{"BUNDLER_VERSION"=>"2.3.18", "BUNDLE_GEMFILE"=>"/home/ylecuyer/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/dependabot-bundler-0.202.0/helpers/v2/Gemfile", "GEM_HOME"=>"/home/ylecuyer/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/dependabot-bundler-0.202.0/helpers/v2/.bundle"}
bundle exec ruby /home/ylecuyer/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/dependabot-bundler-0.202.0/helpers/v2/run.rb
```

Is trying to fetch the dependencies listed here: https://github.com/dependabot/dependabot-core/blob/main/bundler/helpers/v2/Gemfile

Afaiu this gemfile is usefull only for spec and shouldn't error when running outside of specs.

I tried removing those lines: https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/native_helpers.rb#L48-L50 and it worked for me

It looks like this has been changed last year with https://github.com/dependabot/dependabot-core/commit/1535a204faf63ef331dd5ef48d9ed45f29173bc7#diff-833398d42331e02a2fd4bc36f042c10f78764d39a6d6a6b537e80e024cc55e0cR19 it is strange that I am the first one encountering the issue, maybe I'm doing something wrong.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Currently native helpers run in the context of a Gemfile with no gems. This always felt wrong to me.

My understanding is that there are two motivations for this:

* Run in presence of a lockfile with `BUNDLED WITH` set to either Bundler 1 or Bundler 2, so that RubyGems can properly activate the proper version according to which native helpers need to run.
* Optionally add test gems to the "empty by default" Gemfile, so that native helper specs can run.

Turns out none of these are needed, because:
* The proper version of Bundler can be also activated through `BUNDLER_VERSION`, which we already set.
* Native helper specs have the same dependencies as regular specs, so we can use the same Bundler context for running those.

The previous approach felt a bit overcomplicated, but also caused some issues when dependabot-core is used as a library, because native helpers would not run unless:

* Gems needed only for Dependabot to run their own tests are explicitly installed
OR
* Bundler is explicit configured as `bundle config without test`, which is what we do ourselves to avoid this problem in production.

An example of this last issue is explained at https://github.com/dependabot/dependabot-core/issues/5670, but has also recently caused issues for potential contributors to dependabot, for example, at https://github.com/dependabot/dependabot-core/issues/6517.

Closes #5670.

### CODE REVIEW

**Review by jurre — APPROVED** [review]
Yeah this makes sense and seems like a nice cleanup to me! It might be good to test this in staging on a real-world repo before deploying though just to make sure everything still works as expected?

**Comment by deivid-rodriguez** [comment]
Absolutely, I think this is the kind of PR that deserves some manual testing in staging. I'll do that!

**Review by jeffwidman — APPROVED** [review]
Makes sense. I look forward to when we can move forward with https://github.com/dependabot/dependabot-core/issues/6457 which will simplify this even further.

**Comment by deivid-rodriguez** [comment]
Yeah, the weirdness of running updates in an empty `bundler/setup` context would still be there, so this improvement should be independent from supporting Bundler 1 and Bundler 2 or just once. But I admittedly needed a few hacks for Bundler 1 to make this work :)

**Pull request merged**
