### PR TITLE
[WIP] Add Cake support

### PR DESCRIPTION
**Pull request by gitfool**
Trying to get the ball rolling for #733. I'm struggling though as my Ruby skillz are rusty and there's a lot to grok. After looking around the repo, I've at least formed what I think is the required file fetcher and file parser. This much should be fairly straight forward; maybe the maintainers can easily take it over the line from here? 😛 

- file fetcher simply looks for `*.cake` files
- file parser uses regexes to match the permutations of Cake preprocessor directives
  - and simply extracts the package and version to pass to the NuGet package manager

I'm a little lost from here but the key is that Cake is using NuGet for dependencies, so almost everything else the implementation needs should somehow delegate to the NuGet package manager.

Notes:
- NuGet "source" URL can optionally be specified in the preprocessor directive but I didn't know exactly how to specify that to the NuGet package manager. I'm sure Dependabot handles this though as it picks up changes to packages in private myget feeds, that I specify in NuGet.config only.

### CODE REVIEW

**Comment by gitfool** [comment]
Excuse me while I use your CI to check things. RuboCop is slapping me. 😊

**Comment by greysteil** [comment]
Nice! I'm crunched with a couple of other things - is it OK if I look over this late next week? Apologies for the slow turn-around!

**Comment by gitfool** [comment]
@greysteil of course; no problemo! 😄 

I've rebased this PR onto the latest master with the fix re invalid file names on Windows. Thanks for that!

**Comment by gep13** [comment]
@greysteil @gitfool just wanted to touch base on this...

What is this status of this?

**Comment by gitfool** [comment]
@gep13 I'm just going to leave this as is until @greysteil can look at it. 🤞

**Comment by ChrisMaddock** [comment]
Just stumbled across this - it will be great for us at NUnit! Thanks guys! 😄

**Comment by gitfool** [comment]
@greysteil how do I keep this PR on life support?

**Comment by greysteil** [comment]
I'm not on the Dependabot team anymore (I work on security more generally at GitHub) but I *think* stalebot works based ono comments on an issue. I don't know if it's possible to disable it for a PR - whoever turned it no should know more.

**Comment by gep13** [comment]
@greysteil thanks for replying back about this.  Congratulations on the new assignment, hope it is going well for you.  Do you know who is assigned to look at new dependabot features?  It would still be great to get this looked at, and hopefully merged in.

**Comment by greysteil** [comment]
@feelepxyz and @hmarr are your go-tos there, along with @jeffmcaffer.

**Comment by rebelagentm** [comment]
@gitfool @gep13 We set up Stale to help us manage our backlog.  I'm going through issues and will be keeping requests like this open.  For features that have been requested more than once, there may be a single tracking issue opened, but your issue will be referenced in it if that is the case.  Sorry for any confusion!

**Comment by MO2k4** [comment]
Hi,

is there any chance to fix the merge conflicts and merge this pr? I would be happy to use this feature :-)

Best Regards,
Martin

**Comment by gitfool** [comment]
Superseded by #1848.

**Pull request closed without merging**
