### PR TITLE
Clean up/optimize Dockerfile

### PR DESCRIPTION
**Pull request by ChaosCypher**
- Reduces Dockerfile image layers
- re-organizes ARG and ENV placements

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@ChaosCypher Thanks for volunteering to optimize our Dockerfile! 💪 

I see that you are proposing at least two separate changes, but having them all proposed together is hard to review. Let's for now focus on reducing image layers, and leave `ARG` and `ENV` alone, ok?

Also, once you remove all the changes about `ENV` and `ARG`, can you show the difference in build time and image size before and after your changes?

**Comment by ChaosCypher** [comment]
Hi @deivid-rodriguez I pulled it back into draft to undo those exact changes 😄 

I will provide the image size differences shortly, and revert the env/arg changes.

**Comment by jeffwidman** [comment]
If you haven't seen it, [`dive`](https://github.com/wagoodman/dive) can be very useful for optimizing layers. The project doesn't seem to be maintained anymore, but I've still found it helpful from time to time.

**Comment by jeffwidman** [comment]
gentle nudge @ChaosCypher are you still interested in working on this?

**Comment by jeffwidman** [comment]
@pavera and @jakecoffman are working on redoing our Dockerfile setup so that we can more easily split it on a per-ecosystem basis for efficiency instead of shipping a single monolothic dockerfile.

That will make much of this work outdated, so I'm going to close this.

Feel free to take another crack at it if you're interested after their changes land, or if there are specific improvements you want to break out separately from this PR go for it... I'm sure they're all ears for potential improvements.

**Pull request closed without merging**
