### PR TITLE
Do we need git-shim?

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
More of a question PR, do we need it?

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
So the rationale here is that the motivation explained in [git-shim's](https://github.com/dependabot/git-shim) README:

> This is useful in a corporate environment where an HTTP Proxy is used. You could use the command git config --global url."https://".insteadOf git:// but that doesn't work for SCP-style style URLs: git@github.com:org/repo.git due to the colon :.

I don't think that's true, since we're actually using this git feature with SCP-style URIs? 🤔

https://github.com/dependabot/dependabot-core/blob/6252098c225778707f257ce77a6bcdd3be03b8c4/common/lib/dependabot/shared_helpers.rb#L261-L268C8

I guess the one case where insteadOf doesn't work is when using inlined `user:pass` in URLs, like `ssh://user:pass@github.com/foo/bar`, maybe that's the reason?

Insights appreciated!

**Comment by jakecoffman** [comment]
See https://github.com/dependabot/dependabot-core/pull/5310 for more info on why we went with the shim.

We should add that glommio dependency to the Cargo smoke tests so any future attempts to fix it will not regress!

**Comment by deivid-rodriguez** [comment]
Mmmm, I see, thanks for the pointer.

So we keep the git shim to fix the edge case of "not knowing the host in advance + SCP-style uri being used", correct? However, that realworld example there does not fit that case, right? Both URIs mentioned there (ssh://git@github.com/DataDog/glommio.git and git://git.kernel.dk/liburing) and not SCP-style URIs?

**Comment by deivid-rodriguez** [comment]
I would agree normally, but SCP-style URIs feel like maybe too big of an edge case to warrant keeping our own shim? Specially if we have not really seen any issue in real life that cannot be fixed tweaking other stuff we already do.

In the case of PNPM, URL rewriting confused me. PNPM keeps track and detects the best protocol based on the shape of the URIs and accessibility of the repo. If it detects ssh as the best protocol, and we still rewrite URIs to https, then the requests may succeed, but PNPM will still save a ssh URI to the lockfile. If I had changed the shim or the our `insteadOf` configurations to rewrite URIs in the case of https://github.com/dependabot/dependabot-core/issues/7258, we would've introduced a bug probably worse than https://github.com/dependabot/dependabot-core/issues/7258, because we would've generated incorrect PRs.

Overall, I think all approaches have upsides and downsides, so I'm good with sticking to the shim. We should probably update the README of https://github.com/dependabot/git-shim to clarify the use case a bit though?

**Comment by deivid-rodriguez** [comment]
I'll close this since it was just a way to learn, thanks for the info and insights @jakecoffman :)

**Pull request closed without merging**
