### PR TITLE
chore(python): Target latest Python 3.12 version to 3.12.7

### PR DESCRIPTION
**Pull request by HrMathematiker**
### What are you trying to accomplish?

This PR bumps the latest Python version to 3.12.7 (the latest stable 3.12.* release - [link](https://www.python.org/doc/versions/)).

Fix https://github.com/dependabot/dependabot-core/issues/10830

### CODE REVIEW

**Comment by jeffwidman** [comment]
Oof, thanks @HrMathematiker  let's seee if we can get this out the door.

**Review by jeffwidman — APPROVED** [review]

**Comment by jeffwidman** [comment]
Looks like [Python 3.12.8 is also now live](https://www.python.org/downloads/release/python-3128/)... 

I'm going to merge this to get some users unblocked, but feel free to bump to 3.12.8 as well... we'll try to ship it a little faster next time.

**Comment by ff137** [comment]
Hi @jeffwidman - just a heads up that I see our workflow fails with 3.12.8. I assume it's not supported in dependabot yet?

**Comment by ulgens** [comment]
@ff137 This should solve that: https://github.com/dependabot/dependabot-core/pull/11530

**Pull request merged**
