### PR TITLE
Fix Python version switched from exact to tilde version

### LINKED ISSUE #6462: Python version being switched from exact to tilde version
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

Poetry 1.2.1

### Language version

Python 3.9.15

### Manifest location and content before the Dependabot update

`poetry.lock`
```
[metadata]
lock-version = "1.1"
python-versions = "3.9.15"
content-hash = "fd6fc6f4059782a6eb9e54c3f01d79433176e9ec18b525e6578641cc3369e98d"
```

`pyproject.toml` used to trigger an update:
```
[tool.poetry.dependencies]
python = "3.9.15"
Flask = "2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
```

### Updated dependency

Flask 2.1.0 -> 2.2.2

### What you expected to see, versus what you actually saw

I expect the Flask dependency to be updated to 2.2.2, but not have the `python-versions` change.

The Dependabot changed `poetry.lock` file contains:

```
[metadata]
lock-version = "1.1"
python-versions = "~3.9"
content-hash = "72b14837467ed77c01c43c1a6727e9c2e3ba4dcbf51f6a23da7d3fe48c805a6b"
```

### Native package manager behavior

Changing Flask to be `2.2.2` in the `pyproject.toml` and running `poetry lock` produces the following:

```
[metadata]
lock-version = "1.1"
python-versions = "3.9.15"
content-hash = "72b14837467ed77c01c43c1a6727e9c2e3ba4dcbf51f6a23da7d3fe48c805a6b"
```

Note the `python-versions` is correct.

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #6462.

### CODE REVIEW

**Review by jeffwidman — APPROVED** [review]
Code change makes sense... Does this need a spec?

**Comment by deivid-rodriguez** [comment]
I only left it as WIP because I didn't have time to write a spec.

**Comment by deivid-rodriguez** [comment]
Finally got around to adding a spec here!

**Comment by deivid-rodriguez** [comment]
Test failures here are unrelated and should be fixed by https://github.com/dependabot/dependabot-core/pull/7862.

**Pull request merged**
