### PR TITLE
Remove accidentally committed node_modules folders

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I think these folders must've been committed by mistake?

### CODE REVIEW

**Review by landongrindheim — APPROVED** [review]
🩸🩸🩸 😵‍💫 🩸🩸🩸

**Comment by jakecoffman** [comment]
The root `.gitignore` has `/node_modules`, should that be `node_modules/`?

**Comment by deivid-rodriguez** [comment]
Awesome catch @jakecoffman! I changed the .gitignore file to disallow all `node_modules/`!

**Comment by landongrindheim** [comment]
> Awesome catch @jakecoffman! I changed the .gitignore file to disallow all `node_modules/`!

While a much better solution, this blood diff is 🤏 less impressive now 🙃 
image

**Review by abdulapopoola — APPROVED** [review]

**Review by jeffwidman — APPROVED** [review]
Let's land this. 🎉

**Pull request merged**
