### PR TITLE
Python: support alternative names / locations for requirements.txt files

### PR DESCRIPTION
**Pull request by greysteil**
Adds FileFetcher to #135.

TODO (GB):
- [x] More specs for parser
- [x] Specs for file updater

### CODE REVIEW

**Comment by greysteil** [comment]
@apanzerj @tristan0x - FYI. 🎉

**Comment by apanzerj** [comment]
woohoo!

**Comment by greysteil** [comment]
All deployed now, too.

**Comment by apanzerj** [comment]
@greysteil so basically I just add the repo and (skimming the code here) it looks for a file that is a txt file in the repo that it can parse?

**Comment by greysteil** [comment]
Yep - Dependabot will now pick up any `.txt` file with `requirements` in its name at the root level, or any file in a `requirements` folder. Any other conventions we should be aware of?

**Comment by apanzerj** [comment]
¯\_(ツ)_/¯ 

It's fine. The team I'm working with uses a requirements folder that has txt files that are each used for different reasons: docs, test, and main. It's not a huge deal, I'm going to try to push them to change things up.

**Comment by greysteil** [comment]
That will be fine if the folder their in is called `requirements` - we'll pick up all `.txt` files in that folder.

**Comment by apanzerj** [comment]
oh cool. I would add that it's kind of hard to tell if everything is "a-okay" since when I run a bump, if nothing happens, I don't know if that is because nothing was found or if everything is up to date. So right now, I'm not sure things are "correct" because when it wasn't reading the txt files, it didn't say anything, and when it is reading the txt files (and things are up to date) it still doesn't say anything.

**Comment by greysteil** [comment]
Interesting. I think we could do a better job of giving feedback in the frontend on that one - rather than saying "Bumped <x> minutes ago" it would be nice to say "All up-to-date" or something like that.

**Comment by apanzerj** [comment]
Yup! Alternatively, for a quick fix/win, a badge maybe?

**Pull request merged**
