### PR TITLE
fix(npm): Detect unsatisfiable version constraints

### PR DESCRIPTION
**Pull request by xlgmokha**
# Why is this needed?

To prevent attempting to update a dependency that cannot be satisfied by
indirect dependency constraints.

E.g the dependency tree for Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161 is:

* turbo360@1.8.68 via "latest" (package.json)
  * cheerio@1.0.0-rc.3 via "^1.0.0-rc.2" (package-lock.json)
    * css-select@1.20 via "~1.2.0" (package-lock.json)
      * css-what@2.1.3 via "2.1" (package-lock.json)

`turbo360` is declared in the package.json manifest with a constraint of "latest".
It depends on `cheerio` which depends on `css-select` which depends on `css-what`.

The constraint defined for `css-what` comes from `css-selector` which is declared as "2.1".
A contraint of "2.1" would need to be changed in order to update `css-what` to `5.0.1`.

The request to update css-what from `2.1.3` to `5.0.1` cannot be satisfied
without first attempting to update `css-selector`, then recursively up the tree.

## What does this do?

It adds a test to reproduce the defect caused by this:

https://github.com/dependabot/dependabot-core/blob/e425a284e67850a9950de5fdbf69f010d01f19c9/common/lib/dependabot/update_checkers/base.rb#L238

/xref: https://github.com/github/dependabot-updates/issues/1511

Before:

```bash
[dependabot-core-dev] ~/dependabot-core $ ./bin/dry-run.rb npm_and_yarn Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161 --dep=css-what --cache=files --commit=a3d15980117871bf159c39035818638b48ffe1ba
=> reading dependency files from cache manifest: ./dry-run/Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161/cache-manifest-npm_and_yarn.json
=> parsing dependency files
=> updating 1 dependencies: css-what

=== css-what (2.1.3)
 => checking for updates 1/1
 => latest available version is 5.0.1
 => latest allowed version is 5.0.1
 => The update is not possible because of the following conflicting dependencies:
   turbo360@1.8.68 requires css-what@2.1 via a transitive dependency on css-select@1.2.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating css-what from 2.1.3 to 5.0.1
Traceback (most recent call last):
        3: from ./bin/dry-run.rb:599:in `<main>'
        2: from ./bin/dry-run.rb:599:in `each'
        1: from ./bin/dry-run.rb:687:in `block in <main>'
/home/dependabot/dependabot-core/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:42:in `updated_dependency_files': No files were updated! (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
```

After:

```bash
[dependabot-core-dev] ~/dependabot-core $ ./bin/dry-run.rb npm_and_yarn Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161 --dep=css-what --cache=files --commit=a3d15980117871bf159c39035818638b48ffe1ba
Resolving dependencies...
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> failed to read all dependency files from cache manifest: ./dry-run/Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161/cache-manifest-npm_and_yarn.json
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/Jessica-Fenhouse/Jessica-Fenhouse-p1-ITDEV161/
=> parsing dependency files
=> updating 1 dependencies: css-what

=== css-what (2.1.3)
 => checking for updates 1/1
 => latest available version is 5.0.1
 => latest allowed version is 5.0.1
 => The update is not possible because of the following conflicting dependencies:
   turbo360@1.8.68 requires css-what@2.1 via a transitive dependency on css-select@1.2.0
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating css-what from 2.1.3 to 5.0.1
```

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Nishnha** [comment]
It seems like you went with option 2 from https://github.com/github/dependabot-updates/issues/1511#issuecomment-858150765
> 2. Remove/ignore the raise NoChangeError because of the reasons listed above. (complexity: low, value: low).

I see the `NoChangeError` was removed in this PR. Can you link to the actual fix to see what this tests against?

**Comment by xlgmokha** [comment]
> It seems like you went with option 2 from [github/dependabot-updates#1511 (comment)](https://github.com/github/dependabot-updates/issues/1511#issuecomment-858150765)
> 
> > 1. Remove/ignore the raise NoChangeError because of the reasons listed above. (complexity: low, value: low).


I'm not 100% sure if this is the best way to go so I'm looking for critical feedback on this change. Please chime in.

> I see the `NoChangeError` was removed in this PR. Can you link to the actual fix to see what this tests against?

Here's what I could find: 

* https://github.com/dependabot/dependabot-core/pull/907
* https://github.com/dependabot/dependabot-core/pull/911

I don't think either of those PR's describe the original rationale for adding the `NoChangeError` so I will need to continue my search for the answer.

**Comment by feelepxyz** [comment]
Thanks for looking into this gnarly one! I'm not sure we want to drop this error as the updater will think the update succeeded and try and create a pull request with no files in it. We could swallow the error in the updater instead if we want to mute this error for now?

I'm leaning towards either tolerating this error or swallowing it in the updater until we have some more bandwidth to fix it properly in the update checker but from old memories this is not entirely trivial.

**Comment by xlgmokha** [comment]
> I'm leaning towards either tolerating this error or swallowing it in the updater until we have some more bandwidth to fix it properly in the update checker but from old memories this is not entirely trivial.

I will look into how to do this. I think I have a rough idea of where to get started. Thank you for the guidance @feelepxyz.

**Pull request closed without merging**
