### PR TITLE
Add shim for Gem::Version.initialize

### PR DESCRIPTION
**Pull request by JamieMagee**
See https://github.com/sorbet/sorbet/pull/7314

### CODE REVIEW

**Comment by JamieMagee** [comment]
This is available in Sorbet version `0.5.11023`

**Review by jakecoffman — APPROVED** [review]
Should we merge this or upgrade to the latest Sorbet to get the change?

**Comment by JamieMagee** [comment]
IMO upgrading Sorbet is the best approach. I just haven't had a chance yet.

**Comment by JamieMagee** [comment]
Superseded by #8064

**Pull request closed without merging**
