### PR TITLE
Upgrade Python to 3.10.4 and support newer releases

### PR DESCRIPTION
**Pull request by henrikhorluck**

### CODE REVIEW

**Comment by henrikhorluck** [comment]
Oh well... this is blocked on a new pyenv release for `3.10.4` — will update as soon as that is available

**Comment by henrikhorluck** [comment]
Oh well... this is blocked on a new pyenv release for `3.10.4` — will update as soon as that is available

**Comment by henrikhorluck** [comment]
As per the `python/README.md`-instructions, one should use a commit-hash instead of release if there has not been a release, so I did as instructed. Should be good to go

**Comment by henrikhorluck** [comment]
> As per the `python/README.md`-instructions, one should use a commit-hash instead of release if there has not been a release, so I did as instructed. Should be good to go

And now a new version of pyenv is out, so this should be extra good to go

**Comment by henrikhorluck** [comment]
@brrygrdn bump, sorry to bother, but any chance of a review (and potentailly merge && release) soon?

**Comment by henrikhorluck** [comment]
@brrygrdn bump, sorry to bother, but any chance of a review (and potentailly merge && release) soon?

**Comment by ulgens** [comment]
@henrikhorluck It's nice someone else pushing these updates too 🌹 


@feelepxyz @landongrindheim @jurre 👋🏻

**Comment by pavera** [comment]
@henrikhorluck thanks for the PR! If you can rebase your branch on current main that'll fix the CI failure and I think we can get this merged in.

**Comment by henrikhorluck** [comment]
> @henrikhorluck thanks for the PR! If you can rebase your branch on current main that'll fix the CI failure and I think we can get this merged in.

Done!

**Review by pavera — APPROVED** [review]

**Pull request merged**
