### PR TITLE
deploy commits made after approval

### PR DESCRIPTION
**Pull request by jakecoffman**
A downside to #5640 was commits pushed after approval aren't deployed.

So to fix that, I've restored the pull_request trigger, but use `gh` to get the review state. Thus if a commit comes in after approval it will still be able to see if was approved. Commits before an approval should be skipped.

### CODE REVIEW

**Comment by jakecoffman** [comment]
Hold off on approving so I can test this. Also I seem to have broken the workflow.

**Comment by jakecoffman** [comment]
Great, it looks like it's working now: 

```
Review decision is: REVIEW_REQUIRED
```

**Review by pavera — APPROVED** [review]
Test away :)

**Comment by jakecoffman** [comment]
The approval trigger worked: https://github.com/dependabot/dependabot-core/runs/8236295929?check_suite_focus=true

**Comment by jakecoffman** [comment]
Update trigger worked too: https://github.com/dependabot/dependabot-core/runs/8236356928?check_suite_focus=true

Only thing left is to test on main 🤞

**Pull request merged**
