### PR TITLE
Remove headers from HTTP fixture recordings

### PR DESCRIPTION
**Pull request by xlgmokha**
# Why is this needed?

To remove non-essential data from test fixtures.

## What does this do?

To remove headers that aren't needed.

### CODE REVIEW

**Review by Nishnha — APPROVED** [review]
LGTM 👍🏾

**Comment by jurre** [comment]
@xlgmokha I don't think we should manually modify these fixtures, those fixtures are recorded by [vcr](https://github.com/vcr/vcr), this means that any time we re-record them that data will be put back.

VCR has [some hooks](https://relishapp.com/vcr/vcr/v/1-10-1/docs/configuration/filter-sensitive-data) to scrub sensitive data, but other than that we should leave these generated files alone IMO.

**Comment by feelepxyz** [comment]
I added some hooks to scrub headers from recordings but missed this old one.

**Comment by xlgmokha** [comment]
Larger recordings make it easier to miss things like accidental inclusion of sensitive data. We purposefully commit manifest files with the minimum data required to isolate defects/features and I think this change aligns with that convention.

Is it possible to specify an allow list of headers rather than a deny list?

**Comment by Nishnha** [comment]
It looks like this VCR recording included an Authorization token but it should have been removed via https://github.com/dependabot/dependabot-core/blob/1a9e69f78066ed135d30fbfc57736e762e95d3eb/common/spec/spec_helper.rb#L66

As far as I can tell, VCR recordings are automated--do we have a way of debugging to find out how this key snuck into the file?

**Comment by xlgmokha** [comment]
> As far as I can tell, VCR recordings are automated--do we have a way of debugging to find out how this key snuck into the file?

A couple of thoughts come to mind. Is it possible that the header was committed before we added the filter? We could try deleting the generated recording and re-running the test and debug the hook to see how it works.

**Comment by feelepxyz** [comment]
Yeah the fixture with the auth header was created just over a year ago: https://github.com/xlgmokha/dependabot-core/commit/f3ef00bbe610998408cb51809b5e09f122b3cf45

I only added the code to strip these out 4 days ago https://github.com/dependabot/dependabot-core/commit/c35256e3b3cd41945aa1b8063081d1cc9bd52dfb

We shouldn't see these added in future recordings.

**Comment by jurre** [comment]
> We purposefully commit manifest files with the minimum data required to isolate defects/features and I think this change aligns with that convention.

For any files that we manually add I think this is a great default, but for generated files it seems needlessly painful and error-prone, we might end up removing headers that turn out to be relevant and future changes might break production without being covered by our tests.

I tend to ~never read these generated files, if we're worried about committing auth-headers maybe a better approach would be to add a linter to catch these?

**Comment by feelepxyz** [comment]
I think there's some miscommunication here? This PR only strips out an old header that was added before this code to automatically strip them out was added: https://github.com/dependabot/dependabot-core/commit/c35256e3b3cd41945aa1b8063081d1cc9bd52dfb

Pretty sure we shouldn't need to worry about this again.

**Pull request merged**
