### PR TITLE
 chore(python): target latest python 3.12.6 version

### PR DESCRIPTION
**Pull request by Greesb**
## What are you trying to accomplish?

This adds support for python 3.12.6

## Anything you want to highlight for special attention from reviewers?

N/A

## How will you know you've accomplished your goal?

N/A

## Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by Greesb** [comment]
@jeffwidman @kbukum1 Can this be merged please ?

**Comment by Greesb** [comment]
(all those changes are just rebase, not real change from the beginning)

**Review by JamieMagee — APPROVED** [review]

**Comment by Greesb** [comment]
@JamieMagee Thanks the approval. Can we merge it ?

Also, for minor upgrades like this would it be possible to make a script to auto upgrade the max supported version ? It seems trivial and would benefit a lot of people i guess. Having to wait more than 2 weeks for a minor upgrade like this is really annoying.

**Comment by JamieMagee** [comment]
@Greesb Unfortunately, I don't have merge rights

**Pull request closed without merging**
