### PR TITLE
Gradle: Add support for parsing dependencySet dependencies

### PR DESCRIPTION
**Pull request by greysteil**
This is a WIP - the `FileUpdater` and `UpdateChecker` will also need to be updated to handle dependencies that are part of a dependency set.

### CODE REVIEW

**Comment by greysteil** [comment]
@bsideup - FYI, you can see this in action [here](https://github.com/greysteil/liiklus/pull/2). 🎉

**Comment by bsideup** [comment]
@greysteil that's amazing, thank you so much! 👍 
Especially cool to see the changelogs for different entries 💯

**Comment by greysteil** [comment]
Yeah, I think it just found the same release notes for each one, though, as they were in a monorepo. If they *weren't* in a monorepo it would have got different changelogs / release notes for each one, though 🙂

**Comment by bsideup** [comment]
@greysteil yes, that's absolutely fine 👍

**Pull request merged**
