### PR TITLE
Bump default PNPM to 9.4.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What are you trying to accomplish?

This is required so that Dependabot works for people using PNPM 9 and not specifying `packageManager` in their `package.json` files.

### Anything you want to highlight for special attention from reviewers?

If `packageManager` is not specified, Dependabot currently uses PNPM 8. When PNPM 8 finds "PNPM 9 lockfiles", it prints a warning like this:

```
 WARN  Ignoring broken lockfile at /home/dependabot/tmp/wJoenn/vue-template: Lockfile /home/dependabot/tmp/wJoenn/vue-template/pnpm-lock.yaml not compatible with current pnpm
```

So it ignores the lockfile and creates a new one from scratch using its own format (lockfileVersion 6), causing the problem reported in https://github.com/dependabot/dependabot-core/issues/9684.

### How will you know you've accomplished your goal?

The problem can be reproduced in a dev shell with

```
$ bin/dry-run.rb npm_and_yarn wJoenn/vue-template --commit eea451a717b4e1f814f840196511fdbef0e1cabb --dep vue
```

With this PR, the lockfile format is no longer reverted to v6.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
All unit test failures seem because of the change in lockfile format but they indicate no regression or further work needed to support PNPM 9. Happy to adapt the specs to work with PNPM 9!

**Comment by yeikel** [comment]
Closes https://github.com/dependabot/dependabot-core/pull/8936

**Comment by deivid-rodriguez** [comment]
I was actually wrong and specs did detect one change that affects us 😢.

**Comment by deivid-rodriguez** [comment]
I checked that PNPM 9.0.0-alpha.5 was the first version that changed the behavior tested by the failing spec, but I did not bisect further.

**Comment by deivid-rodriguez** [comment]
Actually I bisected the issue properly now and found the culprit to be https://github.com/pnpm/pnpm/pull/7715. That makes sense, we rely on the PNPM error when it tries to fetch a git package to detect inaccesible private git dependencies. Since that PR, pnpm no longer tries to fetch packages with `--lockfile-only` is used, so we need to detect it in some other way.

**Comment by deivid-rodriguez** [comment]
In the end I ended up fixing this in the Dependabot core side, it seems too much of an edge case to go through fixing this in PNPM and waiting for a release, and it'd be good to ship a fix for this soon! If CI passes, this should be ready!

**Review by honeyankit — APPROVED** [review]

**Comment by abdulapopoola** [comment]
Thanks so much @deivid-rodriguez !

**Comment by deivid-rodriguez** [comment]
No problem!

**Comment by b1rdex** [comment]
Wouldn't this change lead to another problem: bumping all old lock files to `lockfileVersion: 9` so people using old versions will have broken updates?

**Comment by deivid-rodriguez** [comment]
It depends on how PNPM 9 behaves when finding an old lockfile. I'm not sure, maybe it respects the previous format, or upgrades it automatically. Dependabot will now behave the same as PNPM 9.

**Comment by deivid-rodriguez** [comment]
But, you have a point that Dependabot can do better by using PNPM 8 when finding an old lockfile. This was actually included in the initial fix by @robaiken and makes sense! Let me create a follow up PR.

**Comment by b1rdex** [comment]
> maybe it respects the previous format, or upgrades it automatically

AFAIR, it only leaves it as-is when using `install --frozen-lockfile`. Otherwise, it bumps it to the new version.

**Comment by deivid-rodriguez** [comment]
Oh, I misread @robaiken's PR, this was already introduced by https://github.com/dependabot/dependabot-core/commit/176339f93709a24ca78d8af9d8192c3c20d584cb.

However, I think something is not working quite well with our corepack logic, because with that commit present, Dependabot should've been happily using PNPM9 and not reverting lockfile formats even before this PR 🤔.

**Comment by deivid-rodriguez** [comment]
I'll look into this 👍.

**Comment by deivid-rodriguez** [comment]
I see what the problem is. Corepack creates binstubs for package managers that automatically respect the "packageManager" setting in `package.json`. So that magically works when we run `pnpm`, `yarn`, or `npm` when `packageManager` is set. However, when `packageManager` is not set but we infer the package manager version from the lockfile, we need to make sure the correct version is run ourself.

So the solution is to:
* Make sure ecosystem version information parsed by `FileFetcher`, in particular, the locked PNPM version, is available in the `UpdateChecker` and `FileUpdater` steps.
* Change our helpers to run `pnpm` (or `yarn`, or `npm`) to instead or running `<package_manager> <command>`, they run something like `corepack <pacakge_manager>@<version> <command>`.

I'll try to find some time to work on this although it's not trivial. In any case, the situation after this PR at least has improved a bit, since Dependabot upgrading the lockfile format is better than Dependabot downgrading it.

**Comment by CaoMeiYouRen** [comment]
Hi ,
I noticed that after upgrading to PNPM 9.4.0, Dependabot is modifying the dependency URLs from https://codeload.github.com/ to git+https://git@github.com, which is causing the following error:
```
ERROR  Command failed with exit code 128: /usr/bin/git clone git@github.com:CaoMeiYouRen/rss-parser.git /home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1835_81cad7a39cafa01315f02c3d60683486
```
 [CaoMeiYouRen/rss-impact-server/pull/178](#https://github.com/CaoMeiYouRen/rss-impact-server/pull/178/files)

This seems to be related to the way PNPM handles Git dependencies. 
I would like to know if it is related to this change

**Comment by abdulapopoola** [comment]
Sorry to hear that @CaoMeiYouRen , can you please file a new issue?

**Pull request merged**
