### PR TITLE
feat: Add support for `workspace.dependencies` in `cargo` 1.64.0+

### LINKED ISSUE #5315: Rust: support workspace inheritance
Cargo nightly now supports workspace-level dependencies.

See:

* https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance
* https://github.com/rust-lang/cargo/issues/8415
* https://rust-lang.github.io/rfcs/2906-cargo-workspace-deduplicate.html

### PR DESCRIPTION
**Pull request by poliorcetics**
I did not write tests because I don't know enough Ruby to do it, but I
will gladly accept directions on it.

Closes #5315

See the section on Cargo in https://github.com/rust-lang/rust/releases/tag/1.64.0 for more details about the workspace feature.

### CODE REVIEW

**Comment by poliorcetics** [comment]
Since Dependabot already handled dependencies like `dep = { path = "path" }` without a version, I expect that dependencies with `workspace = true` to work correctly out of the box. This makes this PR simply a matter of teaching Dependabot to look at `[workspace.dependencies]`

**Comment by Nishnha** [comment]
Hi @poliorcetics, thanks for this contribution!

I'm new to the Rust ecosystem, so I did some light reading on [[workspace.dependencies]](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) and it looks like the key is actually called `[workspace.dependencies]` so we should try matching on that instead of `[workspace]` and `[dependencies]` separately.
 

Dependabot will already include any dependencies under the `[dependencies]` key in cargo.toml files with https://github.com/dependabot/dependabot-core/blob/78afa00dbd274ed937d8ff70118d2d4335d39526/cargo/lib/dependabot/cargo/file_parser.rb#L64-L70

In order to get this merged in we will need to test that a project with `[workspace.dependencies]` in its cargo.toml has its dependencies parsed correctly. 

Something similar to https://github.com/dependabot/dependabot-core/blob/78afa00dbd274ed937d8ff70118d2d4335d39526/cargo/spec/dependabot/cargo/file_parser_spec.rb#L123-L151 

The manifest referenced in that file is at https://github.com/dependabot/dependabot-core/blob/78afa00dbd274ed937d8ff70118d2d4335d39526/cargo/spec/fixtures/manifests/repeated_dependency

**Comment by poliorcetics** [comment]
> I'm new to the Rust ecosystem, so I did some light reading on [[workspace.dependencies]](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) and it looks like the key is actually called [workspace.dependencies] so we should try matching on that instead of [workspace] and [dependencies] separately.

This is not a single TOML key, This is a key and a subkey. The following samples are equivalent ([Rust playground code for example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=%23!%5Ballow(dead_code)%5D%0A%0Ause%20toml%3B%0Ause%20serde%3A%3ADeserialize%3B%0Ause%20std%3A%3Acollections%3A%3ABTreeMap%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20s%20%3Dr%23%22%0A%5Bworkspace.dependencies%5D%0Acc%20%3D%20%223.0.0%22%0A%22%23%3B%0A%20%20%20%20let%20a%3A%20Workspace%20%3D%20toml%3A%3Afrom_str(s).unwrap()%3B%0A%20%20%20%20dbg!(a)%3B%0A%20%20%20%20%0A%20%20%20%20let%20s%20%3Dr%23%22%0A%5Bworkspace%5D%0Adependencies%20%3D%20%7B%20cc%20%3D%20%223.0.0%22%20%7D%0A%22%23%3B%0A%20%20%20%20let%20b%3A%20Workspace%20%3D%20toml%3A%3Afrom_str(s).unwrap()%3B%0A%20%20%20%20dbg!(b)%3B%0A%20%20%20%20%0A%20%20%20%20let%20s%20%3Dr%23%22%0Aworkspace.dependencies%20%3D%20%7B%20cc%20%3D%20%223.0.0%22%20%7D%0A%22%23%3B%0A%20%20%20%20let%20c%3A%20Workspace%20%3D%20toml%3A%3Afrom_str(s).unwrap()%3B%0A%20%20%20%20dbg!(c)%3B%0A%7D%0A%0A%23%5Bderive(Debug%2C%20Deserialize)%5D%0Astruct%20Workspace%20%7B%0A%20%20%20%20workspace%3A%20Dependencies%0A%7D%0A%0A%23%5Bderive(Debug%2C%20Deserialize)%5D%0Astruct%20Dependencies%20%7B%0A%20%20%20%20dependencies%3A%20BTreeMap%3CString%2C%20String%3E%2C%20%20%20%20%0A%7D))

```toml
[workspace.dependencies]
dep-name = "version"
```

```toml
[workspace]
dependencies = {  dep-name = "version"  }
```

```toml
workspace.dependencies = { dep-name = "version" }
```

So to parse `[workspace.dependencies]` in a `Cargo.toml`, I need to first look for `workspace`, then inside that, `dependencies`.

Thanks for the guidance on testing, I'll try to write one

**Comment by poliorcetics** [comment]
Test added, could a maintainer launch the CI ?

**Comment by poliorcetics** [comment]
I don't think the failures are related to my changes ?

**Review by Nishnha — APPROVED** [review]
This PR updates the version of Cargo we use in our Dockerfile since it introduces support for a new feature.

I thought about moving the check for workspace dependencies into our existing DEPENDENCY_TYPES.each loop in the file_parser, but it's more maintainable as it is and Cargo workspaces currently only support regular dependencies (as opposed to dev-dependencies and build-dependencies), so this is fine.

**Comment by poliorcetics** [comment]
Thanks for the help and fixing my mistakes @Nishnha, it was greatly appreciated 😄

**Comment by poliorcetics** [comment]
What's left to do ?

**Review by jeffwidman — APPROVED** [review]
I don't know a ton about Rust, but from what I understand this looks straightforward.

We follow a deploy-then-monitor-prod-then-merge strategy, so one of us will try to do that when we get a few spare cycles in the next few days.

**Pull request merged**
