### PR TITLE
Upgrade to latest Ruby patchlevels

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What are you trying to accomplish?

Make sure we support and use the latest Ruby patchlevels. We recently upgraded to 3.3.3 in terms of user Manifest support, but had to pin the version run by Dependabot itself to 3.3.1 because of a bug in Ruby. See discussion in https://github.com/dependabot/dependabot-core/pull/10038.

The bug has been fixed in [Ruby 3.3.4](https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/), so we can reconcile things again now.

### Anything you want to highlight for special attention from reviewers?

Just version updates everywhere.

### How will you know you've accomplished your goal?

CI passes.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Rate limit issues again, but I doubt this PR introduces issues.

**Review by JamieMagee — APPROVED** [review]

**Review by abdulapopoola — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Rebased and updated to 3.3.6.

**Comment by deivid-rodriguez** [comment]
It seems some Bundler smoke specs are broken but I'd say it's not the fault of this PR. Happy to look in those though if necessary.

**Comment by deivid-rodriguez** [comment]
I looked into the smoke test failures. They are specific to Ruby 3.3.6 (Ruby 3.3.5 is fine). I _think_ https://github.com/dependabot/smoke-tests/pull/241 should fix them, but I can't verify because I'm getting the classic rate limiting CI issues.

I also cherry-picked changes from #10279 so that PR can be closed.

**Comment by deivid-rodriguez** [comment]
Finally green!

Next steps should be:

* Merge https://github.com/dependabot/smoke-tests/pull/241.
* Then I remove the latest commit here, rerun CI, and this PR should be still green, and ready for review and hopefully finally merge!

**Comment by JamieMagee** [comment]
Okay, I'll get that merged.

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
NuGet failures are related to rate limiting.

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
Thanks @deivid-rodriguez! Looks like we're good.

Now to re-open the Ruby 3.4.0-rc1 PR 😅

**Pull request merged**
