### PR TITLE
Respect platform requirements if they are set

### LINKED ISSUE #394: PHP platform requirements ignored
_From @ChristophWurst on January 8, 2018 8:40_

Hi,

dependabot created a PR to update one of our composer libraries in https://github.com/nextcloud/twofactor_totp/pull/218. This, however, does not work on our supported platforms (php5.6 to 7.2) as the newest version pulled is only compatible with php => 7.1.

To prevent composer from installing incompatible versions on my dev instance (I'm on php7.2 and thus `composer update` would install software incompatible with lower php versions), I've added a platform override to force php5.6 compatibility: https://github.com/nextcloud/twofactor_totp/pull/216

It seems dependabot ignores this override somehow.

Luckily, Travis detected this incompatibility: https://travis-ci.org/nextcloud/twofactor_totp/jobs/324921046#L1836

_Copied from original issue: dependabot/feedback#70_

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #394

When a user sets the platform requirements we should respect them. Else
proposed new versions might not run on their target platform.

If no platform is set we ignore it all so that the current platform
isn't taken into account.

Todo:
- [ ] Add some test (once I figure out how)
  * Just took them from https://github.com/dependabot/dependabot-core/pull/209

### CODE REVIEW

**Comment by rullzer** [comment]
Seems my spec writing skills are very subpar. Any help is appareciated.

**Comment by greysteil** [comment]
Nice! The spec you copied across was a bit old - I've updated the way we stub Packagist since writing it. Will get it fixed up now.

**Comment by rullzer** [comment]
Glad to give back! We use your product at more and more places over at Nextcloud. Thank you for creating it.

**Comment by greysteil** [comment]
It's a great contribution - thanks! Imagine there might be a little teething trouble as some repos have to add some extensions to their platform overrides to get everything working, but with good error messaging that should be fine. Solving #394 is a really big improvement.

**Pull request merged**
