### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by rebelagentm**
Add support for [Swift Package Manager](https://swift.org/package-manager/) to Dependabot Core.

### CODE REVIEW

**Comment by W5G** [comment]
Merhaba umarım bir sorun yoktur

**Comment by dominicegginton** [comment]
Hi @rebelagentm, is this PR is in the works? very interested to see Swift Package Manager Support added to dependable 😄

**Comment by rebelagentm** [comment]
Hi, @dominicegginton!  I'm no longer working on Dependabot.  I know the team is still planning to add new features, however, they are currently very busy working on the integration with GitHub, so it's going to be some time before that happens.

/cc @feelepxyz

**Comment by rogerluan** [comment]
Resolves #1245

**Comment by pepibumur** [comment]
Are there any updates on this one? It'd be awesome if this could make it to Dependabot.

**Comment by funkenstrahlen** [comment]
I'd love for this to get support in Dependabot as Swift Package Manager usage has grown a lot this year.

**Comment by jurre** [comment]
I'm going to close this out for now as we won't be able to tackle this in the near future

**Comment by reshadf** [comment]
Is it possible to contribute to this from the community? @jurre

**Pull request closed without merging**
