### PR TITLE
Properly infer `.npmrc` for PNPM

### LINKED ISSUE #7731: Dependabot w/ pnpm and private feed returns ERR_PNPM_FETCH_401
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm (pnpm)

### Package manager version

8.6.11

### Language version

Node v18.15.0

### dependabot.yml content
```
version: 2
registries:
  upstreams:
    type: npm-registry
    url: https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/
    token: "PAT:${{AZURE_DEVOPS_PAT}}" # this is the non-base64 encoded PAT with Packaging read/write scope
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - upstreams
    schedule:
      interval: daily
    target-branch: main
    open-pull-requests-limit: 3
    milestone: 163501 # The work item Id to link to the PR
    versioning-strategy: increase
```

### What you expected to see, versus what you actually saw

We have a repository in Azure Devops which uses a single private feed. When running our dependabot pipeline it successfully scans the first package, detects the update, and opens a PR. Then starting with the second package we begin seeing failures. In the logs below `@1js/react-ecs-client` is scanned and finds no update (because it already opened the PR in a previous run). But `@azure/storage-file-datalake` detects that an update is required, but fails before opening the PR.

```
Checking if @1js/react-ecs-client 2.0.4 needs updating
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client
🌍 <-- 200 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client
🌍 <-- 200 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client/2.0.4
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client/2.0.4
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js/react-ecs-client/2.0.4
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js/react-ecs-client/2.0.4
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client/latest
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@1js%2Freact-ecs-client/latest
No update needed for @1js/react-ecs-client 2.0.4

Checking if @azure/storage-file-datalake 12.13.0 needs updating
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake
🌍 <-- 200 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake
🌍 <-- 200 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake/12.14.0
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake/12.14.0
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure/storage-file-datalake/12.14.0
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure/storage-file-datalake/12.14.0
🌍 --> GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake/latest
🌍 <-- 404 https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fstorage-file-datalake/latest
Requirements to unlock own
Requirements update strategy bump_versions
Updating @azure/storage-file-datalake from 12.13.0 to 12.14.0
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.224.0/lib/dependabot/shared_helpers.rb:345:in `run_shell_command': Progress: resolved 0, reused 1, downloaded 0, added 0 (Dependabot::SharedHelpers::HelperSubprocessFailed)
 ERR_PNPM_FETCH_401  GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/@azure%2Fabort-controller: Unauthorized - 401

No authorization header was set for the request.

No authorization settings were found in the configs.
Try to log in to the registry by running "pnpm login"
or add the auth tokens manually to the ~/.npmrc file.
 ERR_PNPM_FETCH_401  GET https://pkgs.dev.azure.com/1edu/_packaging/Upstreams/npm/registry/events: Unauthorized - 401
...
```

I'm not understanding how the first request could succeed, yet subsequent request would suddenly receive a 401. The PAT token I've used is for my personal account, and I'm able to perform a `pnpm install` locally just fine.

### Images of the diff or a link to the PR, issue, or logs
[Full dependabot pipeline logs](https://gist.github.com/AndrewCraswell/a887c681e7747776c8d300eab0aa3113)

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
There are two issues:

* PNPM lockfile updater is not using `NpmrcBuilder` to properly configure private registries. This was an oversight from the initial PNPM implementation since all other lockfile updaters (NPM and Yarn) do it.

This issue is fixed by cherry-picking #8091 from @mburumaxwell.

* Even if an npmrc file is generated, the logic for generating it is incomplete. The `NpmrcBuilder` only looks in the lockfile for finding the proper registry vs scope configuration, but can't work if the lockfile does not include registries or if parsing a specific lockfile is not implemented. However, we have a smarter class, `RegistryFinder`, that can also infer the proper registry by directly querying it and checking which dependencies it serves. This class is already used by the `UpdateChecker` and there's a TODO note on top of `NpmrcBuilder` to refactor it to use `RegistryFinder`: https://github.com/dependabot/dependabot-core/blob/0d64ef28006599f59147c107266719bfc3edc0cb/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L9-L11.

The second commit refactors `NpmrcBuilder` to use `RegistryFinder`, but just for PNPM. Once I validate that this works properly, I can migrate NPM & Yarn too and completely remove lockfile parsing code from this class.

This PR should fix #7731.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This is hard to test, but I did add a test to check that a properly scoped registry is generated in the .npmrc file when only one of the dependencies is listed in a configured private registry.

I added a commit to simplify some npmrc generation tests at 0c0cc10d5b6acb1cfb7e8886c0c84ba63bdf914f. I could extract it to a separate PR but I'll set this as ready in any case.

I plan to follow up with other PRs to implementing this for NPM and Yarn, and eventually completely removing direct parsing of lockfiles from this class. But I think this is a good low risk first step.

**Review by jakecoffman — APPROVED** [review]
Let's try it!

**Review by abdulapopoola — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Ok let's try this!

**Comment by mburumaxwell** [comment]
I just got a chance to test this. I can confirm that the credentials issue is now fixed. However, updating one dependency took about half an hour on my machine. Looking at the logs, a request is made to the private registry for each dependency available in the lock file for each dependency that needs to be updated. I stopped after the first. My thoughts are that came from using the new `RegistryFinder` ...

How can we speed up the operation for finding the registry? Or run it once? I haven't studied much of how it works to offer valid ideas yet.

**Comment by deivid-rodriguez** [comment]
Thanks for testing @mburumaxwell. Yes, this is not performant. I see several improvements that can be made, like the one you suggest of running it just once, not once per dependency. I will look into it.

As a workaround, you can commit an npmrc file with proper registry and scope configuration so that Dependabot does not need to infer it.

**Comment by mburumaxwell** [comment]
I am not entirely sure that works. I tested this out with a repo that only pulls a few packages from one private feed and the rest from the default registry. Maybe my understanding of the npm ecosystem is low but here's the npmrc file:

```
auto-install-peers = true

registry=https://registry.npmjs.org/
@tingle:registry=https://pkgs.dev.azure.com/tingle/_packaging/tingle/npm/registry/
always-auth=true
```

It still goes slow.

I tried executing step by step and through the `RegistryFinder`, I noticed the value for `registry_source_url` will always be null because the public registry is in use.
https://github.com/dependabot/dependabot-core/blob/3887e23a059c7949c752a9ce2623ddb545bfbee8/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L268-L274

Consequently, that will fall on `first_registry_with_dependency_details`
https://github.com/dependabot/dependabot-core/blob/3887e23a059c7949c752a9ce2623ddb545bfbee8/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L33-L35

`first_registry_with_dependency_details` will always make one or more HTTP requests...

I created a sample to try figure out what is happening or how to solve it.
https://dev.azure.com/tingle/dependabot/_build/results?buildId=66063&view=logs
https://dev.azure.com/tingle/dependabot/_git/pnpm-auth-test

Could there be something I am missing?

**Comment by deivid-rodriguez** [comment]
Thanks for your investigation. I think that may be a problem with my patch. If scopes are already configured, I was not expecting to go through this logic. I'll look into it!

**Comment by mburumaxwell** [comment]
@deivid-rodriguez As you look into this, I made an assumption that if the registry is not present in the lockfile, the global one should be used. It increased the speed significantly (the numerous HTTP requests are no longer made). 
See https://github.com/mburumaxwell/dependabot-core/commit/4bcf888f8823e0d0c27e55ccaa71eefe31a09db1

I do not know what else it affects but at least it works as expected and could be a hint on which direction to check.
If by chance it is the right direction, let me know then I can create a PR.

**Comment by deivid-rodriguez** [comment]
@yeikel Working on a fix at #8330, feel free to give it a try!

**Pull request merged**
