### PR TITLE
Docker rewrite

### LINKED ISSUE #946: Docker image is huge
[dependabot/dependabot-core](https://hub.docker.com/r/dependabot/dependabot-core/) image from [Dockerfile](https://github.com/dependabot/dependabot-core/blob/426fff73823cd27c6a65e1f220e936262cd07a96/Dockerfile) is amazing!

But it now exceeds [1 GB](https://hub.docker.com/r/dependabot/dependabot-core/tags), which is starting to be huge. ([why](https://developers.redhat.com/blog/2016/03/09/more-about-docker-images-size/) it [matters](https://semaphoreci.com/blog/2018/03/14/docker-image-size.html))

Some suggestions to optimize Dependabot's image (sorted by difficulty):
- [ ] Follow basic `apt` recommandations:
  * Use of `apt-get update` should be paired with `rm -rf /var/lib/apt/lists/*` in the same layer.
  * Use of `apt-get upgrade` must be avoided in a Dockerfile. ([ref](http://crosbymichael.com/dockerfile-best-practices-take-2.html)).
  * Consider using a `--no-install-recommends` when `apt-get` installing packages.
- [ ] Exclude development dependencies when distributing "production" image (#851).
  * Can be optimized easily with `build` scripts and an environment variable.
- [ ] Use [stages](https://docs.docker.com/develop/develop-images/multistage-build/) to build helpers and avoid excessive binaries distribution.
  * For example (if I'm correct) `golang` is not required to _run_ the helpers once built.
- [ ] Switch to a smaller base image for the last stage, commonly to Alpine.

### PR DESCRIPTION
**Pull request by LeoColomb**
- [x] dependabot-common (tested, actively using it)
	- dependabot-bundler
	- dependabot-docker
	- dependabot-nuget
	- dependabot-git_submodules
	- dependabot-gradle
	- dependabot-maven
- [x] dependabot-composer (tested, actively using it)
- [x] dependabot-terraform
- [x] dependabot-python
- [x] dependabot-go_modules
- [x] dependabot-dep
- [x] dependabot-cargo
- [x] dependabot-elm
- [x] dependabot-hex
- [x] dependabot-npm_and_yarn (tested, actively using it)
  ~~For efficiency, I would build it with [pkg](https://github.com/zeit/pkg) to obtain a single binary. Will submit a separate PR (#988).~~ _Rejected_
- [x] dependabot-omnibus

Target|Image size before|Image size after|Time to run before|Time to run after
---|---|---|---|---
bundler|> 1 GiB|84.12 MiB|2 min 24 s|58 s
composer|> 1 GiB|128.88 MiB|4 min 10 s|2 min 13 s
npm_and_yarn|> 1 GiB|104.72 MiB|3 min 16 s|1 min 50 s

Time to run includes loading time, and represents an execution on a GitLab CI shared runner.

Thoughts? 🙏 

Fix #946

### CODE REVIEW

**Comment by hmarr** [comment]
Thanks for submitting this! Looks like a great step in exactly the right direction.

A few thoughts:

### Maintaining monster-image support

I'd be really nice to preserve the ability to build a monster image that contains everything. While we're keen to move to smaller images in production (to reduce the startup time of update jobs), there are cases where it'd be easier to just use one big image - for instance some people running Dependabot on-prem would rather just have one image we can provide.

When I started playing around with splitting up the Dockerfile pre-refactor, I ended up with two scripts per package manager - a helper build script (as currently exists) and an environment setup script, which would be responsible for installing runtime dependencies into the container. That way, we can simply run the same scripts from the lean image Dockerfiles and from the monster image Dockerfile.

### Clarification of the structure of `/opt`

The `/opt` dir currently contains both the source for the helpers, and the installed artefacts. Maybe not one for this PR, but I'm keen to clean that up. It could be as simple as reserving `/opt` for the installed helpers (i.e. Go binaries, or in the case of languages such as JavaScript, the source + the installed dependencies in a `node_modules` folder - or the pkg approach you mentioned).

### Having a good story around local development

I'd like it to be trivial to develop a) locally on a developer's laptop, within their native OS, and b) in a locally-run Docker container. To make this so, I think we'd need a couple of changes.

1. We'd need to be able to build an image that includes the compile/build-time dependencies (so you can e.g. rebuild a native Go helper within a container), and also the runtime dependencies so the helpers can be executed in the same container. Re-running a multi-stage container build after each change to a helper probably isn't conducive to a productive development workflow :-)

2. Simplify the build scripts. Currently you have to provide an install dir as an argument, which can be confusing. Instead, I propose we default to the `DEPENDABOT_NATIVE_HELPERS_PATH` environment variable, and fall back automatically to a `tmp/native-helpers` directory in the root of the repo (untracked in version control). This will also have the benefit of simplifying the Docker mount options - we currently mount only specific files and directories to avoid including helpers built for a different architecture (for instance, if you're working on a Mac but running Linux development containers).

Sorry for the essay! I'd love to hear your thoughts. If you're broadly in agreement, then we can split up the work and try to do it incrementally to avoid a long-running branch that we need to endlessly rebase :-)

**Comment by hmarr** [comment]
I just pushed an example of what the updated build script might look like [here](https://github.com/dependabot/dependabot-core/compare/make-go-modules-build-script-less-confusing?expand=1) - it's perhaps easier to follow the code than paragraphs of text!

And thinking about this further, I think the trickiest thing to achieve will be the monster development image, as it'd effectively need to merge all of the native base images. We'll still need to partially solve that problem anyway, as we'll need multiple language runtimes to exist for e.g. running the native JS helpers, as it'll still be using the Ruby base image.

**Comment by hmarr** [comment]
At risk of complicating this too much, here's one option that I think would cover all cases.

Each package manager has three scripts:
- `install_build_dependencies` - e.g. install the Go compiler, or composer in the case of PHP
- `install_runtime_dependencies` - e.g. no-op for Go, or install node.js for JS.
- `build_helpers` - the existing script that compiles natives helpers / installs their dependencies, etc.

Crucially, all scripts would leave all output (compiler / interpreter / compiled helpers) in a specified directory, so could be used as part of a multi-stage Docker build, or could be run in a monster-image Dockerfile too.

Anyway, I'd love to hear your thoughts @LeoColomb! Sorry for the massive wall of text... 😬

**Comment by LeoColomb** [comment]
> Sorry for the massive wall of text...

No worry, happy to read this ***monster*** reply! 😉 

> Maintaining monster-image support

Sure. Definitely.
I've also got some hesitation around an `install` script, but the thing is dependencies installation is very specific to the platform.
I made the choice to use Alpine here, as it is _the_ image to use for small footprint in production.
If we switch the monster core image to Alpine, everything will be fine.
But using Alpine for interactive usage may require some user adaption (if you see what I mean 😆).

Anyway, yes, the three scripts seems a bit complicated.
IMO, if you have docker images with _build_ helpers, only runtime dependencies are required.

I mean:
```dockerfile
FROM alpine

RUN python/install
RUN composer/install
RUN ...

COPY --from=dependabot/dependabot-python /opt/python/helpers /opt/python/helpers
COPY --from=dependabot/dependabot-composer /opt/composer/helpers /opt/composer/helpers
COPY ...
COPY --from=dependabot/dependabot-dep /opt/dep/bin /opt/dep/bin
```

That said, this excessive docker layering may not be the most cleaner...

> Clarification of the structure of `/opt`

I'm not sure to understand well here (sorry).
If you mean you want that `/opt` contains **only** what is required, then yes, this is what I tried to do.

> Having a good story around local development

Sure! 😸 

> 1. We'd need to be able to build an image that includes the compile/build-time dependencies

Well, that's much more complicated.
Some build/runtime dependencies may require even more dependencies for a flexible dev env.
As an example: elm do require Node.js for REPL usage (then many local/dev execution) but not to compile.

So the bad thing here is that even if we succeed to make the prod-monster-image easy to maintain, you will still need to maintain the dev image separately. AFIAK

> 2\. Currently you have to provide an install dir as an argument, which can be confusing.

👍 👍 👍 👍 👍 👍 👍 👍 
(but I prefer not doing this in this PR, this is not required to make it working)

**Comment by hmarr** [comment]
We haven't forgotten about this @LeoColomb - I'm hoping to pick this up soon!

One additional thing - since this is such a big contribution we need something from you saying that you're happy to gift the IP of any code you contribute to Dependabot for us to use however we wish (which is, of course, to merge into the product and treat the same way as the rest of Dependabot Core). A GitHub comment saying that is totally fine.

Thanks!

**Comment by LeoColomb** [comment]
No worries, take your time! 😊

You mean a sort of DCO? Sure, no problem, I'm OK with that. 

```
Signed-off-by: Léo Colombaro <git@colombaro.fr>
```

**Comment by LeoColomb** [comment]
Added a dependabot-omnibus dockerfile for the all-in-one example, without install scripts for now.

**Comment by greysteil** [comment]
Thanks @LeoColomb!

> You mean a sort of DCO? Sure, no problem, I'm OK with that.

I mean more like we were given [here](https://github.com/dependabot/dependabot-core/pull/614#issuecomment-410408876). Would be great if you could say that for this PR and all previous an future contributions, just to keep the lawyer in me happy (and allow me to avoid adding a CLA bot or anything like that). 🙂

**Comment by LeoColomb** [comment]
Understood 🙂 

I'm gifting the IP of the contents of this PR and the other contributions I authored to Dependabot for it to be used however Dependabot wishes.

**Comment by greysteil** [comment]
Legend, thanks! We'll try to get this merged ASAP, apologies for the delay!

**Comment by asummers** [comment]
Just curious if there's anything outstanding for this that is preventing merging this PR.

**Comment by greysteil** [comment]
It needs @hmarr to pick it up, but there's lots on his plate right now. I'm not sure anyone else can really help with it. Sorry about that!

**Comment by hmarr** [comment]
Sorry for not getting this across the line! We've been super busy with other things since the GitHub acquisition.

In general, this is a big improvement over the previous setup. We've been planning to split up the Dockerfiles for a long time, but never managed to prioritise the work. That said, I don't feel totally comfortable merging this right now for a few reasons:
- A few of the tests are failing with this setup.
- While in theory this shouldn't interfere too much with our existing setup, it does make a few changes to the helper scripts. I'd like to verify that this doesn't break anything in our build process before merging.
- Until we move over to this setup ourselves, we'll have to keep the old Dockerfiles around too. This PR already duplicates some of the setup between 2 Dockerfiles (the per-package-manager Dockerfile and the Omnibus one), and with the original Dockerfile we'll have three copies each languages setup in different places. I worry this will make it harder to make changes, that we'll get a lot of version / config drift between the different files.

So given that, I think it's best to keep this as a branch for now, and when we pick up the work of moving to per-language images, we can hopefully get this merged and support it properly.

**Comment by LeoColomb** [comment]
> * A few of the tests are failing with this setup.

That one is not very fair @hmarr! 😆
Essentially no active file is edited and the build is not that stable (I made many rebases and the build is failing randomly https://circleci.com/gh/dependabot/dependabot-core/tree/pull%2F986).

No problem for the others points, please let me know if I can help you.
BTW, may I host docker images based on these docker file on my hub account? This may help others who need lighter images.

**Comment by hmarr** [comment]
😬sorry @LeoColomb! I totally retract my statement about the tests. The build used to be fairly stable - we should get that fixed.

I don't have a problem with you pushing the images to your Docker account, but @greysteil knows more about the Ts & Cs than I do 👨‍⚖

And thanks for understanding on the other points - I know this isn't the ideal outcome! We'll get there :-)

**Comment by greysteil** [comment]
> I don't have a problem with you pushing the images to your Docker account, but @greysteil knows more about the Ts & Cs than I do

Totally chill on that  - no legal issues.

**Comment by LeoColomb** [comment]
Alright! Then for anyone interested I maintain the image of each of these Dockerfiles _via_ [leocolomb/dependabot](https://hub.docker.com/r/leocolomb/dependabot). They are build automatically when relative helper files are modified.

Each [variant](https://github.com/dependabot/dependabot-core/pull/986#issue-251517018) have [its tag](https://hub.docker.com/r/dependabot/dependabot-core/tags), eg. use `leocolomb/dependabot:common` for bundler and `leocolomb/dependabot:composer` for composer.

**Comment by andrcuns** [comment]
Hey guys! Any progress/blockers for this?

I'm using current docker image in a separate app for gitlab and in tandem with running it as non root user (have to chown all of the helpers for that to work) it makes final image 7.3Gb 😱 

Implementing smaller image + non root user would be very helpful. I can help out if necessary.

**Comment by feelepxyz** [comment]
> Implementing smaller image + non root user would be very helpful. I can help out if necessary.

@andrcuns this is done 👍  we now create a `dependabot` user in the main `Dockerfile`. Let us know if this is working for you. There are some updated instructions in dependabot-script: https://github.com/dependabot/dependabot-script#running-script-with-dependabot-script-dockerfile

**Comment by andrcuns** [comment]
> > Implementing smaller image + non root user would be very helpful. I can help out if necessary.
> 
> @andrcuns this is done 👍 we now create a `dependabot` user in the main `Dockerfile`. Let us know if this is working for you. There are some updated instructions in dependabot-script: https://github.com/dependabot/dependabot-script#running-script-with-dependabot-script-dockerfile

Yep, I saw that, thanks. With few adjustments works as expected!

**Comment by xlgmokha** [comment]
Good news: The savings created in this PR look amazing!
Bad news: At the moment we've standardized on Debian.

Dependabot is shipped on Debian at this time. We're expanding where Dependabot can run but Alpine Linux isn't an environment that we're prepared to support at this time.

Thank you for taking the time to submit this pull request. Unfortunately, at this time we cannot accept this submission.

**Pull request closed without merging**
