### PR TITLE
fix(gitlab): pr creator missing default for target_project_id

### PR DESCRIPTION
**Pull request by THETCR**
Before #8729 `target_project_id` was `nil` when it was not provided.
Version ^0.240.0 upward is therefore broken for consumers on Gitlab.
This should be the default behaviour again.

### CODE REVIEW

**Comment by THETCR** [comment]
@JamieMagee

**Comment by THETCR** [comment]
Fixes #8846

**Comment by yeikel** [comment]
Can we add a test for this?

**Comment by THETCR** [comment]
@JamieMagee I just rebased and pushed again. Since I figured the PPA would be back online again by now. 
Hopefully you can merge this before the next release.

**Comment by JamieMagee** [comment]
Unfortunately I don't have merge rights. Let me ping someone who does.

**Review by jakecoffman — APPROVED** [review]

**Pull request merged**
