### PR TITLE
Attempt to fix *-* range handling

### LINKED ISSUE #3540: Dependabot tries to change *-* nuget package versions to -* which nuget does not know how to process.
**Package ecosystem**

Nuget
**Package manager version**

The version shipped with the .NET 6 Preview 3 SDK.
**Language version**
C# latest (C# 9 or 10 I do not remember which one) But yes it's set to always use the latest version of C# so I can refactor to the new syntax features constantly.

**Manifest location and content prior to update**

I would check for every *.props file under the root of the repository and the Sdk/ sub-directory of the project for the files that use ``PackageReference``. Yes the Project files themselves do not directly reference the packages to try to keep them short and clean.

Also the pull requests failed on the CI, so my github actions workflow to auto merge the github native dependabot pr's resulted in them not getting merged so the "manifest" files was left unchanged for now.
**dependabot.yml content**

https://github.com/Elskom/Sdk/tree/main/.github/dependabot.yml
**Updated dependency**

``GenericPluginLoader`` from ``*-*`` -> ``-*`` (invalid version pattern to nuget which breaks ``dotnet restore`` or even ``dotnet build``)

**What you expected to see, versus what you actually saw**
I expected dependabot to not open an PR to change ``*-*`` to ``-*`` which the nuget package manager does not support or like (to nuget it's a by design unsupported version pattern).

**Native package manager behavior**

I use nuget and I later froze my own projects (inside of my Sdk.props file) to ``*-*`` because ``*`` only includes stable releases, while ``*-*`` also includes stable, and latest prereleases (if there are any published that is). I also froze common analyzer packages within that file as well too. The version freeze was because of the number of times dependabot wanted to update them and if I hard coded the versions of the other things would result in endless tagging and releases that do no benefit but changing versions on the SDK not to mention cluttered tags and it then all becomes a mess.
**Images of the diff or a link to the PR, issue or logs**
https://github.com/Elskom/Sdk/pull/177

**🕹 Bonus points: Smallest manifest that reproduces the issue**

I think the smallest manifest to reproduce this is as simple as adding a ``PackageReference`` to a new .NET console application then changing the fixed version number to ``*-*`` and provide the xml attribute that the .NET SDK uses to flag it as an implicit reference (oddly rider does not support this since forever but VS2019 does) 🤣. For .NET Console applications ``System.CommandLine`` can be used to reproduce it.

### PR DESCRIPTION
**Pull request by Danielku15**
Fixes #3540 
This PR introduces a similar change like in https://github.com/dependabot/dependabot-core/commit/528431659e0603aebd9713c274cac50239af4e90 but also considering `*-*` wildcards. 

Tested the fix against my concrete use case and the result is as expected (see comments below).

### CODE REVIEW

**Comment by AraHaan** [comment]
Couldn't you run dependabot within WSL2 on Windows with the newest version of Ubuntu in the Microsoft Store?

**Comment by Danielku15** [comment]
@AraHaan It's all not so easy. I am a bit reluctant so spoil my system with all these tools and configurations just to get a "simple" ruby script running. I tried to get it running in WSL but the next problem was instantly: You can't even test dependabot with also setting up docker. The whole system seems a bit overengineered and unless you are really an established dependabot developer the hurdle to develop and test is really high because there are so many tools and things involved.

**Comment by Danielku15** [comment]
After a long time fiddling on my env I got some version running but I have to clearly say: The current process it neither Windows nor Contributor friendly. There are so many dependencies and tools involved to run at the end a rather simple (but powerful) ruby script. There is big potential for improvement in this regards. 

I ran the tests against my repository and the results look promising: 

Before my fixes: 
```
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/CoderLine/alphaTabSamplesDotNet/
=> parsing dependency files
=> updating 3 dependencies: AlphaTab, AlphaTab.Windows, JetBrains.Annotations

=== AlphaTab ()
 => checking for updates 1/3
 => latest available version is 1.2.2
 => latest allowed version is 1.2.2
 => requirements to unlock: own
 => requirements update strategy:
 => updating AlphaTab to 1.2.2

    ± src/AlphaTab.Samples.PngDump/AlphaTab.Samples.PngDump.csproj
    ~~~
    7c7
    <         <PackageReference Include="AlphaTab" Version="*-*"/>
    ---
    >         <PackageReference Include="AlphaTab" Version="-*"/>
    ~~~

    ± src/AlphaTab.Samples.ScoreDump/AlphaTab.Samples.ScoreDump.csproj
    ~~~
    7c7
    <         <PackageReference Include="AlphaTab" Version="*-*"/>
    ---
    >         <PackageReference Include="AlphaTab" Version="-*"/>
    ~~~

=== AlphaTab.Windows ()
 => checking for updates 2/3
 => latest available version is 1.2.2
 => latest allowed version is 1.2.2
 => requirements to unlock: own
 => requirements update strategy:
 => updating AlphaTab.Windows to 1.2.2

    ± src/AlphaTab.Samples.Player/AlphaTab.Samples.Player.csproj
    ~~~
    7c7
    <         <PackageReference Include="AlphaTab.Windows" Version="*-*"/>
    ---
    >         <PackageReference Include="AlphaTab.Windows" Version="-*"/>
    ~~~

    ± src/AlphaTab.Samples.WinForms/AlphaTab.Samples.WinForms.csproj
    ~~~
    8c8
    <         <PackageReference Include="AlphaTab.Windows" Version="*-*"/>
    ---
    >         <PackageReference Include="AlphaTab.Windows" Version="-*"/>
    ~~~

    ± src/AlphaTab.Samples.Wpf/AlphaTab.Samples.Wpf.csproj
    ~~~
    26c26
    <         <PackageReference Include="AlphaTab.Windows" Version="*-*" />
    ---
    >         <PackageReference Include="AlphaTab.Windows" Version="-*" />
    ~~~

=== JetBrains.Annotations (2021.3.0)
 => checking for updates 3/3
 => latest available version is 2021.3.0
 => latest allowed version is 2021.3.0
    (no update needed as it's already up-to-date)
```

After my fixes: 
```
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/CoderLine/alphaTabSamplesDotNet/
=> parsing dependency files
=> updating 3 dependencies: AlphaTab, AlphaTab.Windows, JetBrains.Annotations

=== AlphaTab ()
 => checking for updates 1/3
 => latest available version is 1.2.2
 => latest allowed version is 1.2.2
 => requirements to unlock: update_not_possible
 => requirements update strategy:
    (no update possible 🙅‍♀️)

=== AlphaTab.Windows ()
 => checking for updates 2/3
 => latest available version is 1.2.2
 => latest allowed version is 1.2.2
 => requirements to unlock: update_not_possible
 => requirements update strategy:
    (no update possible 🙅‍♀️)

=== JetBrains.Annotations (2021.3.0)
 => checking for updates 3/3
 => latest available version is 2021.3.0
 => latest allowed version is 2021.3.0
    (no update needed as it's already up-to-date)
```

**But:** I'm not yet 100% happy with my change. "latest allowed version" should actually point to the [1.3.0-alpha.177](https://www.nuget.org/packages/AlphaTab.Windows/1.3.0-alpha.177) version as we include pre-releases. I'd like to ensure first that we actually manage to tell dependabot to consider the new prereleases but then still not make a change because of the wildcard. Converting the PR to a draft until this is solved.

**Comment by Danielku15** [comment]
https://github.com/dependabot/dependabot-core/pull/4255 + latest fix is needed to get the expected output like:

```
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/CoderLine/alphaTabSamplesDotNet/
=> parsing dependency files
=> updating 3 dependencies: AlphaTab, AlphaTab.Windows, JetBrains.Annotations

=== AlphaTab ()
 => checking for updates 1/3
 => latest available version is 1.3.0-alpha.177
 => latest allowed version is 1.3.0-alpha.177
 => requirements to unlock: update_not_possible
 => requirements update strategy:
    (no update possible 🙅‍♀️)

=== AlphaTab.Windows ()
 => checking for updates 2/3
 => latest available version is 1.3.0-alpha.177
 => latest allowed version is 1.3.0-alpha.177
 => requirements to unlock: update_not_possible
 => requirements update strategy:
    (no update possible 🙅‍♀️)

=== JetBrains.Annotations (2021.3.0)
 => checking for updates 3/3
 => latest available version is 2021.3.0
 => latest allowed version is 2021.3.0
    (no update needed as it's already up-to-date)
```

**Comment by AraHaan** [comment]
Oh sweet, thanks for the fix.

**Comment by Nishnha** [comment]
Hi @Danielku15,

I'm really sorry to hear about your experience in contributing to Dependabot. I don't know how well WSL 2 and Docker work together, but if you are able to install Docker Desktop natively on your machine (or even just Docker machine), the `docker-dev-shell` script should "just work". I'll run through the setup instructions on my personal Windows computer and see what we can improve!
https://github.com/dependabot/dependabot-core#running-with-docker


I'll take a look at merging https://github.com/dependabot/dependabot-core/pull/4255 so that we can unblock the work you did on this PR.

Thank you for your contribution! ❤️

**Comment by Danielku15** [comment]
@Nishnha On Topic: Regarding the failing CI/CD I will take care to get them green. 😉  Seems just to be some linting problem with trailing whitespaces (I really need to setup Notepad++ to trim these automatically 😅)

Off topic: I would have seem some opportunities in improving the development process. Beside the unfortunate dependency issue with libraries not working well on Windows which could be reviewed, the dry-run script could use some flexibility:  It could only require the packages it actually needs to run ignoring others (e.g. going in with dry-run.rb nuget should only require dependabot/nuget, eliminating the need of installing a lot of dependencies). While docker is nice for deterministic tests and runs, for local quick tests I guess it is maybe not needed. As long the deps are available on the host machine the script could try to run locally.

**Comment by Nishnha** [comment]
> the `dry-run script` could use some flexibility: It could only require the packages it actually needs to run ignoring others. 

> This would eliminate the need of installing a lot of dependencies. 

Maybe something like running `docker-dev-shell --minimal` which just installs Dependabot could work? Then you could manually install whichever ecosystem(s) you need for a `dry-run` by `cd`-ing into the appropriate package manager's directory and running `bundle install`. 

This is essentially what running the development image in docker (without the `docker-dev-shell` script) or building from source would do, but it's not really that clear. https://github.com/dependabot/dependabot-core#building-the-development-image-from-source

**Comment by AraHaan** [comment]
Is this ready for merge? we really need something like this ASAP.

**Comment by Nishnha** [comment]
> Is this ready for merge? we really need something like this ASAP.

This PR looks good to me. I appreciate the two test cases you added @Danielku15! 

I updated https://github.com/dependabot/dependabot-core/pull/4255 so its CI should be all passing. Once that's reviewed + approved, I'll merge this in.

I want to include these two PRs in the same Dependabot release so that we avoid the issue described in https://github.com/dependabot/dependabot-core/pull/4749#issuecomment-1046015465 and have `pre-releases` correctly show up.

**Review by Nishnha — APPROVED** [review]

**Comment by AraHaan** [comment]
@Nishnha ready to merge?

btw how long after merge would we have to wait for the release on the live instance of the github dependabot to start using the fixes from this PR?

**Comment by Nishnha** [comment]
> @Nishnha ready to merge?

Yep ^-^

> btw how long after merge would we have to wait for the release on the live instance of the github dependabot to start using the fixes from this PR?

Like 1-2 days. It's towards the end of my workday but I will make sure this is released in a timely manner.

**Pull request merged**
