### PR TITLE
Upgrade Bundler to 2.5.11 and RubyGems to 3.5.11

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It needs the tweak I mentioned in https://github.com/rubygems/rubygems/pull/7659#issuecomment-2114690972.

Two of the failing specs I think are just because Bundler got smarter (and Dependabot should get smarter too as a side effect), so I updated expectations.

There's one more failing that I'm not sure about and I'd need to dig in more.

Opening a WIP PR to check smoke tests too.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This should be ready now!

Some expectations changed, but I think it's just because Dependabot will be smarter now and able to create more PRs. So I mostly updated the expectations.

**Comment by jurre** [comment]
Thanks @deivid-rodriguez! Can we also get rid of our recent bundler patch with this upgrade?

**Comment by deivid-rodriguez** [comment]
Oh good point, let me remove it!

**Comment by deivid-rodriguez** [comment]
I think I may have pushed too many times and reached some rate limit, apologies! This should be ready now I believe.

**Review by abdulapopoola — APPROVED** [review]

**Comment by abdulapopoola** [comment]
Thanks @deivid-rodriguez !

**Pull request merged**
