### PR TITLE
JS: Sanitize any variables in a package.json before parsing/updating

### PR DESCRIPTION
**Pull request by greysteil**
Fixes the underlying issue in https://github.com/dependabot/feedback/issues/42.

### CODE REVIEW

**Comment by greysteil** [comment]
@sobolevn - does this roughly make sense to you? Is there anything I'm missing about how variables in a `package.json` could be being provided (i.e., any way we might not have to just `sanitize` them out during the updating process)?

(Don't worry too much about the details of the Ruby code if it's not your language - I'm more interested in whether this is conceptually the right thing to do.)

**Comment by sobolevn** [comment]
I guess so, but it is worth mentioning that `npm` will normally raise an error if the `name` is invalid. And `{{ name }}` is invalid because of the `{{ }}`. But since it is used in a template that the only way.
So consider it as a corner case.

Thanks! When I can test this?

**Comment by greysteil** [comment]
Just deployed it and kicked off an update run for you - PRs are at https://github.com/wemake-services/wemake-vue-template/pulls 🎉

**Comment by sobolevn** [comment]
It works!

**Pull request merged**
