### PR TITLE
Add factories for gitlab api clients

### PR DESCRIPTION
**Pull request by codisart**
Here my proposal for factories for the gitlab api clients

### CODE REVIEW

**Comment by greysteil** [comment]
Sorry, been crazy busy for the last couple of days. I'll get this properly reviewed tomorrow - thanks for your patience!

**Comment by greysteil** [comment]
OK, I see what you're doing here and it makes sense as a refactor, but it's a little unidiomatic for Ruby (where I don't often see factories) and makes the pattern we're using for GitLab different to the one we're using for GitHub. For that reason I'm going to close - sorry for the wasted work 😢.

**Comment by greysteil** [comment]
(It looks like there was no functionality change here, just a refactor, but if you were planning to add one later let's re-open and figure out a way forward.)

**Comment by codisart** [comment]
I am more than motivated to do the same pattern for github. In fact, I have sevreal ideas to prevent shotgun surgeries. I have actually created last year the same type of bot in php and I had the same problem.
About your point of factories not be idiomatic in ruby (I know there is a "violent" debate about dependency injection in ruby ^^), I think it is important to not see this as simply the factory pattern but as a "extract class" refactoring. Ruby is a pure object language and I think it makes sense to be aware of oop code smells.

**Comment by greysteil** [comment]
👍. OK, in that case let's get something done here 🙂.

I've just refactored the GitHub client creating calls in [this commit](https://github.com/dependabot/dependabot-core/commit/7f282fa8f2cf72337b36d66f6b1d0bf5d37ec761). It would be awesome to have a `GitlabClient` class that worked similarly (no need to add retrying logic yet, unless you're keen to). I prefer a class with constructor methods (like [this one](https://github.com/dependabot/dependabot-core/commit/7f282fa8f2cf72337b36d66f6b1d0bf5d37ec761#diff-9c55d74cd9e2054501e6fd89fd95a992R27)) to factory classes, if you're OK with switching this PR to that format?

Thanks for the contribution, and for pushing me to refactor things here!

**Comment by codisart** [comment]
Ok for me

**Comment by codisart** [comment]
Should we put these two classes in their own directories ?

**Comment by greysteil** [comment]
Could do, although I'm happy with them living in lib, too - there won't be that many more of them (just Bitbucket and VSTS at some point).

**Comment by greysteil** [comment]
Apologies it's taken me so long to get this merged - I didn't see that you'd pushed changes. I'm combining it with the Bitbucket client work now, and should have it merged in the next hour - leave it to me, and thanks for the PR!

**Pull request merged**
