### PR TITLE
Try fix in-app vs outside-app frame classification in Sentry

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Trying out an alternative to #6282.

### CODE REVIEW

**Review by brrygrdn — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Just wrapping things up here. I ended up merging #6282 because otherwise we won't get proper grouping on subcommand failed errors (not fully sure why).

Still, I think this PR is an improvement because it considers paths in ecosystem specific folders as "in-app" which means those frames in the stacktrace are displayed in Sentry by default.

If others agree, I'll merge this.

**Comment by jeffwidman** [comment]
I honestly don't have full context here, but I trust your judgement. If you think it's an improvement, then let's merge it and try it out... can always revert if it's not...

**Comment by deivid-rodriguez** [comment]
This seems to have done what I wanted, sawing the full backtrace (ecosystem + updater) by default. Hope you like it better too!

**Comment by Nishnha** [comment]
The stack traces are really clean and only show dependabot-core traces, and they're properly grouped by the subprocess command. Thank you!!

**Pull request merged**
