### PR TITLE
Return name unless contains git dependency name notation

### LINKED ISSUE #4519: Terraform PRs titles no longer container resource name
I am observing this on GitHub, but I think the bug is coming from dependabot core.  It may be related to #4440 as this issue just started in the last week, and that's right around when this patch to terraform functionality was applied.

**Package ecosystem**
Terraform

**What you expected to see, versus what you actually saw**
Up until a week ago, the PRs created by dependabot for my terraform manifests had fully descriptive names, eg `Bump hashicorp/kubernetes from 2.3.2 to 2.7.0`

In the last week, the name of the resource provider appears to have been dropped from the PR name, and my PRs are now titled like `Bump from 2.68.0 to 2.88.1`, which is clearly not very useful when trying to review the PR list.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

### PR DESCRIPTION
**Pull request by dwc0011**
Closes #4519  - returns name unless it contains git dependency name notation/

### CODE REVIEW

**Comment by dwc0011** [comment]
I am adding in a unit test now to test display name, I will add to this PR or create a new one if this has been merged prior to that.

**Comment by jurre** [comment]
Really appreciate you tackling this @dwc0011 🙇 

I'll wait for the test to merge this 👍

**Comment by dwc0011** [comment]
> Really appreciate you tackling this @dwc0011 🙇
> 
> I'll wait for the test to merge this 👍

No problem, I own my bugs :)  I am almost done, just doing a couple tests and then will push. Thanks for being patient!

**Review by Nishnha — APPROVED** [review]

**Comment by dwc0011** [comment]
I have added in tests for the display name for registry, provider, and git dependencies.  I will update this test for unknown git dependencies in my other PR #4493 once this is merged.

**Comment by Nishnha** [comment]
Thanks for adding a variety of source types in your `display_name` test! 🥇 
Our CI has been finicky, but once the test suite passes I'll merge this in and take a look at https://github.com/dependabot/dependabot-core/pull/4493

**Comment by dwc0011** [comment]
> Thanks for adding a variety of source types in your `display_name` test! 🥇 Our CI has been finicky, but once the test suite passes I'll merge this in and take a look at #4493

Awesome, once merged I will update the test with the unknown naming convention from #4493.  Thanks again!

**Pull request merged**
