### PR TITLE
Improve memory limit handling in PHP helper

### PR DESCRIPTION
**Pull request by alcaeus**
This commit changes the memory_limit logic used when resolving composer dependencies. Previously, the limit of 1900 MB was always set, even if the limit configured in php.ini was higher. With the change applied, we always respect an infinite memory limit (denoted by memory_limit=-1) as well as a limit higher than what is configured here. The COMPOSER_MEMORY_LIMIT env setting will always override any previously configured values.

The reason for the change is that the PHP helper is run with `memory_limit=-1` (see [`version_resolver.rb`](https://github.com/dependabot/dependabot-core/blob/61e79897c8c79ef0fb2e2c3c23ca8050fcf02754/lib/dependabot/update_checkers/php/composer/version_resolver.rb#L61)), but this limit is immediately overwritten by the 1900M setting in `run.php`.

// cc @ruudk

### CODE REVIEW

**Comment by greysteil** [comment]
Thanks! @hmarr - is there an easy way to get PRs from a fork to build propertly?

**Comment by alcaeus** [comment]
You're very welcome. Do you have an idea when this will be deployed on dependabot.com?

**Comment by greysteil** [comment]
Next few hours. I'm working on a separate PHP issue and want to have that fixed before cutting a new release.

**Comment by alcaeus** [comment]
Awesome, thank you very much! Here's to hoping that this will fix the updates which are not coming in.

**Comment by hmarr** [comment]
I'm working on getting CI builds passing on forks - shouldn't take too long.

**Comment by hmarr** [comment]
#889 _should_ have fixed the build. @alcaeus would you mind rebasing the PR to see if you can get a green build?

**Comment by alcaeus** [comment]
Unfortunately I've already deleted the branch, which means that travis-ci won't pick up on it. I'll open another PR shortly to fix the issue outlined in 
https://github.com/dependabot/dependabot-core/pull/868#issuecomment-451957698.

**Pull request merged**
