### PR TITLE
Docker Registry Upgrade

### PR DESCRIPTION
**Pull request by lewis-strong**
### What are you trying to accomplish?

Fix for pagination on quay.io as this is currently not working 

#10347

https://github.com/deitch/docker_registry2/releases/tag/v1.18.2

Fix introduced at 1.18.2 as per above tag

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by lewis-strong** [comment]
@yeikel - Are you able to review this PR please?

**Comment by targylyen** [comment]
@lewis-strong I can't wait to see that being merged and released.  😄

**Comment by thomas-riccardi** [comment]
does anyone knows how to get a dependabot maintainer to review PRs? 
cc @dependabot/maintainers (does this work?)

**Review by JamieMagee — APPROVED** [review]

**Comment by lewis-strong** [comment]
@JamieMagee - I've rebased a number of times to keep the PR up to date, on the latest rebase though there's a check which appears to be hung and I can't cancel or rerun.

Is this something you can help with?

**Comment by lewis-strong** [comment]
> @JamieMagee - I've rebased a number of times to keep the PR up to date, on the latest rebase though there's a check which appears to be hung and I can't cancel or rerun.
> 
> Is this something you can help with?

Rebased again and all checks passing again.

Can we get this merged? @JamieMagee

**Comment by JamieMagee** [comment]
@lewis-strong Unfortunately, I don't have merge permissions in this repo. Let me see if I can get someone to merge.

**Review by thavaahariharangit — APPROVED** [review]

**Comment by lewis-strong** [comment]
Thanks All! 🥳

**Comment by targylyen** [comment]
Thank you guys!

**Comment by JamieMagee** [comment]
@lewis-strong this is causing errors. Might need to roll this back.

```
TypeError: no implicit conversion of nil into Array
  from dependabot-updater/vendor/ruby/3.3.0/gems/docker_registry2-1.18.2/lib/registry/registry.rb:101:in `+'
  from dependabot-updater/vendor/ruby/3.3.0/gems/docker_registry2-1.18.2/lib/registry/registry.rb:101:in `tags'
  from docker/lib/dependabot/docker/update_checker.rb:198:in `tags_from_registry'
```

**Comment by DashaBochkar** [comment]
Thanks

**Comment by lewis-strong** [comment]
> @lewis-strong this is causing errors. Might need to roll this back.
> 
> ```
> TypeError: no implicit conversion of nil into Array
>   from dependabot-updater/vendor/ruby/3.3.0/gems/docker_registry2-1.18.2/lib/registry/registry.rb:101:in `+'
>   from dependabot-updater/vendor/ruby/3.3.0/gems/docker_registry2-1.18.2/lib/registry/registry.rb:101:in `tags'
>   from docker/lib/dependabot/docker/update_checker.rb:198:in `tags_from_registry'
> ```

@JamieMagee was this an unrelated issue which has now been fixed? I can see Quay pagination is now working in dependabot and it's prompted me with an update this morning?

**Pull request merged**
