### PR TITLE
[WIP] Fetch Terragrunt files in terraform file fetcher

### PR DESCRIPTION
**Pull request by greysteil**
As suggested in #654.

### CODE REVIEW

**Comment by lorengordon** [comment]
Very nice! Thank you!

**Comment by greysteil** [comment]
OK, this should be working now. I'll cut a release and deploy, but it's late here in the UK, so I won't be able to fully watch it out. If you run into any issues let me know and I'll pick them up in the morning.

(Tests will probably fail due to the ongoing npm issues.)

**Comment by greysteil** [comment]
Deploying now - should be live in 10 minutes.

**Comment by lorengordon** [comment]
Nice, thanks @greysteil! I was able to add a dependabot config for the root of that wrangler-watchmaker repo I linked in the issue, but adding another config for the subdirectory `release/salt-yum-defs` fails. Get an error saying the repo must contain a terraform configuration file.

https://github.com/plus3it/wrangler-watchmaker/blob/master/release/salt-yum-defs

**Comment by greysteil** [comment]
Ah, that makes sense - I'd deployed the update to our updater, but not to the backend responsible for doing that check. Should be fixed now.

**Comment by lorengordon** [comment]
Alright, c working now, thanks again!

**Pull request merged**
