### PR TITLE
build(deps): bump terraform from 1.8.0 to 1.9.0

### PR DESCRIPTION
**Pull request by HorizonNet**
https://github.com/hashicorp/terraform/releases/tag/v1.9.0
https://releases.hashicorp.com/terraform/1.9.0/

### CODE REVIEW

**Comment by GarryHurleyJr** [comment]
@dependabot rebase

**Comment by GarryHurleyJr** [comment]
.dependabot rebase

**Comment by HorizonNet** [comment]
Updated the PR to the latest Terraform minor version.

**Review by jeffwidman — APPROVED** [review]
Thanks! Let's get you unblocked here.

**Comment by jeffwidman** [comment]
This is deployed now.

**Comment by robertalexa** [comment]
Hey guys, does this mean Dependabot supports Terraform 1.9.x? If so, does that mean the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) is wrong?

image

Thanks in advance

**Comment by HorizonNet** [comment]
> documentation

@robertalexa Yes, the documentation is wrong. Depending on how you're declaring the required Terraform version Dependabot is working fine. If you're pinning to the exact version it works up to 1.9.1. If you pin the minor version it works until the latest version (currently 1.9.5).

**Comment by robertalexa** [comment]
Hey @HorizonNet thanks for the clarification!

I guess i should do a PR on the docs in that case. Thoughts?

**Comment by HorizonNet** [comment]
@robertalexa SGTM

**Pull request merged**
