### PR TITLE
[Composer] Enhancement: Copy composer.phar from official Docker image

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] copies `composer.phar` from the official Docker image for `composer`

💁‍♂ For reference, see https://github.com/composer/docker.

### CODE REVIEW

**Comment by greysteil** [comment]
Makes sense to me. @hmarr look good to you?

**Comment by hmarr** [comment]
What's the benefit? Is the idea that the composer Docker image is sometimes cached, so we won't need to do the download when we re-build?

My concern is that much of the time (e.g. in CI) the image won't be in the cache, so we'll actually need to download more (the whole Docker image rather than just the individual file), which could slow things down a bit.

**Comment by localheinz** [comment]
@hmarr 

No problem!

Just felt that - since we're installing `composer` in the context of Docker - copying from the official Docker image would make more sense than downloading it via `curl`.

**Comment by hmarr** [comment]
Thanks so much for all your contributions! 😊

**Comment by localheinz** [comment]
@hmarr 

You are much welcome! I hope it helps. 

Thanks to you and GitHub for making Dependabot available for us!

❤️

**Pull request closed without merging**
