### PR TITLE
Upgrade httparty to 0.22.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What are you trying to accomplish?

Running tests with less clobbered output.

### Anything you want to highlight for special attention from reviewers?

I generated this PR by running

```
$ bundle lock --update httparty
$ BUNDLE_GEMFILE=updater/Gemfile bundle lock --update  httparty
```

### How will you know you've accomplished your goal?

Running tests and not seeing the warning anymore.

### Checklist

- [ ] I have run the complete test suite to ensure all tests and linters pass.
- [ ] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [ ] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by JamieMagee** [comment]
Related #9770

**Comment by deivid-rodriguez** [comment]
Ouch, didn't notice there was a PR for this already. Should I close this? It's a duplicate and the other PR came first.

**Comment by abdulapopoola** [comment]
Thanks @deivid-rodriguez and @JamieMagee , I can try to get the [9970 PR in](https://github.com/dependabot/dependabot-core/pull/9770)

**Comment by abdulapopoola** [comment]
[Merged this PR](https://github.com/dependabot/dependabot-core/pull/9770)

**Comment by deivid-rodriguez** [comment]
Thanks both!

**Pull request closed without merging**
