### PR TITLE
[Composer] Enhancement: Clean up UpdateChecker

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] cleans up `UpdateChecker`

💁‍♂ Let me know if you'd prefer me to squash the commits - I've tried to make small, reviewable changes for ease of review.

### CODE REVIEW

**Comment by localheinz** [comment]
Let's wait with this one until #1332 has been sorted out.

**Comment by localheinz** [comment]
Rebased after merge of #1332.

**Comment by localheinz** [comment]
@greysteil 

Please let me know if you'd prefer me to squash the commits after review and before merge!

**Comment by localheinz** [comment]
Thank you, @greysteil!

**Comment by greysteil** [comment]
Thanks @localheinz !

**Pull request merged**
