### PR TITLE
Remove links to reduce timeline noise

### PR DESCRIPTION
**Pull request by landongrindheim**
### 🖼️ Context

In an attempt to reduce noise in timelines, I'm removing links to PRs opened by Dependabot. I've opted to leave non-bot contributors for now.

I also inserted a zero-width space between `@` and `handle` in the release notes so as to limit notification noise. If this is unwelcome, please let me know 🙂 

Closes https://github.com/dependabot/dependabot-core/issues/5639

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@landongrindheim Not sure if this is helpful, but this is the original report with links with the fix that was implemented at the time: https://github.com/dependabot/dependabot-core/issues/3276.

**Comment by deivid-rodriguez** [comment]
It seems that we have regressed somewhere but I have no idea where or how. This PR seems like a workaround for now to stop the bleeding? I mean we always showed links, and GitHub didn't create cross references until now. With this solution, we would lose the links?

**Comment by landongrindheim** [comment]
Thanks @deivid-rodriguez! I misread this report. Looking closer, it appears that we started spamming yesterday (Sept 5th):
image

That should help track this down.

**Comment by jeffwidman** [comment]
Could this be at all related to internal work on the monolith or api back end? I know some of the team was recently touching code around PR generation there... perhaps a side effect?

**Comment by bakkot** [comment]
> Looking closer, it appears that we started spamming yesterday (Sept 5th):

If you're referring to https://github.com/tc39/ecma262/pull/2819, it's not that something in Dependabot changed at that time; rather, that's when [the babel release which mentioned said PR went out](https://github.com/babel/babel/releases/tag/v7.19.0).

**Pull request closed without merging**
