### PR TITLE
Check Azure PR description against utf-16 encoded length

### PR DESCRIPTION
**Pull request by jurre**
Azure Devops uses a character limit of 4000 characters in UTF-16
encoding, instead of Ruby's default UTF-8 encoding. This causes issues
with special characters like Emoji, which count as 2 characters in
UTF-8, but as 4 characters in UTF-16.

### CODE REVIEW

**Comment by aldodfm** [comment]
thx @jurre , let's seee, when this will be merged, i will test with the last Dependabot core docker image verison. ;), just tell me when.

**Comment by aldodfm** [comment]
:'(

**Comment by aldodfm** [comment]
seems that now is ready for merge? =)

**Review by feelepxyz — APPROVED** [review]
👌

**Pull request merged**
