### PR TITLE
always recurse submodules when cloning

### LINKED ISSUE #7201: Dependabot fails when including a git submodule Gradle project using Gradle includeBuild feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

Gradle 7.6

### Language version

Kotlin 1.8.20

### Manifest location and content before the Dependabot update

/build.gradle.kts
/settings.gradle.kts

/somemodule1/build.gradle.kts
/somemodule2/build.gradle.kts
/subproject/build.gradle.kts
/subproject/settings.gradle.kts

> This is the git submodule folder pointing to a different GitHub repository, which should be ignored by Dependabot:

/CommonLibraries

> (in the submodule):

/CommonLibraries/commonGradleConfiguration/build.gradle.kts

and some more files

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
    open-pull-requests-limit: 50
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Error provided by GitHub:

```
Dependabot couldn't find a build.gradle.

Dependabot requires a build.gradle to evaluate your Java dependencies. It had expected to find one at the path: /CommonLibraries/commonGradleConfiguration/build.gradle.

If this isn't a Java project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.
```

It seems Dependabot cannot read git submodules. The CommonLibraries folder is a git submodule pointing to another  (private) GitHub repository. That repository contains another (standalone) Gradle project, which has its own Dependabot configuration in that repository.

I think Dependabot should just ignore the gradle files in that submodule, as it can't even update them even if it could read them. The reason Dependabot is looking for gradle files in that directory is probably because the CommonLibraries project is included using the Gradle `includeBuild` feature. Is there a way to exclude this from Dependabot? Currently I cannot get it working due to this issue.

The file `/subproject/settings.gradle.kts` contains the following which references the git submodule:
includeBuild("../CommonLibraries/commonGradleConfiguration")

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

Private repository

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #7916: path_dependencies_not_reachable error for git submodule
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

`/package.json`

Applicable lines in `package.json`:

```
"devDependencies": {
  ...,
  "@pixiebrix/extension": "file:pixiebrix-extension",
  ...
}
```

Note `@pixiebrix/extension` points to a submodule. Here is our `/.gitmodules` file:

```
[submodule "pixiebrix-extension"]
	path = pixiebrix-extension
	url = https://github.com/pixiebrix/pixiebrix-extension.git
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    assignees:
      - johnnymetz
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

**Expected**

`@pixiebrix/extension` is a submodule so npm dependabot should not touch it. I even tried ignoring it by appending `ignore` to the dependabot config:

```
updates:
  - package-ecosystem: npm
    ...
    ignore:
      - dependency-name: "@pixiebrix/extension"
```

**Actual**

Screenshot 2023-08-28 at 11 35 05 AM

Dependabot logs:

```
updater | 2023/08/28 18:41:23 ERROR <job_714829645> Error during file fetching; aborting
updater | 2023/08/28 18:41:23 INFO <job_714829645> Finished job processing
updater | 2023/08/28 18:41:23 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------------+
updater | |             Errors              |
updater | +---------------------------------+
updater | | path_dependencies_not_reachable |
updater | +---------------------------------+
updater | time="2023-08-28T18:41:23Z" level=info msg="task complete" container_id=job-714829645-file-fetcher exit_code=0 job_id=714829645 step=fetcher
updater | time="2023-08-28T18:41:23Z" level=warning msg="failed during fetch, skipping updater" job_id=714829645
```

### Native package manager behavior

`npm install` works fine locally. No errors.

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #8428: Dependabot couldn't fetch all your path-based dependencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

_No response_

### Language version

Python

### Manifest location and content before the Dependabot update

https://github.com/HangJung97/test_dependabot/blob/main/pyproject.toml

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "pytorch-lightning"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "torchmetrics"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

I have a git submodule named ASCENT located at the root. I have included it as a package in my `pyproject.toml` like this `ascent = { path = "./ASCENT/", develop = true }`. I expected dependabot to be able to find the `pyproject.toml` in my ASCENT submodule since my path is relative and correct but got this error instead `Dependabot couldn't fetch all your path-based dependencies`. The exact error looks like this:

updater | 2023/11/17 18:56:10 ERROR <job_751387553> Error during file fetching; aborting: The following path based dependencies could not be retrieved: ASCENT/pyproject.toml.

The public repository I created to debug this problem can be found [here](https://github.com/HangJung97/test_dependabot).

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #9193: Dependabot not pulling submodules before maven pom.xml since February 1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

https://github.com/onthegomap/planetiler/blob/main/pom.xml

### dependabot.yml content

https://github.com/onthegomap/planetiler/blob/40e64a2fd303900989fa133fcec4d9c8daa33e81/.github/dependabot.yml#L6-L17

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Expected: dependabot opens new PRs when dependencies are updated.
Actual: No PRs have been opened since [January 31](https://github.com/onthegomap/planetiler/pull/811), and on https://github.com/onthegomap/planetiler/network/updates I see errors:

image

and an example update log https://github.com/onthegomap/planetiler/network/updates/794518193 is:

```
  proxy | 2024/03/01 10:05:30 proxy starting, commit: b46ea0704f16a9103c1637eea8708f9cf4f39684
  proxy | 2024/03/01 10:05:30 Listening (:1080)
updater | 2024-03-01T10:12:00.003183228 [794518193:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-03-01T10:12:03Z" level=info msg="guest starting" commit=684e575d82404ac8cfafa9000ff20dbc9dddb4f6
updater | time="2024-03-01T10:12:03Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=794518193 updater_timeout=45m0s updater_version=a8d33f7bd41710faa9653b1416b61eb2fece30b0-maven
updater | 2024/03/01 10:12:13 INFO <job_794518193> Starting job processing
updater | 2024/03/01 10:12:13 INFO <job_794518193> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[[{"dependency-name":"org.slf4j:slf4j-api","dependency-version":"2.0.0"}],[{"dependency-name":"org.slf4j:slf4j-api","dependency-version":"2.0.2"}],[{"dependency-name":"org.apache.logging.log4j:log4j-api","dependency-version":"2.16.0"},{"dependency-name":"org.apache.logging.log4j:log4j-core","dependency-version":"2.16.0"},{"dependency-name":"org.apache.logging.log4j:log4j-slf4j-impl","dependency-version":"2.16.0"}],[{"dependency-name":"org.apache.logging.log4j:log4j-api","dependency-version":"2.19.0"},{"dependency-name":"org.apache.logging.log4j:log4j-core","dependency-version":"2.19.0"},{"dependency-name":"org.apache.logging.log4j:log4j-slf4j-impl","dependency-version":"2.19.0"}]],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[{"dependency-name":"com.google.protobuf:protobuf-java","source":".github/dependabot.yml","update-types":null,"updated-at":"2023-06-23T09:53:49.000Z","version-requirement":"3.23.3"}],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"maven","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/.","hostname":"github.com","provider":"github","repo":"onthegomap/planetiler"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/03/01 10:12:13 [002] GET https://github.com:443/onthegomap/planetiler/info/refs?service=git-upload-pack
  proxy | 2024/03/01 10:12:13 [002] * authenticating git server request (host: github.com)
  proxy | 2024/03/01 10:12:13 [002] 200 https://github.com:443/onthegomap/planetiler/info/refs?service=git-upload-pack
  proxy | 2024/03/01 10:12:13 [004] POST https://github.com:443/onthegomap/planetiler/git-upload-pack
  proxy | 2024/03/01 10:12:13 [004] * authenticating git server request (host: github.com)
  proxy | 2024/03/01 10:12:13 [004] 200 https://github.com:443/onthegomap/planetiler/git-upload-pack
  proxy | 2024/03/01 10:12:13 [006] POST https://github.com:443/onthegomap/planetiler/git-upload-pack
  proxy | 2024/03/01 10:12:13 [006] * authenticating git server request (host: github.com)
  proxy | 2024/03/01 10:12:14 [006] 200 https://github.com:443/onthegomap/planetiler/git-upload-pack
updater | 2024/03/01 10:12:19 ERROR <job_794518193> Error during file fetching; aborting: /planetiler-openmaptiles/submodule.pom.xml not found
updater | 2024/03/01 10:12:19 INFO <job_794518193> Finished job processing
updater | 2024/03/01 10:12:19 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-03-01T10:12:19Z" level=info msg="task complete" container_id=job-794518193-file-fetcher exit_code=0 job_id=794518193 step=fetcher
updater | time="2024-03-01T10:12:20Z" level=warning msg="failed during fetch, skipping updater" job_id=794518193
```

submodule.pom.xml is a file that should show up in the repo after pulling submodule dependencies.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #9198: Dependabot Gradle version update fails with "dependency_file_not_found" for files in git submodule
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

Main entrypoint:

```
build.gradle
```

Referenced via:  `apply from: 'build-system/dependencies-spring.gradle'` in `build.gradle` above.

```
build-system/dependencies-spring.gradle
``` 

Note: `build-system` is a Git submodule.

### dependabot.yml content

```yaml
version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/our-org/*
    username: "our-user"
    password: ${{ secrets.GITHUB_PACKAGES_READ_TOKEN }}
updates:
  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - github-packages
    schedule:
      interval: "daily"
    # Limit number of open PRs
    open-pull-requests-limit: 10
  # Enable version updates for submodules (build-system)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

As noted above, `build-system` is a Git submodule (which is updated via Dependabot too, and it works fine). However, when running the Gradle update check, it seems Dependabot can't find the files in the submodule. My guess it that it isn't fetched at all... 

The above `dependabot.yaml` used to work fine (last PR was merged on January 26. 2024), but now Dependabot complains: "Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found". I guess this is some sort of regression or change in functionality. 

It would be nice if dependabot could fetch submodules for version checks again, or add an option to enable it. 

(The reason we need this to work, is that we have collections of libraries in the submodule, with versions as variables, these variables are defined in the top level `build.gradle`). 

Here's a part of the log for the failing update (full contents in logs below): 

```
updater | 2024/03/04 12:27:27 ERROR <job_795506033> Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found
updater | 2024/03/04 12:27:28 INFO <job_795506033> Finished job processing
updater | 2024/03/04 12:27:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-03-04T12:27:28Z" level=info msg="task complete" container_id=job-795506033-file-fetcher exit_code=0 job_id=795506033 step=fetcher
updater | time="2024-03-04T12:27:28Z" level=warning msg="failed during fetch, skipping updater" job_id=795506033
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

```
 proxy | 2024/03/04 12:27:16 proxy starting, commit: b46ea0704f16a9103c1637eea8708f9cf4f39684
  proxy | 2024/03/04 12:27:16 Listening (:1080)
updater | 2024-03-04T12:27:18.134492116 [795506033:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-03-04T12:27:20Z" level=info msg="guest starting" commit=684e575d82404ac8cfafa9000ff20dbc9dddb4f6
updater | time="2024-03-04T12:27:20Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=795506033 updater_timeout=45m0s updater_version=29b0328d79f188adc8338958a16d6301018acf30-gradle
updater | 2024/03/04 12:27:26 INFO <job_795506033> Starting job processing
updater | 2024/03/04 12:27:26 INFO <job_795506033> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"type":"maven_repository","url":"https://maven.pkg.github.com/nrkno/*"},{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"gradle","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":true,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/.","hostname":"github.com","provider":"github","repo":"nrkno/mdb-authority-client"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/03/04 12:27:27 [002] GET https://github.com:443/nrkno/mdb-authority-client/info/refs?service=git-upload-pack
  proxy | 2024/03/04 12:27:27 [002] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [002] 200 https://github.com:443/nrkno/mdb-authority-client/info/refs?service=git-upload-pack
  proxy | 2024/03/04 12:27:27 [004] POST https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [004] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [004] 200 https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [006] POST https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [006] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [006] 200 https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
updater | 2024/03/04 12:27:27 ERROR <job_795506033> Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found
updater | 2024/03/04 12:27:28 INFO <job_795506033> Finished job processing
updater | 2024/03/04 12:27:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-03-04T12:27:28Z" level=info msg="task complete" container_id=job-795506033-file-fetcher exit_code=0 job_id=795506033 step=fetcher
updater | time="2024-03-04T12:27:28Z" level=warning msg="failed during fetch, skipping updater" job_id=795506033
```

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by jakecoffman**
In https://github.com/dependabot/dependabot-core/pull/8933 we made all ecosystems clone rather than fetching single files. 

Similarly this PR enables recurse submodules for all ecosystems to fix some path dependency issues. The only downside would be an increase in out of disk errors but we can onboard to Actions beta now which increases the amount of disk available.

Fixes #8428
Fixes #9198
Fixes #7201
Fixes #9193
Fixes #7916

Supersedes:
- #7078
- #9181
- #8807

### CODE REVIEW

**Comment by abdulapopoola** [comment]
Thanks for this! I assume it'll fix this [too](https://github.com/dependabot/dependabot-core/pull/7078)?

**Comment by jakecoffman** [comment]
Yes I think so, the problem then was we weren't cloning for Gradle yet. Now that we're cloning and fetching submodules it should be fixed without additional changes 🤞

**Comment by abdulapopoola** [comment]
Awesome, can you please link it? I tried but wasn't successful :)

**Comment by jakecoffman** [comment]
Since it's a PR it can't be linked like issues can, I'll close it out an reference this PR once it's merged.

**Review by abdulapopoola — APPROVED** [review]

**Review by jurre — APPROVED** [review]

**Pull request merged**
