### PR TITLE
build(deps): bump go from 1.20.7 to 1.21.0

### PR DESCRIPTION
**Pull request by julienschmidt**
> go1.21.0 (released 2023-08-08)
Go 1.21.0 is a major release of Go. Read the [Go 1.21 Release Notes](https://go.dev/doc/go1.21) for more information.

Go 1.21 contains new stdlib packages `maps` and `slices`, meaning that dependabot updates on projects that already use them currently fail.

### CODE REVIEW

**Comment by julienschmidt** [comment]
I'm not sure if fully understand the error message. Which file(s) would have to be adjusted? (feel free to simply push to this branch)

**Comment by jeffwidman** [comment]
I'm 👍 on this PR, as well as the idea of requiring versions to be specified in `go.mod` files.

However, that probably means we first need to add error handling that translates the error thrown by native `go` tooling when a version is `unknown` / unspecified and bubbles it up to the user with a clear error message. Otherwise it will be seen as an unknown error, so users won't know the real problem... plus within the GitHub internal service it could hurt whether we're achieving our SLO's.

I don't anticipate that PR being very difficult, but I'd probably prefer we land that first before landing this. If you don't have time/knowledge on how to to this, then it's probably something one of the maintainers can pickup in the not too distant future.

**Comment by julienschmidt** [comment]
I'm afraid I won't have the time to implement it.
Fell free to close this PR if it isn't useful

**Comment by jakecoffman** [comment]
My apologies, I think I misidentified what the issue is here. It looks like Go 1.21 now allows a patch version on the go directive, and adds it by default. That means our `go_mod_updater` needs to be updated, but otherwise nothing is changing. 

I pushed a fix here #7823

**Comment by jakecoffman** [comment]
This should be fixed now by #7823.

**Pull request closed without merging**
