### PR TITLE
build(deps): bump pNPM to 8.15.2

### PR DESCRIPTION
**Pull request by yeikel**
Release notes : 

https://github.com/pnpm/pnpm/releases/tag/v8.15.0
https://github.com/pnpm/pnpm/releases/tag/v8.15.1
https://github.com/pnpm/pnpm/releases/tag/v8.15.2

Small incremental upgrade with only a few changes :) 

Note to reviewers: Please squash this :)

### CODE REVIEW

**Comment by yeikel** [comment]
cc @abdulapopoola

**Review by jurre — APPROVED** [review]

**Comment by yeikel** [comment]
@abdulapopoola Can you help move this forward?

**Comment by yeikel** [comment]
@jurre Can you help me procure another review? I am not sure who to tag

**Review by jurre — APPROVED** [review]

**Comment by jurre** [comment]
Thanks @yeikel! Feel free to tag me, I will try to get this landed today

**Pull request merged**
