### PR TITLE
Move common code into its own package

### PR DESCRIPTION
**Pull request by hmarr**
This removes the `lib` and `spec` folders at the top level - all package managers now depend on `dependabot-common`.

### CODE REVIEW

**Comment by RohanNagar** [comment]
FYI looks like you missed one - https://github.com/dependabot/dependabot-core/blob/master/spec/fixtures/github/ref_my_branch_many.json

😄

**Comment by hmarr** [comment]
That got lost during a rebase, but I re-added it here 9a15f4b5f87537699762f0968b8cac888bafb13c :-)

**Comment by RohanNagar** [comment]
I meant that it's in two places now - in the top level `spec/fixtures/github` and also in `common/spec/fixtures/github`

**Comment by hmarr** [comment]
Ah, I see, it's still also in its original location too 🙈  Thanks!

**Comment by hmarr** [comment]
Fixed in 8f2182382bcf5ace87bad2fdfc87c47ffc71bd9d

**Pull request merged**
