### PR TITLE
Include crucial new dependabot emoji

### PR DESCRIPTION
**Pull request by jurre**
:dependabot:

### CODE REVIEW

**Comment by ldeluigi** [comment]
Could this emoji be used in PRs too?

**Review by deivid-rodriguez — APPROVED** [review]
Approving this hotfix 👍

**Comment by jurre** [comment]
> Could this emoji be used in PRs too?

Where would you like to see it?

**Comment by ldeluigi** [comment]
> > Could this emoji be used in PRs too?
> 
> Where would you like to see it?

Maybe here or here or here....?
image

**Comment by jeffwidman** [comment]
I'm not opposed to tweaking the PR title/description, but we'd probably still want to ensure the literal word "dependabot" shows up in the description to ensure it remains easily grep'able.

**Comment by jeffwidman** [comment]
Also 🎩 💁‍♂️  to @landongrindheim for adding :dependabot:!

**Pull request merged**
