### PR TITLE
Try to find pnpm-lock.yaml file upwards on tree structure

### PR DESCRIPTION
**Pull request by Yurickh**
### What are you trying to accomplish?

Iterate the folder tree upwards in order to find a pnpm-lock file when the directory source points to a nested workspace.

This hopefully addresses https://github.com/dependabot/dependabot-core/issues/10758, but I'd like to be able to verify these changes against my own repository. Is there any way to point dependabot to a fork in GitHub? I couldn't find any docs on it.

### Anything you want to highlight for special attention from reviewers?

I'm not familiar with ruby project standards, so please let me know if you'd rather structure tests or code in a different way. I tried following the existing standards, but might have missed something.

### How will you know you've accomplished your goal?

- The test I've added was failing prior to the changes in code, which I hope is enough to reproduce the issue described in #10758.
- I'd like to test these changes against my own repository, but couldn't find a way to point dependabot to a fork.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by sylver** [comment]
Having this specific issue with our repos and was surprised to discover this is not actually covered while pnpm is supported.

Would be great to have some maintainers attention, since this is mandatory for any monorepo out there and the PR is quite simple and straightforward

**Comment by abdulapopoola** [comment]
Thanks @Yurickh , @thavaahariharangit will be investigating in this area this week.

**Comment by thavaahariharangit** [comment]
How do you ensure this solution works? , Is there are any example repository test it? , I mean I could recreate the error, and check that changes that you have provided fixing the issue please. 

Based on the [analysis on the ticket](https://github.com/github/dependabot-updates/issues/7169). If it is yarn monorepo, dependabot is failing. But I could not test that on the repo they provided  because there are lot of dependency using the private registry. Could you please let me know your thoughts on this.

**Comment by Yurickh** [comment]
That's my question in the PR description exactly :)~ 
Is there a way to run dependabot against a fork? I'd gladly setup a reproduction repo if I knew how to, but I couldn't find any docs on it.

**Comment by Yurickh** [comment]
So far, I've ensured the fix works by adding a test that breaks on your main, and passes on my branch, but if that's not enough, please I'd be glad to help verify it in any manner you see fit.

**Comment by thavaahariharangit** [comment]
Give me sometime, I will recreate this problem on sample or general repo, and verify both pls
1. Does that gives the same error customer is facing
2. Fix that you given here, fixing that issue.

**Review by thavaahariharangit — APPROVED** [review]

**Comment by thavaahariharangit** [comment]
@Yurickh 

I did some more reading on this issue. As per the documentation. 
pnpm-lock.yaml should be on the root folder. If that's the case then this changes need not to be there.

FYR: https://github.com/dependabot/dependabot-core/issues/6346#issuecomment-2506331054

**Comment by Yurickh** [comment]
Yes, you're right there's only a single `pnpm-lock.yaml` file, but it is not necessarily at the same directory as the `updates.directory` configuration in dependabot.
In our case, we specifically want a single PR per workspace package, so we separate the configuration in different `updates` groups, but then the lockfile is not updated correctly.
This change ensures that we can find the root even when `updates.directory` is not the root by itself.

**Comment by thavaahariharangit** [comment]
> Yes, you're right there's only a single `pnpm-lock.yaml` file, but it is not necessarily at the same directory as the `updates.directory` configuration in dependabot. In our case, we specifically want a single PR per workspace package, so we separate the configuration in different `updates` groups, but then the lockfile is not updated correctly. This change ensures that we can find the root even when `updates.directory` is not the root by itself.

Thank you for this update, Trying recreate this problem based on your comment. Give me sometime pls :)

**Comment by MattIPv4** [comment]
If it helps for reproducing, I just ran into this bug/failure mode in the wild: https://github.com/alveusgg/alveusgg/pull/850

**Comment by thavaahariharangit** [comment]
@Yurickh and @MattIPv4 

I have created [a sample repo recreate this problem](https://github.com/dsp-testing/pnpm-monorepo-sample)

Note: 
In above repo I have used below sample data, 
1. root level: `express@4.10.0`
2. project level: `vue@3.2.0`

Without any update to the current dependabot (without this PR changes), I saw below behaviors 

### Scenario 1

When `updates.directory` is 

```
directories:
      - /
      - /packages/*
```

then PR's generated
```
 +---------------------------------------------+
 |     Changes to Dependabot Pull Requests     |
 +---------+-----------------------------------+
 | created | express ( from 4.10.0 to 4.21.1 ) |
 | created | vue ( from 3.2.0 to 3.5.13 )      |
 +---------+-----------------------------------+
```
### Scenario 2

When `updates.directory` is 
```
directories:
      - /
```
then PR's generated
```
 +---------------------------------------------+
 |     Changes to Dependabot Pull Requests     |
 +---------+-----------------------------------+
 | created | express ( from 4.10.0 to 4.21.1 ) |
 +---------+-----------------------------------+
```

### Scenario 3

When `updates.directory` is 
```
directories:
      - /packages/*
```
then PR's generated
```
 +----------------------------------------+
 |  Changes to Dependabot Pull Requests   |
 +---------+------------------------------+
 | created | vue ( from 3.2.0 to 3.5.13 ) |
 +---------+------------------------------+
```

As far as I know things are working as per the dependabot documentation.

Could you please help me on recreating the issue that we are planning to fix by this changes.

FYI 
@abdulapopoola and @landongrindheim

**Comment by sylver** [comment]
@thavaahariharangit as stated previously, we have the exact same problem, thus why I ended up here.  
So I can confirm this is a real issue.

To help illustrate, here's (a simplified snippet of) our dependabot.yml:

```
updates:
  - package-ecosystem: npm
    directory: "/apps/portal"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    allow:
      - dependency-name: "@angular*"
      - dependency-name: "typescript"
    ignore:
      - dependency-name: "@angular*"
        versions: [">=18.0.0"]
      - dependency-name: "@angular*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 4
    ignore:
      # Handled by dedicated groups above
      - dependency-name: "@angular*"
```

- the first update is needed for specific versions to lock in the directory `/apps/portal`. Dependabot will update `/apps/portal/package.json` but not `/pnpm-lock.yaml` <= That's the problem
- the second will properly update any `/**/package.json` along with `/pnpm-lock.yaml`, as expected, since we don't filter in a sub-directory/package of the monorepo

Hope that helps.

**Comment by sylver** [comment]
@thavaahariharangit I just had a look at your sample repo. You have a `pnpm-lock.yaml` in the subdirectory `packages/web`, but that's not how it's supposed to work. In a monorepo, everything is handled by one `pnpm-lock.yaml` file at the root level, not within each workspace packages.

**Comment by Yurickh** [comment]
Here's a reproduction repro:
https://github.com/Yurickh/dependabot-core-repro

I've created a very simple pnpm workspaces repository with two packages with old dependencies, and as you can see in the PRs opened:
- https://github.com/Yurickh/dependabot-core-repro/pull/3/files
- https://github.com/Yurickh/dependabot-core-repro/pull/2/files
- https://github.com/Yurickh/dependabot-core-repro/pull/1/files

None of them updates the lock file, as you'd expect.

**Comment by thavaahariharangit** [comment]
> @thavaahariharangit I just had a look at your sample repo. You have a `pnpm-lock.yaml` in the subdirectory `packages/web`, but that's not how it's supposed to work. In a monorepo, everything is handled by one `pnpm-lock.yaml` file at the root level, not within each workspace packages.

Yes you're correct @sylver , But in this specific @Yurickh  case it's different, Please refer https://github.com/dependabot/dependabot-core/pull/10806#issuecomment-2506345133 

I might need to analyze your issue as a different ticket. First I will finish with @Yurickh's issue and get back to you.

**Comment by thavaahariharangit** [comment]
> Here's a reproduction repro: https://github.com/Yurickh/dependabot-core-repro
> 
> I've created a very simple pnpm workspaces repository with two packages with old dependencies, and as you can see in the PRs opened:
> 
> * https://github.com/Yurickh/dependabot-core-repro/pull/3/files
> * https://github.com/Yurickh/dependabot-core-repro/pull/2/files
> * https://github.com/Yurickh/dependabot-core-repro/pull/1/files
> 
> None of them updates the lock file, as you'd expect.

I started analyzing your Issue, and I will get back to you as soon as I found anything.

**Comment by sylver** [comment]
> Yes you're correct @sylver , But in this specific @Yurickh case it's different, Please refer [#10806 (comment)](https://github.com/dependabot/dependabot-core/pull/10806#issuecomment-2506345133)
> 

@thavaahariharangit I could be mistaken, but unless @Yurickh proves me wrong, I'm pretty sure we are talking about the same thing here.

**Comment by Yurickh** [comment]
As far as I can tell @sylver has indeed the same issue this PR is aiming to fix.

**Comment by thavaahariharangit** [comment]
Part of my analysis.

I have ran the cli against [sample repo](/Yurickh/dependabot-core-repro) provided by @Yurickh 

- Root level I don't see any different in PR generation with and without this changes. As expected as it is traversing upwards

- In Package-a level I notice the below different in PR generation with and without this changes

image

- In Package-b level I found an error That's what I took some extra time on this analysis

image

As I have decided analysis this error as part of another ticket. I am approving this, Moving forward and deploying this changes.

**Review by thavaahariharangit — APPROVED** [review]

**Comment by sylver** [comment]
Thanks @thavaahariharangit, that will help a lot 🙏 
Looking forward to the next release so that we can actually benefit from it

**Comment by sylver** [comment]
> > @thavaahariharangit I just had a look at your sample repo. You have a `pnpm-lock.yaml` in the subdirectory `packages/web`, but that's not how it's supposed to work. In a monorepo, everything is handled by one `pnpm-lock.yaml` file at the root level, not within each workspace packages.
> 
> Yes you're correct @sylver , But in this specific @Yurickh case it's different, Please refer [#10806 (comment)](https://github.com/dependabot/dependabot-core/pull/10806#issuecomment-2506345133)
> 
> I might need to analyze your issue as a different ticket. First I will finish with @Yurickh's issue and get back to you.

@thavaahariharangit after new PRs opened by dependabot in our repos, it seems it still does not update the `pnpm-lock.yaml` file from sub-packages rules even with this PR merged, not sure why though.

The issue is still like I described here earlier and like it was shown in @Yurickh monorepo sample example opened PRs:
https://github.com/Yurickh/dependabot-core-repro/pull/3
https://github.com/Yurickh/dependabot-core-repro/pull/2 

@Yurickh could you force dependabot to update/reopen the PRs in your sample monorepo, so that we can assess whether it works or not at least on that one for a follow-up please ?

**Comment by Yurickh** [comment]
Yes, it seems the issue is still not fixed :(

**Comment by thavaahariharangit** [comment]
@sylver or @Yurickh Could you please raise a ticket on this please, I am able to prioritize this on upcoming planning meeting.

**Comment by MattIPv4** [comment]
Hiya, I just wanted to note that this fix does appear to be working, dependant successfully opened PRs in alveusgg/alveusgg finally

**Comment by MattIPv4** [comment]
I think the issue with the repro repo is that it is pointing dependabot to each of the sub-packages individually.

I played around a bunch in alveusgg/alveusgg and found that with this fix in, it all worked perfectly once we just pointed dependabot at the root -- it would discover and update the sub-packages by itself

**Comment by abdulapopoola** [comment]
> I think the issue with the repro repo is that it is pointing dependabot to each of the sub-packages individually.
> 
> I played around a bunch in alveusgg/alveusgg and found that with this fix in, it all worked perfectly once we just pointed dependabot at the root -- it would discover and update the sub-packages by itself

Thanks @MattIPv4 ! @Yurickh could you give this a try?

@thavaahariharangit , can we start a discussion post with this guide too?

**Comment by MattIPv4** [comment]
I'm not sure I follow -- if you point dependabot at just the root, it will handle updating the entire workspace?

**Comment by sylver** [comment]
> I'm not sure I follow -- if you point dependabot at just the root, it will handle updating the entire workspace?

But you have use cases in a monorepo where you need to filter your rules per packages / sub-folders, not at the root level

**Comment by MattIPv4** [comment]
Ah that is true. This fix seems to have solved the issue for it updating the sub-packages when pointed at the root, but not pointed directly at the sub-packages. I guess another issue needs to be filed?

**Comment by vluoto** [comment]
> Ah that is true. This fix seems to have solved the issue for it updating the sub-packages when pointed at the root, but not pointed directly at the sub-packages. I guess another issue needs to be filed?

I filed a new issue for this: #11135

**Pull request merged**
