### PR TITLE
Resolve some Sorbet errors in Terraform

### PR DESCRIPTION
**Pull request by JamieMagee**
I removed the `FileSelector` mixin from `FileFetcher` as the mixin expects `dependency_files` to be defined. Instead, I extracted the 2 methods that are used in `FileFetcher`.

See [the Sorbet documentation][1] for the advice I followed

---

Recreated from #9404 due to losing write permissions in this repository.

[1]: https://sorbet.org/docs/abstract#interfaces-and-the-included-hook

### CODE REVIEW

**Review by brettfo — APPROVED** [review]

**Review by bdragon — APPROVED** [review]

**Review by bdragon — APPROVED** [review]

**Comment by bdragon** [comment]
I'm pretty sure the reason CI won't build branch images for this PR is because it's from a fork:

https://github.com/dependabot/dependabot-core/blob/7b25e935cd0a1f9a89abf6ce865cea69090c298d/.github/workflows/images-branch.yml#L49

**Comment by JamieMagee** [comment]
@bdragon do you need me to recreate the branch in this repo?

**Comment by bdragon** [comment]
@JamieMagee I think so, unfortunately. Sorry for the ping-ponging.

**Comment by JamieMagee** [comment]
@bdragon #9635

**Pull request closed without merging**
