### PR TITLE
[WiP] composer support all extentions

### PR DESCRIPTION
**Pull request by WyriHaximus**
This PR adds support to dependabot for any extention by trial and error. As mentioned here https://github.com/dependabot/dependabot-core/pull/890#issuecomment-504428697 I've made progress on this at @usabilla. But I also have to time box this (, I will continue on my own time once we go out of the time box). Currently I have a clear path of what has to be done but I would love to have early feedback on this. Especially this is the first time I'm doing Ruby beyond capistrano (and the likes) files.

Currently the code contains debug and some hardcoded bits but those show the direction I'm going for. The idea is:

1. We try to resolve the versions to update to and in the mean time detect if we're missing extentions, if we are we add them to `platform` temporarily.
2. We then pass the list of extesions onto the lock file updater and update the lock file
3. Clean up any traces of our platform traces

/cc @greysteil

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Right so I had a successful end of the day. Been running it against one of my projects [`reactive-apps/command-http-server`](https://github.com/reactive-apps/command-http-server) that requires `ext-parallel` which isn't installed on the Dependabot image. This is the output of `bin/docker-dev-shell bin/dry-run.rb composer reactive-apps/command-http-server`:

```
[34m > image dependabot/dependabot-core-development already exists(B[m
[32m=> running docker development shell(B[m
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> fetching dependency files
=> parsing dependency files
=> updating 26 dependencies

=== cakephp/collection (3.7.8)
 => checking for updates
 => requirements to unlock own
 => updating to 3.7.9;ext-parallel

    ± composer.lock
    ~~~
    55c55
    <             "version": "3.7.8",
    ---
    >             "version": "3.7.9",
    728c728
    <             "name": "jeremeamia/SuperClosure",
    ---
    >             "name": "jeremeamia/superclosure",
    3304c3304
    <                     "email": "backendtea@gmail.com"
    ---
    >                     "email": "BackEndTea@gmail.com"
    ~~~

=== doctrine/annotations (1.6.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== nikic/fast-route (1.3.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== react/http (0.8.4)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== roave/better-reflection (3.5.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/doctrine-annotation-autoloader (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/get-in-packages-composer.jason (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/json-psr7 (1.1.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/psr-3-callable-throwable-logger (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/psr-3-context-logger (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-child-process-closure (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-child-process-pool (1.5.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-http-middleware-resume-response-body (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-http-middleware-rewrite (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-http-middleware-runner (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-http-middleware-webroot-preload (1.4.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-http-psr-15-middleware-group (1.4.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/react-stream-json (1.3.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/recoil-promise-coroutine-wrapper (1.0.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/recoil-queue-caller-pool (1.2.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/to-child-process-or-not-to-child-process (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/to-coroutine-or-not-to-coroutine (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== zendframework/zend-diactoros (2.1.2)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== twig/twig (2.11.2)
 => checking for updates
 => requirements to unlock own
 => updating to 2.11.3;ext-parallel

    ± composer.lock
    ~~~
    728c728
    <             "name": "jeremeamia/SuperClosure",
    ---
    >             "name": "jeremeamia/superclosure",
    3304c3304
    <                     "email": "backendtea@gmail.com"
    ---
    >                     "email": "BackEndTea@gmail.com"
    10412c10412
    <             "version": "v2.11.2",
    ---
    >             "version": "v2.11.3",
    10416c10416
    <                 "reference": "84a463403da1c81afbcedda8f0e788c78bd25a79"
    ---
    >                 "reference": "699ed2342557c88789a15402de5eb834dedd6792"
    10420,10421c10420,10421
    <                 "url": "https://api.github.com/repos/twigphp/Twig/zipball/84a463403da1c81afbcedda8f0e788c78bd25a79",
    <                 "reference": "84a463403da1c81afbcedda8f0e788c78bd25a79",
    ---
    >                 "url": "https://api.github.com/repos/twigphp/Twig/zipball/699ed2342557c88789a15402de5eb834dedd6792",
    >                 "reference": "699ed2342557c88789a15402de5eb834dedd6792",
    10475c10475
    <             "time": "2019-06-05T11:17:07+00:00"
    ---
    >             "time": "2019-06-18T15:37:11+00:00"
    ~~~

=== wyrihaximus/async-test-utilities (1.1.0)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)

=== wyrihaximus/cs-fixer-config (1.0.1)
 => checking for updates
 => requirements to unlock update_not_possible
    (no update available)
```

**Comment by WyriHaximus** [comment]
So as you can see it picks up new versions without any errors about missing extensions now. And it also ensures that no trace of the fiddling in the platform config is comitted. I (for sure) took some nasty short cuts, especially getting the extension list from the checker into the lock file updater, and I probably need help fixing those from someone with Ruby knowledge. Next target are tests :tada: .

**Comment by greysteil** [comment]
Haven't had a chance to give this proper attention yet, but will do over the weekend and am *seriously* excited about it.

**Comment by WyriHaximus** [comment]
@greysteil Cool! I should have most of the issues ironed out, but I could use some help with the rest of the failing tests (12 of them). And some of the cheats I used getting the version into the right location. There is one more thing I need to do and that is get the guessed version into the lock file updater, once that is done I'll squash the commits and this is ready for your review

**Comment by WyriHaximus** [comment]
@greysteil Ok I've added the last thing that was missing feature wise. Also squashed everything into one commit. The original history can be found in this branch for those that are interested: https://github.com/WyriHaximus-labs/dependabot-core/tree/composer-support-any-extension_history

There are a bunch of tests failing regarding `Gem::Version` and I have no idea how to deal with those.

There is one final situation I haven't covered yet and that's when a now major version of a package is released and `composer.json` will be updated. There shouldn't be any traces of the platform modifications in there but I haven't verified that yet.

There is a final gotcha that might come back to bite us in the ass and that's extension requirements that have been defined as `~1.2|~3.4`. Those would be transformed to `1.23.4` and that's fine. The gotcha is when another package in the tree requires `~3.4` and not `~1.2`.

**Comment by greysteil** [comment]
OK, I like the looks of this approach. I've cleaned up the Ruby code, which it looks like is where almost all of this is going to need to live, so it *should* all be working now.

I still think an implementation in Composer would be preferable, because the "find a version we can use that satisfies all the requirements" logic is a pain, but in the meantime I think you're onto something here. 🤞

**Comment by greysteil** [comment]
I also went for just duplicating the logic between the `VersionResolver` and the `LockfileUpdater`, rather than try to pass extension details across in the dependency's version. I think it's fine to have that duplication, as the first pass (to determine the required extensions) appears to blow up very quickly.

**Comment by WyriHaximus** [comment]
> OK, I like the looks of this approach. I've cleaned up the Ruby code, which it looks like is where almost all of this is going to need to live, so it _should_ all be working now.
> 

:tada: 

> I still think an implementation in Composer would be preferable, because the "find a version we can use that satisfies all the requirements" logic is a pain, but in the meantime I think you're onto something here.

Agreed and make sure to check the dry-run output for traces of the platform changes. If you can solve that in ruby it would be even more awesome, but I solved that in PHP by cloning the config and reapply the original one before only updating the lock file.

> I also went for just duplicating the logic between the `VersionResolver` and the `LockfileUpdater`, rather than try to pass extension details across in the dependency's version. I think it's fine to have that duplication, as the first pass (to determine the required extensions) appears to blow up very quickly.

Be ware that passing the information on is faster because you don't have to run those checks a second time.

**Comment by greysteil** [comment]
Good shout - should be taken care of in the last commit.

**Comment by greysteil** [comment]
One final requirement to get this merged: can you sign the attached and email it to me on support@dependabot.com? Apologies for the hassle - we're planning to change the license on Dependabot Core (to something better drafted with the same intent, or to MIT) and need to ensure we have ownership of the IP to do so.

[Cees-Jan Kiewiet.pdf](https://github.com/dependabot/dependabot-core/files/3343288/Cees-Jan.Kiewiet.pdf)

Thanks masses for your work on this!

**Comment by WyriHaximus** [comment]
> One final requirement to get this merged: can you sign the attached and email it to me on [support@dependabot.com](mailto:support@dependabot.com)? Apologies for the hassle - we're planning to change the license on Dependabot Core (to something better drafted with the same intent, or to MIT) and need to ensure we have ownership of the IP to do so.
> 
> [Cees-Jan Kiewiet.pdf](https://github.com/dependabot/dependabot-core/files/3343290/Cees-Jan.Kiewiet.pdf)
> 
> Thanks masses for your work on this!

That might take a few days. For my personal time I would have signed in a heartbeat, but since I also spent two weeks worth I'll check and confirm with them first. Will keep you posted.

**Comment by rdohms** [comment]
@greysteil I have talked to our legal team and I'll send more details to the same email you recommended to answer a few questions they had.

**Comment by greysteil** [comment]
Signed doc received! I'll release this tomorrow morning (UK time).

**Comment by WyriHaximus** [comment]
Looking forward to that 🎉

**Comment by LeoColomb** [comment]
Does this PR fix #890? Can we drop all concrete extensions in our dependabot docker images? 🧹😉 Thx!

**Comment by greysteil** [comment]
That's the idea... 🤞 🎉

**Comment by greysteil** [comment]
Now release a `v0.111.0`. I'm deploying the change to Dependabot now.

Thanks again for all your work on this @WyriHaximus !

**Comment by WyriHaximus** [comment]
@greysteil you're more then welcome! PR's are starting to flow in on my own projects for example https://github.com/reactive-apps/command-http-server/pull/58 so we'll start enabling it at @usabilla very soon :tada: !

**Comment by alcaeus** [comment]
Only realised now that this has been fixed - thank you so much @WyriHaximus and @greysteil! ❤️

**Comment by WyriHaximus** [comment]
@alcaeus you're welcome :tada: !

**Pull request merged**
