### PR TITLE
[WIP] Bitbucket Server file fetcher

### PR DESCRIPTION
**Pull request by Kamiizumi**
Initial attempt at adding on-prem Bitbucket Server instances as a file fetcher source (mentioned in the comments of https://github.com/dependabot/feedback/issues/128).

It seems that on-prem Bitbucket Server instances uses a different API to Bitbucket Cloud, so I've created a separate BitbucketServer client for interacting with the API.

Still needs further testing and adding unit tests, but any initial feedback would be welcome 😄

### CODE REVIEW

**Comment by chris5287** [comment]
@greysteil congrats on the github news today! Just wonder what that means for integrations like this and other ecosystems like Azure DevOps/Gitlab/Bitbucket?

**Comment by chris5287** [comment]
FYI @Kamiizumi see #1211 for reference on how to implement a PullRequestCreator

**Comment by georgemathieson** [comment]
Really excited for this feature, any ETA on when it’s going to be finished? 😄

**Comment by oeph** [comment]
Are there any news on this?

**Comment by Kamiizumi** [comment]
I'm probably not going to be able to look into this anytime soon, as we're moving away from an Atlassian stack to Azure (which Dependabot already has fetchers for). I'm going to close out this PR so it's not left hanging around.

If anyone picks up this feature in the future the following points may be helpful:
- Bitbucket Cloud and Bitbucket Server (On-Prem) have different APIs, so make sure you're using the correct API ([BitBucket Server's API Docs](https://docs.atlassian.com/bitbucket-server/rest/6.5.1/bitbucket-rest.html) are quite well documented).
- While I was working on this I checked to see if there were any existing Ruby gems for interacting with BitBucket Server, but I wasn't able to find anything actively maintained. So instead I just directly called Bitbucket's REST API (based on the existing Dependabot client for Bitbucket Cloud).

**Comment by greysteil** [comment]
@Kamiizumi - thanks for your work on this and providing clarity for anyone else who wants to pick it up.

**Pull request closed without merging**
