### PR TITLE
Adds python 3.7.9.

### PR DESCRIPTION
**Pull request by jeremiq**
I think this is all that it takes to resolve https://github.com/dependabot/dependabot-core/issues/2520

### CODE REVIEW

**Review by kryskool — APPROVED** [review]

**Comment by jeremiq** [comment]
Oh no! The build is failing with this, 
```
.......python-build: definition not found: 3.7.9
```

I didn't see this failure locally since I ran the tests outside of docker. 

It seems that we're installing and using pyenv `v1.2.20`,  https://github.com/dependabot/dependabot-core/blob/main/Dockerfile#L70 and support for 3.7.9 wasn't added to pyenv until a month after that release (here's the merge that added it, https://github.com/pyenv/pyenv/commit/58c776a136a2c1b60ed104694fc14998e0fbb131). Unfortunately, there isn't yet a tagged pyenv release that contains 3.7.9 (I jumped the gun!). 

It's easy enough to start using a slightly newer version of pyenv, albeit by checking out a commit rather than a release tag. I'll prepare that change locally and run the tests via docker to verify.

**Comment by jeremiq** [comment]
Updating pyenv did fix the ci issues!

**Comment by jeremiq** [comment]
Hey @jurre, I saw you merged in https://github.com/dependabot/dependabot-core/pull/2561 which overlapped with this one a bit. Could you take a look at this PR as well?

Thanks!

**Review by jurre — APPROVED** [review]
Thanks @jeremiq

**Comment by jeremiq** [comment]
Thank you!

**Pull request merged**
