### PR TITLE
Add initial support for Helm dependencies

### PR DESCRIPTION
**Pull request by siavashs**
This implementation supports bumping chart dependencies under `Chart.yaml`.
It uses `Psych` to marshal and unmarshal the YAML file so comments are lost.
Updating `Chart.lock` and archives under `charts/` directory will be implemented in future.

This is a draft PR, it will be updated to add tests.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Unless I'm missing something this doesn't update the `Chart.lock` file?

**Comment by siavashs** [comment]
> Unless I'm missing something this doesn't update the `Chart.lock` file?

Correct, it will require installing and using `helm` binary (which can be done in this PR or a separate one).
Also see https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-695829118

**Comment by siavashs** [comment]
Closing this PR as no new ecosystems are accepted https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-767560668

**Comment by alexef** [comment]
@siavashs should we reopen this, as new ecosystems are again welcome? https://github.com/dependabot/dependabot-core/commit/0f931f452e9e51a3996a010ca21c90115b7f80cf

**Comment by rud** [comment]
Oooh, good find @alexef! What do you say @siavashs?

**Comment by siavashs** [comment]
Hey, good to know that new ecosystems are accepted again.
I might revive this when I find some free time.

**Comment by TheMeanBeanMachine** [comment]
Hey are you still working on this? I  could really use this functionality and could either support by creating pr to update the chart.lock file or i can take over and try to get this and the char.lock functionality over the finish line?

**Pull request closed without merging**
