### PR TITLE
If only 1 dep in group is updated, use solo title

### PR DESCRIPTION
**Pull request by pavera**
Fixes https://github.com/dependabot/dependabot-core/issues/7840

I believe I updated the tests to cover both single update and multi-update groups correctly, but this would be something @Nishnha, @jurre or @jakecoffman could hopefully confirm? The biggest question is that in the case of the "directory" test, I just updated the test to be a multi-update because I thought the main point there was the presence of "directory" in the title, and we have other tests that prove the correct behavior of single vs multi updates in groups so I didn't test single update groups with directory.

### CODE REVIEW

**Comment by honeyankit** [comment]
@pavera one test is failing in common. You just need to replace the multi-dir test with single dep test and test will pass.

**Comment by jurre** [comment]
I'd like to take a minute and think through wether this is actually a good change to make. My worry is that with this change it's not apparent that the PR is actually a grouped PR, which behave slightly differently from ungrouped PRs. I understand the desire to get more actionable information into the PR title, but we should think about the consequences of that as well.

**Comment by pavera** [comment]
As far as being able to tell if it is a grouped PR, the body still indicates that it is a bump in the group with 1 update. I did have the same concern about hiding all evidence of a group update and made sure the body still had that info. However, maybe we append or prepend `grouped` somehow in the title?

**Comment by pavera** [comment]
I like `Bump business from 1.0.0 to 2.0.0 in the all-the-things group` best of those 2 options, let me attempt to make that happen.

**Review by jurre — APPROVED** [review]

**Review by landongrindheim — APPROVED** [review]

**Pull request merged**
