### PR TITLE
chore(python): target latest python versions 3.12.0, 3.11.6, 3.10.13, 3.9.18, 3.8.18

### PR DESCRIPTION
**Pull request by dshick-nydig**
Last time done at https://github.com/dependabot/dependabot-core/pull/7914 by @phillipuniverse

### CODE REVIEW

**Comment by dshick-nydig** [comment]
A little stuck on the remaining spec tests failing. Will look again soon.

**Comment by dshick-nydig** [comment]
Sorry, haven't had any additional time to work on this yet due to some competing priorities. Hopefully I can find some personal time to dig deeper.

I suspect all of these relate to the deprecation of distutils and the resulting inability of python 3.12 to build certain older versions of complex packages from source, such as [numpy](https://github.com/numpy/numpy/issues/18588).

**Comment by enkhjile** [comment]
@dshick-nydig
Hello, thank you for your efforts on this. Could you please provide any updates or a rough estimate of when it will be completed?

**Comment by deivid-rodriguez** [comment]
I took over the upgrade at #8732, since it's almost there! Closing in favor of that one.

**Pull request closed without merging**
