### PR TITLE
cd: correctly find workspace.dependencies-declared dependencies and their Cargo.toml

### LINKED ISSUE #5864: Rust: Cargo.toml discovery fails if in a workspace and said manifest is not a member but used in members with workspace dependencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

rust, cargo

### Package manager version

cargo 1.64.0+

### Language version

rust 1.64.0+

### Manifest location and content before the Dependabot update

The situation appeared after my PR https://github.com/dependabot/dependabot-core/pull/5794, and this use case is a little weird so I didn't think about it.

1) Have a Cargo workspace, e.g:

```
root/
- Cargo.toml (C1)
- crate_in_workspace/Cargo.toml (C2)
- crate_outside_workspace/Cargo.toml (C3)
```

```toml
# In (C1)
[workspace.package]
version  = "1.0.0"

[workspace]
members = [ "crate_in_workspace" ]

[workspace.dependencies]
crate_outside_workspace = { version = "1", path = "./crate_outside_workspace" }
```

```toml
# In (C2)
[package]
version.workspace = true

[dependencies]
crate_outside_workspace.workspace = true
```

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Dependabot will currently fail on the config presented earlier with the error that it cannot find `crate_outside_workspace/Cargo.toml`.

This happens because the `workspace.dependencies` table is not looked at by the file filter and I forgot to add it when adding the support for workspace dependencies in #5794.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by ggawryal**
I've decided to pick up  #5865 as fixing the issue is quite urgent for my project. Added some more code to fetch `[workspace.dependencies]` from the root manifest, because extending `required_path?` function was not sufficient. Added a test as well - previously running dependabot on the repository I've attached to the test was finishing with a failure.

Closes #5864.

### CODE REVIEW

**Comment by jeffwidman** [comment]
Thanks for picking this up!

> Added some more code to fetch `[workspace.dependencies]` from the root manifest, because extending `required_path?` function was not sufficient

Ah, that explains why I kept running into problems when I'd tried to write the test myself.

I'm about to walk out the door to go camping, so hopefully someone else on the team can take a look... but if not, I'm happy to take a look next week. If you don't hear from someone by Wednesday, feel free to leave a comment and tag me by name as a reminder.

**Review by Nishnha — APPROVED** [review]
This looks great!

I'm not sure why the one Updater test is failing but it's not related to these changes.

I also looked at the [test repo](https://github.com/ggawryal/test-cargo-inherited-excluded-dependency/tree/fba33a8063a55519cfa0650691f7f7723a1dba81) and although it differs slightly from what's described in https://github.com/dependabot/dependabot-core/issues/5864, it looks correct.

Also, the requests to the test fixtures are all stubbed out so it's okay to reference the test repo 👍🏾

**Comment by Nishnha** [comment]
This is now in production.

**Comment by ggawryal** [comment]
That's a great news, many thanks for your support!

**Comment by abdulapopoola** [comment]
Thanks for helping to make :dependabot: better @ggawryal !

**Pull request merged**
