### PR TITLE
Add (failing) spec for Elixir update checking with a bad version requirement

### PR DESCRIPTION
**Pull request by greysteil**
This needs a change to our Elixir code so that it bubbles errors up to Ruby.

This can likely be done by using:
- The [arguments to System](https://hexdocs.pm/elixir/System.html#cmd/3)
- A conditional in `run.exs` to return an `"error"` (just needs to have the text of the error) to Ruby if the exit code of the command was non-zero

### CODE REVIEW

**Comment by greysteil** [comment]
@stevedomin - would love your help on this. I can have a go, but my Elixir is no good. What we want is for the helper to return something like `{ "error": "Text of the error!" }` here - we can then catch `HelperSubprocessFailed` errors on the Ruby side and raise the right error class accordingly.

If you run `bundle exec rspec spec/dependabot/update_checkers/elixir/hex_spec.rb:162` you'll see what's going on.

**Comment by stevedomin** [comment]
@greysteil let me know what you think of this.

**Comment by stevedomin** [comment]
Not sure what Rubocop mean?

**Comment by greysteil** [comment]
This looks rad. I've fixed the rubocop, but it looks like the `FileParser` specs are failing - can you take a look?

**Comment by greysteil** [comment]
Awesome! Going to ship this now. Huge props on the Elixir work - feels like it's had a really great reception.

**Comment by stevedomin** [comment]
Awesome to hear, would to see the numbers in a month or two.

**Comment by greysteil** [comment]
Me too - will definitely share them!

**Pull request merged**
