### PR TITLE
[WIP] Add support for gemspec path option

### PR DESCRIPTION
**Pull request by broder**
We were seeing an error for one of [our Gemfiles](https://github.com/UKGovernmentBEIS/beis-mspsds/blob/master/shared-web/Gemfile#L5):

```
Bundler::Dsl::DSLError with message: 
[!] There was an error parsing `Gemfile`: There are no gemspecs at /home/dependabot/dependabot-updater/dependabot_tmp_dir/shared-web/dev. Bundler cannot continue.

 #  from /home/dependabot/dependabot-updater/dependabot_tmp_dir/shared-web/Gemfile:5
 #  -------------------------------------------
 #  gemspec
 >  gemspec path: "./dev"
 #  
 #  -------------------------------------------
```

We're using the `path` option [as described here](https://bundler.io/v1.17/rubygems.html) but the [parsing code only supports gemspecs at the top level](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_parsers/ruby/bundler.rb#L281).

I've made a naive change to correct this but it seems like it breaks another test relating to path based `gem` dependencies. The correct solution might involve checking whether the `*.gemspec` file is part of a `gemspec qq, path: './some/path'` or `gem qq, path: './some/path'` declaration (as opposed to assuming that top level `*.gemspec`s are part of a `gemspec` declaration, which we're currently doing).

I couldn't see an obvious way to see which declaration (`gem` or `gemspec`) the `DependencyFile` was from, so I thought I'd ask! Do you have any thoughts for how we could do this?

Let me know if you need any more information. Thanks for the awesome service! 😃

### CODE REVIEW

**Comment by greysteil** [comment]
Thanks for this! I'll take a look and make any changes required. 🙂

**Comment by greysteil** [comment]
OK, so looking through, my first thought here is that we're going to need to extend the `FileFetcher` to be able to detect gemspecs specified with a path. The easiest way to do so is probably to write another class like `ChildGemfileFinder` that loops through detecting them.

Once that's done you're right that there might need to be changes to the parser, too, but I'm not sure and it'll be easier for me to get my head around it once the fetcher is done.

I'm happy to write the new class (`GemspecFinder`), or to have you take it and review it (only if you'd like to! It's basically an opportunity to play around with the `parser` gem, which is quite nice).

Let me know - I'll pick it up tonight / tomorrow if I don't hear back from you 🙂

**Comment by broder** [comment]
Happy for you to take it. It looks like there'll be a lot of overlap with `PathGemspecFinder` and then maybe a fair bit of refactoring to pass the declaration type to the parser - could be a bit of a rabbit-hole 🙂

**Comment by greysteil** [comment]
I want to add a couple of tests at the `UpdateChecker` and `FileUpdater` stage before shipping this, but running it locally against your repo it seems fine.

Will add those tests and get this out tonight / over the weekend. Thanks for flagging!

**Comment by greysteil** [comment]
OK, this should be good to go now - will merge and cut a release once tests pass.

Thanks for flagging this to us @broder, and for taking a first cut at the solution. Turns out there were a lot of places that assumed "top-level" gemspecs would always be in the top-level directory, so I'm glad I took this over. 🙂

**Pull request merged**
