### PR TITLE
Add support for docker-compose.yml files

### LINKED ISSUE #390: Support for Docker compose files
_From @armin-joellenbeck on December 23, 2017 9:21_

Knowing when new Docker images are published would be helpful when the are used in a Docker compose file too.

Just like #20, with the file `docker-compose.yml` instead of `Dockerfile`.

_Copied from original issue: dependabot/feedback#66_

### PR DESCRIPTION
**Pull request by pombeiro**
This PR adds support for `docker-compose.yml` files in the `docker` package. The approach was to add additional handlers alongside `docker/lib/dependabot/docker`, i.e. `docker/lib/dependabot/docker_compose`.

To address the duplication of code resulting from identical logic in e.g. parsing Docker image names or computing resulting updates some shared logic was extracted to modules under `docker/lib/dependabot/docker/utils`, which then get pulled in as mixins. For tests, I've added e.g. `docker/spec/dependabot/docker/common/shared_examples_for_docker_update_checkers.rb`, since most of the code is exactly the same.

Suggestions are welcome, especially on:
- the correct location for the `docker_compose` folder;
- the best way to share common Docker logic between `docker` and `docker_compose`;
- whether naming this as `docker_compose` is the right way. I see that some languages already support multiple package managers in Dependabot (e.g. `go:dep` and `go:modules`), so I'm wondering if this should be named `docker:compose` in [this list](https://dependabot.com/docs/config-file/#package_manager-required). I'm trying to figure out where that is configured, just searching for `go:modules` doesn't yield results.

Closes #390

```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb docker_compose buildkite/agent --dir .buildkite
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.5-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/buildkite/agent/.buildkite
=> parsing dependency files
=> updating 1 dependencies

=== golang (1.12)
 => checking for updates
 => latest version from registry is 1.13.1
 => latest resolvable version is 1.13.1
 => requirements to unlock: own
 => requirements update strategy: 
 => updating golang from 1.12 to 1.13.1

    ± docker-compose.yml
    ~~~
    5c5
    <     image: golang:1.12
    ---
    >     image: golang:1.13.1
    ~~~
```

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks @PombeirP! Would love to see support for docker-compose.yml land ❤️

**Comment by PombeirP** [comment]
@feelepxyz Don't know what is happening but the tests show as failing in the PR, while there's a newer CircleCI build that passed: https://circleci.com/gh/dependabot/dependabot-core/12398. Something fiddly with the CI integration with GH?

**Comment by rebelagentm** [comment]
@PombeirP @feelepxyz It looks like the tests are passing again.

**Comment by feelepxyz** [comment]
@PombeirP thanks for the contribution! Just a heads up that I won't be able to get to this immediately but hopefully get some time in the next week or so to review it thoroughly to make sure we understand the changes and can maintain it going forward.

**Comment by PombeirP** [comment]
@feelepxyz Sure, totally understand it, thanks for the transparency.

**Comment by badgerwithagun** [comment]
Looking forward to this

**Comment by ajcann** [comment]
Also looking forward to this getting in!

**Comment by erkannt** [comment]
@pedropombeiro Can you tell us why this PR was closed? Would love to use this.

**Comment by pedropombeiro** [comment]
@erkannt There was no feedback from reviewers for about 4 months, and because I keep a widget of open PRs in VS Code, I decided to clean that up a bit.

**Comment by falkenhawk** [comment]
> 
> 
> @erkannt There was no feedback from reviewers for about 4 months, and because I keep a widget of open PRs in VS Code, I decided to clean that up a bit.

😭

**Comment by lsh-0** [comment]
Think we can re-open this? Who do we have to prod to get some review feedback?

**Comment by bobvanderlinden** [comment]
@rebelagentm could you have a look again?

**Pull request closed without merging**
