### PR TITLE
Bump docker_registry2 to fix #3989

### LINKED ISSUE #3989: Dependabot not following pagination on Quay.io
**Package ecosystem**
Docker
**Package manager version**
NA
**Language version**
NA
**Manifest location and content prior to update**
**/Dockerfile**
```docker
FROM quay.io/invisionag/yet-another-cloudwatch-exporter:v0.24.0-alpha
USER exporter
```
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
```
**Updated dependency**
From: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.24.0-alpha`
To: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.27.0-alpha`
**What you expected to see, versus what you actually saw**
Dependabot reported that there are no updates on the docker image. Looking closer, the logs reported that the latest tag is `0.12.0-alpha`. Following the `GET https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list` operation shows that this is correct, but the response includes pagination (limit 50) which is likely not being followed.
**Native package manager behavior**
NA
**Images of the diff or a link to the PR, issue or logs**
NA
**🕹 Bonus points: Smallest manifest that reproduces the issue**
See above
**Additional info**
The `yet-another-cloudwatch-exporter` registry did move to using a `v` prefix in the image tag starting at  `v0.13.1-alpha`, however, there is a `0.13.0-alpha` tag, which should have been detected if the prefix was the case (I believe there is support for that prefix anyway based on https://github.com/dependabot/dependabot-core/pull/1195)
**Dependabot logs**
```
  proxy | time="2021-06-25T09:37:42Z" level=info msg="proxy starting" commit=97f78db7d4c42ec4f30c03ac9a981efd790f852d
  proxy | 2021/06/25 09:37:42 Listening (:1080)
updater | 2021-06-25T09:37:42.442133533 [165790641:main:WARN:src/devices/src/legacy/serial.rs:434] Detached the serial input due to peer close/error.
updater | time="2021-06-25T09:37:44Z" level=info msg="guest starting" commit=524810a0a39a9005af53185e9bb7817463751bc4
updater | time="2021-06-25T09:37:44Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=165790641 updater_timeout=45m0s updater_version=0.156.1-3e98b4e9cb1701f0fe394cdcf227935fa77fd407
updater | I, [2021-06-25T09:37:45.449859 #9]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_165790641> Starting job processing
  proxy | 2021/06/25 09:37:47 [002] GET https://api.github.com:443/repos/cyralinc/cyral-yace
  proxy | 2021/06/25 09:37:47 [002] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [002] 200 https://api.github.com:443/repos/cyralinc/cyral-yace
  proxy | 2021/06/25 09:37:47 [004] GET https://api.github.com:443/repos/cyralinc/cyral-yace/git/refs/heads/main
  proxy | 2021/06/25 09:37:47 [004] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [004] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/git/refs/heads/main
  proxy | 2021/06/25 09:37:47 [006] GET https://api.github.com:443/repos/cyralinc/cyral-yace/contents/?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [006] * authenticating github api request
  proxy | 2021/06/25 09:37:47 [006] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/contents/?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [008] GET https://api.github.com:443/repos/cyralinc/cyral-yace/contents/Dockerfile?ref=226e1445eb24abf365b113cc280832358ce56550
  proxy | 2021/06/25 09:37:47 [008] * authenticating github api request
  proxy | 2021/06/25 09:37:48 [008] 200 https://api.github.com:443/repos/cyralinc/cyral-yace/contents/Dockerfile?ref=226e1445eb24abf365b113cc280832358ce56550
updater | INFO <job_165790641> Finished job processing
updater | time="2021-06-25T09:37:48Z" level=info msg="task complete" container_id=job-165790641-file-fetcher exit_code=0 job_id=165790641 step=fetcher
updater | I, [2021-06-25T09:37:49.058595 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_165790641> Starting job processing
updater | INFO <job_165790641> Starting update job for cyralinc/cyral-yace
updater | INFO <job_165790641> Checking if invisionag/yet-another-cloudwatch-exporter v0.24.0-alpha needs updating
  proxy | 2021/06/25 09:37:51 [012] GET https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
  proxy | 2021/06/25 09:37:51 [012] 200 https://quay.io:443/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
updater | INFO <job_165790641> Latest version is 0.12.0-alpha
updater | INFO <job_165790641> No update needed for invisionag/yet-another-cloudwatch-exporter v0.24.0-alpha
updater | INFO <job_165790641> Finished job processing
updater | time="2021-06-25T09:37:51Z" level=info msg="task complete" container_id=job-165790641-updater exit_code=0 job_id=165790641 step=updater
```

### PR DESCRIPTION
**Pull request by noorul**
The latest version of docker_registry2 has the fix for #3989.

### CODE REVIEW

**Comment by Nishnha** [comment]
Thanks! 
Do you think you could add a quick test for this to confirm the bug is no longer present?

Feel free to reach out if you need help!

**Comment by noorul** [comment]
@Nishnha I am new to the code base. I tested the code manually on my machine. Can you point me to test file to which I can add this scenario?

**Comment by Nishnha** [comment]
@noorul, sure!

It looks like we specifically want to test that quay URLs go to the next page for paginated links

Paginated URLs are accessed by our docker client (docker_registry2) in https://github.com/dependabot/dependabot-core/blob/279956f9f28dd1dce087a2163615a8d6c99c827b/docker/lib/dependabot/docker/update_checker.rb#L231

and we eventually use that to determine the `latest version` of a dependency:
`#tags_from_registry` -> `#comparable_tags_from_registry` -> `#fetch_latest_version` -> `#latest_version`


So a test you may be able to set up is: with a paginated quay URL, the update check is able to follow the paginated URL to find the latest version
https://github.com/dependabot/dependabot-core/blob/279956f9f28dd1dce087a2163615a8d6c99c827b/docker/spec/dependabot/docker/update_checker_spec.rb#L160

**Review by Nishnha — APPROVED** [review]
I'm going ahead with approving this since its a gem version update and I don't want to block other fixes this might offer. We will follow up with some test cases for the pagination issue @noorul mentioned after the rollout.

**Comment by noorul** [comment]
@Nishnha Great! Thanks! I couldn't find time to get to this.

**Pull request merged**
