### PR TITLE
build(deps): bump PNPM from 8.3.1 to 8.6.4

### PR DESCRIPTION
**Pull request by yeikel**
See https://github.com/pnpm/pnpm/releases/tag/v8.6.4

### CODE REVIEW

**Comment by jeffwidman** [comment]
As always, thank you for these!

FYI that internally we have a deploy freeze for the next few days.

Once that ends, we'd prefer to avoid a big-bang release, so while we'll be merging docs changes and minor tweaks here and there, we're going to delay merging anything that bumps versions...

That way when the freeze lifts we can have a smaller safer deploy, get a healthy baseline of metrics, then iteratively start merging the slightly riskier bumps and watching them in production.

**Review by jurre — APPROVED** [review]
We'll need to hold off merging this for a bit more, but going to approve so we know that it's good to go once we're ready

**Comment by deivid-rodriguez** [comment]
I edited this PR to bump PNPM all the way to 8.6.3.

The upgrade also fixes an issue specific to lockfiles generated with either PNPM 8.6.0 and 8.6.1. Those versions generated a lockfile format (`lockfileVersion: '6.1'`) that previous PNPM versions cannot handle.

This will need some updates to smoke tests.

**Comment by deivid-rodriguez** [comment]
Smoke tests failure should get fixed by https://github.com/dependabot/smoke-tests/pull/82.

**Comment by deivid-rodriguez** [comment]
@jurre You had already approved this but I added a few more changes on top of it, so I'll wait for a second review if that's ok 🙏.

**Comment by deivid-rodriguez** [comment]
This PR fixes [this error](https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-1588391864) by the way!

**Comment by yeikel** [comment]
@deivid-rodriguez 8.6.4 was released a couple of hours ago and I just updated this PR

**Comment by deivid-rodriguez** [comment]
Thank you! By the way this is the [upstream issue](https://github.com/pnpm/pnpm/issues/6648) for the problem with the `6.1` format (now reverted as of 8.6.4).

**Review by brrygrdn — APPROVED** [review]
🚀

**Comment by deivid-rodriguez** [comment]
Thank you @yeikel!

**Pull request merged**
