### PR TITLE
Allow passing autoCompleteIgnoreConfigIds value for azure

### PR DESCRIPTION
**Pull request by mburumaxwell**
Autocomplete functionality added in #4064 is missing a variable to set autoCompleteIgnoreConfigIds. This PR adds it.

### CODE REVIEW

**Review by jeffwidman — COMMENTED** [review]
What does this field represent? Should there be a unit test for passing a non-default value?

**Comment by mburumaxwell** [comment]
According to the docs, "List of any policy configuration Id's which auto-complete should not wait for. Only applies to optional policies"

I don't believe there is a need to test for non-default values given:
1. This is just for Azure DevOps and not any other provider
2. The method is only invoked in unofficial usage e.g. an extension or custom usage
3. The value is only serialized and not used for anything else like making another object.

**Comment by mburumaxwell** [comment]
@jeffwidman your thoughts?

**Comment by mburumaxwell** [comment]
@jeffwidman the test is in. Okay now?

**Review by jeffwidman — APPROVED** [review]
My apologies, I lost track of this.

Looks great!

**Pull request merged**
