### PR TITLE
Add Python 3.9

### PR DESCRIPTION
**Pull request by ulgens**
New Python version, new update PR :slightly_smiling_face:

### CODE REVIEW

**Comment by ulgens** [comment]
@jurre @feelepxyz :wave: 

Apart from the PR and its content, is it possible to add `hacktoberfest` to repo's topics?

**Comment by jurre** [comment]
Thanks @ulgens, I'll have a look at the failing tests later.

> Apart from the PR and its content, is it possible to add hacktoberfest to repo's topics?

We can't really handle any increased PR volume from new contributors that may come in via hacktoberfest at this time, but if you could send me an email at <handle> @ <this website> I'll be happy to chat about another way to show our appreciation for your contributions!

**Comment by ulgens** [comment]
@jurre Thanks for the positive feedback :slightly_smiling_face: Seeing my PRs are getting merged is just enough motivation to continue.

**Comment by ulgens** [comment]
@jurre I tried to run tests several times, Python tests pass but the others seem to fail randomly.

**Review by codingjoe — APPROVED** [review]
LGTM 👍 really looking forward to this one, since my upgrades are stuck after upgrading our stacks.

**Review by jurre — APPROVED** [review]

**Pull request merged**
