### PR TITLE
Stop running Bundler v1

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What are you trying to accomplish?

Stop running Bundler v1 internally, and thus dropping all Bundler v1 specific code, without dropping support for providing updates for Bundler v1 lockfiles.

### Anything you want to highlight for special attention from reviewers?

To do this, I adapted native helpers to pass an explicitly requirement on the locked version of Bundler to the resolver. With that in place, the end user behavior should still be the same. Ironically, the changes caused some trouble in Bundler 2. I think it should be possible to reconcile that, but for now I only changed helpers when locked bundler version is v1, and left helpers unchanged otherwise. It seemed also a plus to make this less risky to not change anything for Bundler v2.

Also, I'm pretty sure @jurre will ask about the following so I'll explain. There's some stuff that may change in edge cases. For example, if v1 lockfile uses multiple global sources (something considered insecure), Dependabot will now start splitting the gems in the lockfile by the source they come from. I'm not sure how Bundler 1 deals with that, and since Dependabot currently does not modify the `BUNDLED WITH` section in the lockfile, it may cause some trouble.

I think the above is acceptable given Bundler 1 is very old, and only particular cases like that may be affected, but generally updates should still work fine!
 
### How will you know you've accomplished your goal?

Bundler v1 users can still get Dependabot PRs, and at the same time we can get rid of all the Bundler v1 specific code. 

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [ ] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Probably worth doing some realworld testing, but a green spec suite, both with bundler 1 and bundler 2, is reassuring!

Regarding spec changes, I only changed expectations when I considered the new behavior in Bundler 2 better. When it was not clear, I fixed things so that things still work as the work today.

**Comment by jurre** [comment]
Thanks David! Should we consider just dropping support for bundler v1 altogether instead?

**Comment by deivid-rodriguez** [comment]
I don't know but this is ready, so shouldn't be necessary to make that decision now if you don't want to!

**Comment by jurre** [comment]
I'm mostly thinking if we just drop support, we don't need to worry about potential edge-cases or patch up any issues we find with how this works against real world bundler 1 projects.

**Comment by deivid-rodriguez** [comment]
🤷‍♂️ Up to you! I'm just proposing this because the previous times this was approach the number of users was still not small enough to justify a hard drop. Since the main annoyance of supporting Bundler v1 is maintaining a doubled code base, I figured we can fix the main annoyance and let users keep gradually moving on without disruption.

**Comment by deivid-rodriguez** [comment]
Maybe ship this and announce official Bundler v1 deprecation at the same time, announcing that while support is still there, internal changes my cause issues for some users that won't necessarily be addressed.

**Comment by amazimbe** [comment]
> @amazimbe can you help deploy this?

Yes, I will.

**Review by amazimbe — APPROVED** [review]

**Review by thavaahariharangit — APPROVED** [review]
As per the discussion with Abdul

**Comment by amazimbe** [comment]
@jurre I'm not able to deploy this without your approval. Please take a look when you get a chance.

**Comment by jurre** [comment]
To be entirely honest, I feel a little unsure about this change, David captured my reservations well in the PR body.

I would much rather we just push to stop supporting Bundler v1 altogether, rather than have potentially broken support out there. My worry is that, yes it might work for people using a single source, but the potential support burden from people who are using multiple sources seems not worth the risk. If we're not committed to fully supporting Bundler 1, and to be candid, I am not, I'd rather we just drop support entirely and communicate that clearly to our customers.

 As mentioned, Bundler v1 is very old, usage is low, the upgrade path is really good these days. Why should we put ourselves in this awkward situation?

cc @jonjanego can we sync up soon-ish and decide if we can move forward with dropping support for Bundler v1, rather than having potentially incompatible support?

If we _do_ decide we want to move forward with this change, we should IMO at the very least test the scenario where we're using multiple sources with Bundler 1 and see how this implementation handles that, so we can update our documentation to reflect the limitation if necessary.

**Comment by deivid-rodriguez** [comment]
No worries @jurre, I understand being careful, and that's precisely why I proposed this as a way to unblock dropping support, since it has been postponed a few times precisely to avoid disrupting users. But I do understand that this will still be disrupting.

How about this alternative approach:

If Dependabot finds a Bundler v1 lockfile, then it ignores all dependencies, except for Bundler itself, and proposes a PR to upgrade Bundler. Once the PR is merged, users can get PRs for the other dependencies again.

**Comment by jurre** [comment]
Let me talk to Jon about dropping support altogether, and let's also thoroughly test this approach on some real world v1 repo's.

I noticed some v2 fixtures with multiple sources actually use the v1 format, for example [this one](https://github.com/dependabot/dependabot-core/blob/e44facc0f8e49c140f2e62abb401a4ddc6e9e71a/bundler/spec/fixtures/projects/bundler2/sidekiq_pro/Gemfile.lock). I'm actually not quite sure what that means for our test suite here, but either way it'd be good to double check how this _actually_ behaves. @amazimbe is going to run through some examples in a bit.

**Comment by deivid-rodriguez** [comment]
Awesome, let me know if you need help!

**Comment by deivid-rodriguez** [comment]
I was curious and I tried this, and I can confirm the behavior:

* Dependabot will split sources in lockfile for security if used to upgrade a lockfile with merged source.
* Bundler v1 will either merge them back (if run in non frozen mode), or fail (if run in frozen mode).

Note that this is not a new issue though, it already happened for 2.x lockfiles when Dependabot migrated to the version of Bundler that started splitting sources. See for example: https://github.com/dependabot/dependabot-core/issues/4095.

I think the best course of action would be what I proposed earlier:

* If Dependabot finds a Bundler v1 lockfile, then it ignores all dependencies, except for Bundler itself, and proposes a PR to upgrade Bundler.
* Once that PR is merged, users can get PRs for the other dependencies again.

**Comment by amazimbe** [comment]
I run this against a repo with : 
bundler version 1.17.3
ruby 2.7.0

but it did not update the bundler version.

**Comment by deivid-rodriguez** [comment]
Yes, that's correct. Currently Dependabot never updates the Bundler version, and that's what will create issues here. Dependabot will upgrade the lockfile to "v2 format" but will keep "BUNDLED WITH 1.17.3" in it. And that will cause issues in edge cases like the multiple sources situation we were discussing.

Hence my suggestion of actually adding support in Dependabot for upgrading the version of Bundler in the lockfile. Then we can completely stop creating PRs for Bundler v1 lockfiles, except for upgrading the Bundler version itself, and once users merge that PR and upgrade to Bundler v2, they get their Dependabot PRs back.

**Comment by amazimbe** [comment]
> Yes, that's correct. Currently Dependabot never updates the Bundler version, and that's what will create issues here. Dependabot will upgrade the lockfile to "v2 format" but will keep "BUNDLED WITH 1.17.3" in it. And that will cause issues in edge cases like the multiple sources situation we were discussing.
> 
> Hence my suggestion of actually adding support in Dependabot for upgrading the version of Bundler in the lockfile. Then we can completely stop creating PRs for Bundler v1 lockfiles, except for upgrading the Bundler version itself, and once users merge that PR and upgrade to Bundler v2, they get their Dependabot PRs back.

In my case the lockfile stays in v1 format

**Comment by deivid-rodriguez** [comment]
> In my case the lockfile stays in v1 format

So, it proposes correct updates and does not update the format? Then that sounds perfect 😅. I have to admit I tried Bundler directly but not Dependabot as in this PR, so maybe you are right and this is fine after all!

**Comment by amazimbe** [comment]
> > In my case the lockfile stays in v1 format
> 
> So, it proposes correct updates and does not update the format? Then that sounds perfect 😅. I have to admit I tried Bundler directly but not Dependabot as in this PR, so maybe you are right and this is fine after all!

This is the log I get on the simple bundle v1 repo that I'm running this against
```

updater | 2024/07/10 11:32:49 INFO Starting job processing
  proxy | 2024/07/10 11:32:49 [007] POST http://host.docker.internal:50326/update_jobs/cli/update_dependency_list
{"data":{"dependencies":[{"name":"hola","requirements":[{"file":"Gemfile","groups":["default"],"requirement":"0.0.0","source":{"type":"rubygems","url":"https://amazimbe:XXX@rubygems.pkg.github.com/dsp-testing/"}}],"version":"0.0.0"},{"name":"irb","requirements":[{"file":"Gemfile","groups":["default"],"requirement":"\u003e= 0","source":null}],"version":"1.14.0"},{"name":"io-console","requirements":[],"version":"0.7.2"},{"name":"psych","requirements":[],"version":"5.1.2"},{"name":"rdoc","requirements":[],"version":"6.7.0"},{"name":"reline","requirements":[],"version":"0.5.9"},{"name":"stringio","requirements":[],"version":"3.1.1"}],"dependency_files":["/Gemfile","/Gemfile.lock"]},"type":"update_dependency_list"}
  proxy | 2024/07/10 11:32:49 [007] 200 http://host.docker.internal:50326/update_jobs/cli/update_dependency_list
{"data":{"metric":"updater.started","tags":{"operation":"update_all_versions"}},"type":"increment_metric"}
  proxy | 2024/07/10 11:32:49 [008] POST http://host.docker.internal:50326/update_jobs/cli/increment_metric
  proxy | 2024/07/10 11:32:49 [008] 200 http://host.docker.internal:50326/update_jobs/cli/increment_metric
updater | 2024/07/10 11:32:49 INFO Starting update job for dsp-testing/alfred-bundler1-test
updater | 2024/07/10 11:32:49 INFO Checking all dependencies for version updates...
updater | 2024/07/10 11:32:49 INFO Checking if hola 0.0.0 needs updating
  proxy | 2024/07/10 11:32:50 [010] GET https://rubygems.pkg.github.com:443/dsp-testing/versions
  proxy | 2024/07/10 11:32:50 [010] 200 https://rubygems.pkg.github.com:443/dsp-testing/versions
  proxy | 2024/07/10 11:32:50 [012] GET https://rubygems.pkg.github.com:443/dsp-testing/info/hola
  proxy | 2024/07/10 11:32:51 [012] 200 https://rubygems.pkg.github.com:443/dsp-testing/info/hola
updater | 2024/07/10 11:32:51 INFO Latest version is 0.0.0
updater | 2024/07/10 11:32:51 INFO No update needed for hola 0.0.0
updater | 2024/07/10 11:32:51 INFO Checking if irb 1.14.0 needs updating
  proxy | 2024/07/10 11:32:51 [014] GET https://rubygems.org:443/api/v1/versions/irb.json
  proxy | 2024/07/10 11:32:52 [014] 200 https://rubygems.org:443/api/v1/versions/irb.json
updater | 2024/07/10 11:32:52 INFO Filtered out 15 pre-release versions
updater | 2024/07/10 11:32:52 INFO Latest version is 1.14.0
updater | 2024/07/10 11:32:52 INFO No update needed for irb 1.14.0
updater | 2024/07/10 11:32:52 INFO Checking if io-console 0.7.2 needs updating
  proxy | 2024/07/10 11:32:52 [016] GET https://rubygems.org:443/api/v1/versions/io-console.json
  proxy | 2024/07/10 11:32:53 [016] 200 https://rubygems.org:443/api/v1/versions/io-console.json
updater | 2024/07/10 11:32:53 INFO Latest version is 0.7.2
updater | 2024/07/10 11:32:53 INFO No update needed for io-console 0.7.2
updater | 2024/07/10 11:32:53 INFO Checking if psych 5.1.2 needs updating
  proxy | 2024/07/10 11:32:53 [018] GET https://rubygems.org:443/api/v1/versions/psych.json
  proxy | 2024/07/10 11:32:53 [018] 200 https://rubygems.org:443/api/v1/versions/psych.json
updater | 2024/07/10 11:32:53 INFO Filtered out 26 pre-release versions
updater | 2024/07/10 11:32:53 INFO Latest version is 5.1.2
updater | 2024/07/10 11:32:53 INFO No update needed for psych 5.1.2
updater | 2024/07/10 11:32:53 INFO Checking if rdoc 6.7.0 needs updating
  proxy | 2024/07/10 11:32:53 [020] GET https://rubygems.org:443/api/v1/versions/rdoc.json
  proxy | 2024/07/10 11:32:54 [020] 200 https://rubygems.org:443/api/v1/versions/rdoc.json
updater | 2024/07/10 11:32:54 INFO Filtered out 17 pre-release versions
updater | 2024/07/10 11:32:54 INFO Latest version is 6.7.0
updater | 2024/07/10 11:32:54 INFO No update needed for rdoc 6.7.0
updater | 2024/07/10 11:32:54 INFO Checking if reline 0.5.9 needs updating
  proxy | 2024/07/10 11:32:54 [022] GET https://rubygems.org:443/api/v1/versions/reline.json
  proxy | 2024/07/10 11:32:55 [022] 200 https://rubygems.org:443/api/v1/versions/reline.json
updater | 2024/07/10 11:32:55 INFO Filtered out 12 pre-release versions
updater | 2024/07/10 11:32:55 INFO Latest version is 0.5.9
updater | 2024/07/10 11:32:55 INFO No update needed for reline 0.5.9
updater | 2024/07/10 11:32:55 INFO Checking if stringio 3.1.1 needs updating
  proxy | 2024/07/10 11:32:55 [024] GET https://rubygems.org:443/api/v1/versions/stringio.json
  proxy | 2024/07/10 11:32:55 [024] 200 https://rubygems.org:443/api/v1/versions/stringio.json
updater | 2024/07/10 11:32:55 INFO Filtered out 2 pre-release versions
updater | 2024/07/10 11:32:55 INFO Latest version is 3.1.1
updater | 2024/07/10 11:32:55 INFO No update needed for stringio 3.1.1
{"data":{"base-commit-sha":"302b47a90f0477affd107e40e7ad0ce5d083c479"},"type":"mark_as_processed"}
  proxy | 2024/07/10 11:32:55 [025] PATCH http://host.docker.internal:50326/update_jobs/cli/mark_as_processed
  proxy | 2024/07/10 11:32:55 [025] 200 http://host.docker.internal:50326/update_jobs/cli/mark_as_processed
updater | 2024/07/10 11:32:55 INFO Finished job processing
  proxy | 2024/07/10 11:32:56 Skipping sending metrics because api endpoint is empty
  proxy | 2024/07/10 11:32:56 0/11 calls cached (0%)
```

To test it I pulled this branch locally and then run against my bundle v1 repo with multiple sources

`script/dependabot update bundler dsp-testing/alfred-bundler1-test`

**Comment by deivid-rodriguez** [comment]
Oh, but it seems that repo does not need any updates? Of course if Bundler won't create any PRs it won't change the lockfile format. I think we'd need to test on a repository that actually needs updates. I suggest downgrading some gem manually and committing the updated Gemfile/Gemfile.lock file, and then trying again.

**Comment by amazimbe** [comment]
> Oh, but it seems that repo does not need any updates? Of course if Bundler won't create any PRs it won't change the lockfile format. I think we'd need to test on a repository that actually needs updates. I suggest downgrading some gem manually and committing the updated Gemfile/Gemfile.lock file, and then trying again.

I downgraded one gem and then run it again. It generated a pr but in the gemfile.lock the bundler format is still v1

**Comment by abdulapopoola** [comment]
Tagging @jurre and @deivid-rodriguez for final approvals. If this meets the bar, then @amazimbe can get it deployed. 

Thanks.

**Comment by jurre** [comment]
@amazimbe can you share the before and after lockfiles from those updates where we can see the updated dependency but the format staying the same?

**Comment by amazimbe** [comment]
> @amazimbe can you share the before and after lockfiles from those updates where we can see the updated dependency but the format staying the same?

**Before**
```
GEM
  remote: https://rubygems.org/
  remote: https://xxxx:xxxx@rubygems.pkg.github.com/xxxx/
  specs:
    connection_pool (2.4.1)
    hola (0.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    psych (5.1.2)
      stringio
    rack (3.1.6)
    rack-protection (3.0.6)
      rack
    rdoc (6.7.0)
      psych (>= 4.0.0)
    redis (5.2.0)
      redis-client (>= 0.22.0)
    redis-client (0.22.2)
      connection_pool
    reline (0.5.9)
      io-console (~> 0.5)
    sidekiq (6.0.1)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    stringio (3.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  hola (= 0.0.0)!
  irb
  sidekiq (= 6.0.1)

BUNDLED WITH
   1.17.3

```
After

```
GEM
  remote: https://rubygems.org/
  remote: https://xxxx:xxxx@rubygems.pkg.github.com/xxxx/
  specs:
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    hola (0.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    logger (1.6.0)
    psych (5.1.2)
      stringio
    rack (3.1.6)
    rdoc (6.7.0)
      psych (>= 4.0.0)
    redis-client (0.22.2)
      connection_pool
    reline (0.5.9)
      io-console (~> 0.5)
    sidekiq (7.3.0)
      concurrent-ruby (< 2)
      connection_pool (>= 2.3.0)
      logger
      rack (>= 2.2.4)
      redis-client (>= 0.22.2)
    stringio (3.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  hola (= 0.0.0)!
  irb
  sidekiq (= 7.3.0)

BUNDLED WITH
   1.17.3

```

**Comment by amazimbe** [comment]
I've had a call with @jurre regarding this PR and some of what I wrote earlier has turns out to be incorrect. To avoid confusion, I'll summarise the current state of play in this comment.

Before running this CLI against my bundler v1 repo the Gemfile.lock was like this:
```
GEM
  remote: https://rubygems.org/
  remote: https://xxxx:xxxx@rubygems.pkg.github.com/xxxx/
  specs:
    connection_pool (2.4.1)
    hola (0.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    psych (5.1.2)
      stringio
    rack (3.1.6)
    rack-protection (3.0.6)
      rack
    rdoc (6.7.0)
      psych (>= 4.0.0)
    redis (5.2.0)
      redis-client (>= 0.22.0)
    redis-client (0.22.2)
      connection_pool
    reline (0.5.9)
      io-console (~> 0.5)
    sidekiq (6.0.1)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    stringio (3.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  hola (= 0.0.0)!
  irb
  sidekiq (= 6.0.1)

BUNDLED WITH
   1.17.3

```

After running this CLI against my  bundler v1 repo, the output contained:

```
GEM
    remote: https://rubygems.pkg.github.com/xxxx/
    specs:
       hola (0.0.0)

GEM
    remote: https://rubygems.org/
    specs:
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    io-console (0.7.2)
    irb (1.14.0)
        rdoc (>= 4.0.0)
        reline (>= 0.4.2)
    logger (1.6.0)
    psych (5.1.2)
        stringio
    rack (3.1.7)
    rdoc (6.7.0)
        psych (>= 4.0.0)
    redis-client (0.22.2)
        connection_pool
    reline (0.5.9)
        io-console (~> 0.5)
    sidekiq (7.3.0)
        concurrent-ruby (< 2)
        connection_pool (>= 2.3.0)
        logger
        rack (>= 2.2.4)
        redis-client (>= 0.22.2)
    stringio (3.1.1)

PLATFORMS
    ruby

DEPENDENCIES
    hola (= 0.0.0)!
    irb
    sidekiq (= 7.3.0)

BUNDLED WITH
    1.17.3
```

This is indeed in V2 format. 

We then run `bundle _1.17.3_ update` in the v1 repo and the new Gemfile.lock reverted back to the original i.e.
```

GEM
  remote: https://rubygems.org/
  remote: https://xxxx:xxxx@rubygems.pkg.github.com/xxxx/
  specs:
    connection_pool (2.4.1)
    hola (0.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    psych (5.1.2)
      stringio
    rack (3.1.7)
    rack-protection (3.0.6)
      rack
    rdoc (6.7.0)
      psych (>= 4.0.0)
    redis (5.2.0)
      redis-client (>= 0.22.0)
    redis-client (0.22.2)
      connection_pool
    reline (0.5.9)
      io-console (~> 0.5)
    sidekiq (6.0.1)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    stringio (3.1.1)

PLATFORMS
  ruby
  unknown

DEPENDENCIES
  hola (= 0.0.0)!
  irb
  sidekiq (= 6.0.1)

BUNDLED WITH
   1.17.3

```

To conclude, I believe we have 3 main options: 

1. Remove support for bundler v1 completely as bundler v1 is more than 6 years old. But as @deivid-rodriguez mentioned earlier, this has been tried before but we haven't actually done it due to the number of v1 users still being significant.
2. As proposed by @deivid-rodriguez, make changes to Dependabot so that it only creates a PR to upgrade bundler if it encounters a bundler v1 lockfile. This would be like a forced bundler upgrade.
3. Merge this as is and document the flip flopping when users manually run `bundle update` to avoid confusion. From what I've seen, this would lose the updates made by dependabot every time `bundle update` is run so it could be confusing and perhaps ineffective.

**Comment by amazimbe** [comment]
On hold awaiting input from product about how we would like to proceed.

**Comment by deivid-rodriguez** [comment]
No longer relevant 🎉. Thanks all :)

**Pull request closed without merging**
