### PR TITLE
Upgrade to `composer/composer:2.2.3`

### PR DESCRIPTION
**Pull request by Ocramius**
`composer/composer:2.2.0` introduced multiple improvements in terms of update performance
and reduced I/O.

This upgrade also allows to upgrade projects that moved to `composer-runtime-api:^2.2`, where
dependabot no longer performs any updates.

### CODE REVIEW

**Comment by Ocramius** [comment]
@jurre squashed it into previous commit :+1:

**Comment by jurre** [comment]
> @jurre squashed it into previous commit 👍

Sweet, letting CI do it's thing, hope there aren't any breaking changes to the code (we pull composer in as a library and I've ran into issues there)

**Comment by jurre** [comment]
The cargo failure seems unrelated, I'll dig into what's happening there

**Comment by Ocramius** [comment]
## Failure 1 

https://github.com/dependabot/dependabot-core/blob/79e34e902a6ab7814b555bb3e22668ef56f76aa1/composer/spec/dependabot/composer/update_checker_spec.rb#L465-L478

```
  1) Dependabot::Composer::UpdateChecker#latest_resolvable_version with a version conflict at the latest version where the blocking dependency is a git dependency is the highest resolvable version
     # No reason given
     Failure/Error: expect(latest_resolvable_version).to eq(Gem::Version.new("2.1.7"))

       expected: #<Gem::Version "2.1.7">
            got: nil

       (compared using ==)
     # ./spec/dependabot/composer/update_checker_spec.rb:475:in `block (5 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

What could be happening here is that `doctrine/dbal:2.1.7` really cannot be installed with `composer/composer:2.2.3` anymore? I'll try it out locally. 

## Failure 2

https://github.com/dependabot/dependabot-core/blob/79e34e902a6ab7814b555bb3e22668ef56f76aa1/composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb#L730-L764

```

  2) Dependabot::Composer::FileUpdater::LockfileUpdater the updated lockfile when there are patches (composer v2) doesn't strip the patches
     # No reason given
     Failure/Error:
       expect(updated_dep.dig("extra", "patches_applied")).
         to include("[PATCH] markdown modified")

       expected nil to include "[PATCH] markdown modified", but it does not respond to `include?`
     # ./spec/dependabot/composer/file_updater/lockfile_updater_spec.rb:761:in `block (4 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

Unsure what this one is doing, but I'll see how `composer/composer:2.2.3` behaves here, locally.

## Failure 3

https://github.com/dependabot/dependabot-core/blob/main/composer/spec/dependabot/composer/update_checker_spec.rb#L566-L579


```
  1) Dependabot::Composer::UpdateChecker#latest_resolvable_version with a git source dependency that's not the dependency we're checking with an alias 
     Failure/Error:
       SharedHelpers.run_helper_subprocess(
         command: "php -d memory_limit=-1 #{php_helper_path}",
         allow_unsafe_shell_command: true,
         function: "get_latest_resolvable_version",
         args: [
           Dir.pwd,
           dependency.name.downcase,
           git_credentials,
           registry_credentials
         ]

     Dependabot::SharedHelpers::HelperSubprocessFailed:
       Could not authenticate against github.com
     # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:120:in `run_helper_subprocess'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:131:in `block in run_update_checker'
     # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:164:in `with_git_configured'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:130:in `run_update_checker'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:81:in `block in fetch_latest_resolvable_version_string'
     # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
     # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `chdir'
     # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:79:in `fetch_latest_resolvable_version_string'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:64:in `fetch_latest_resolvable_version'
     # ./lib/dependabot/composer/update_checker/version_resolver.rb:54:in `latest_resolvable_version'
     # ./lib/dependabot/composer/update_checker.rb:34:in `latest_resolvable_version'
     # ./spec/dependabot/composer/update_checker_spec.rb:194:in `block (3 levels) in <top (required)>'
     # ./spec/dependabot/composer/update_checker_spec.rb:578:in `block (4 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

This one is because we are not authenticating against github, whilst trying to use a git repo as upstream dependency, I think.

**Comment by Ocramius** [comment]
When re-building locally (from scratch), I don't get to the tests:

```
Post-install message from httparty:
When you HTTParty, you must party hard!
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 35 files
..C................................

Offenses:

failure1/test.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
    context "with a version conflict at the latest version" do
^
failure1/test.rb:1:5: C: [Correctable] Layout/InitialIndentation: Indentation of first line in file detected.
    context "with a version conflict at the latest version" do
    ^^^^^^^

35 files inspected, 2 offenses detected, 2 offenses auto-correctable
```

I suppose the `--caches-from` cause a bit of stale information, so contributing is a bit messy right now :D

**Comment by Ocramius** [comment]
Ok, got tests working locally, and fixed those that have discrepancies with `composer/composer:2.2.3` (due to changed error messages).

What I found so far: 

 * `composer/spec/fixtures/projects/git_source_conflict_at_latest` cannot be upgraded, in `composer/composer:2.2.3` (even if `-W`), and fails with:
    ```
    bash-5.1# composer update --dry-run -W
    Loading composer repositories with package information
    Updating dependencies
    Your requirements could not be resolved to an installable set of packages.
    
    Problem 1
    - Root composer.json requires doctrine/common dev-master, it is found doctrine/common[dev-master] in the lock file and doctrine/common[dev-upgrade-release-workflow, 2.1.3, ..., 2.13.x-dev, 3.0.0, ..., 3.2.x-dev] from composer repo (https://repo.packagist.org) but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one from the lock file.
    Problem 2
    - Root composer.json requires doctrine/dbal ~2.1.5 -> satisfiable by doctrine/dbal[2.1.5, 2.1.6, 2.1.7].
    - doctrine/dbal[2.1.5, ..., 2.1.7] require doctrine/common 2.* -> found doctrine/common[2.1.3, ..., 2.13.x-dev] but it conflicts with your root composer.json require (dev-master).
    
    Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
    ```
    It is possible that this scenario is no longer valid, perhaps? :thinking: 
 * `composer/spec/fixtures/projects/patches` needed updating, because `composer/composer:2.2.0` became much stricter around plugin execution, for security reasons. Still, the test fails: seems like the `but it does not respond to `include?` error indicates a runtime type mismatch? Not enough ruby-fu to understand what is going on...

**Comment by jurre** [comment]
> composer/spec/fixtures/projects/git_source_conflict_at_latest cannot be upgraded

From reading that test, I don't think it's supposed to work, it's just not expected to raise an error? Maybe we catch a specific error message from composer here and handle it differently?

**Comment by Ocramius** [comment]
> Maybe we catch a specific error message from composer here and handle it differently?

Possibly - the error messages changed/improved a lot, so perhaps the parsing needs rewriting there :thinking:

**Comment by jurre** [comment]
> composer/spec/fixtures/projects/patches

The test that touches that project is marked as `pending` I believe, so it shouldn't fail the build, it's expected to fail but we ignore the failure:

https://github.com/dependabot/dependabot-core/blob/79e34e902a6ab7814b555bb3e22668ef56f76aa1/composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb#L754-L763

**Comment by Ocramius** [comment]
Seems like my changes actually worsened the CI results: this is a bit weird, and I think it may be due to stale information on the container built in CI :S

**Comment by jurre** [comment]
> Seems like my changes actually worsened the CI results: this is a bit weird, and I think it may be due to stale information on the container built in CI :S

Yep I noticed the same thing last night and I am looking into that right now

**Comment by jurre** [comment]
I _think_ this might resolve that issue @Ocramius, could you try rebasing against it? https://github.com/dependabot/dependabot-core/pull/4596

**Comment by Ocramius** [comment]
Giving it a shot :+1:

**Comment by Ocramius** [comment]
I included  033ebc0  from #4596

**Comment by jurre** [comment]
I noticed CI is still failing, but unsure if it's because it's using the wrong version of the Docker image, or if they are legitimate?

**Comment by Ocramius** [comment]
Not sure: possibly need to rebuild my environment from scratch then 😬

**Comment by jurre** [comment]
> Not sure: possibly need to rebuild my environment from scratch then 😬

Yeah you'll need to run `./bin/docker-dev-shell --rebuild` whenever the dockerfile changes, it'll take a while :(

**Comment by jurre** [comment]
By the way thanks for digging into this, really appreciate it!

**Comment by jurre** [comment]
A new version of composer came out in the meantime, I've made a few adjustments to the tests and they're passing for me locally:

https://github.com/dependabot/dependabot-core/pull/4611

Going to let CI run on that, get someone on my team to review it and then try to release + deploy a new version of dependabot tomorrow. I'll close this PR out for now, but thanks a bunch for the work so far!

**Comment by Ocramius** [comment]
@jurre awesome! Sorry I couldn't react earlier to this, but glad all is fine in the end 💪

**Pull request closed without merging**
