### PR TITLE
Add sig to dependency injection containers

### PR DESCRIPTION
**Pull request by JamieMagee**
Related to #7782

### CODE REVIEW

**Comment by Nishnha** [comment]
It might be a good idea to create a package_manager enum for type hinting? I don't think we have a canonical list in Dependabot Core outside of https://github.com/dependabot/dependabot-core/blob/1b6f1e4cdff6f6d8e2a9ab76d87cb16b20ecf55d/updater/lib/dependabot/updater.rb#L14-L31

**Review by jakecoffman — APPROVED** [review]
Looks good!

@Nishnha The updater only calls method on the base so I don't think that's necessary?

**Comment by JamieMagee** [comment]
I think a package manager enum is a good idea, but I'm focusing on adding `sig`s and less on general refactoring

**Review by Nishnha — APPROVED** [review]

**Comment by jakecoffman** [comment]
Starting to deploy this now.

**Pull request merged**
