### PR TITLE
Avoid using existing branches

### PR DESCRIPTION
**Pull request by Nishnha**
### What are you trying to accomplish?

Avoid using existing branch names.

### Anything you want to highlight for special attention from reviewers?

Receives a list of existing `dependabot/` branches from API, and uses that to determine if the branch name requires a suffix.

### How will you know you've accomplished your goal?

Dependabot will avoid opening a PR with an existing branch name and will instead append a suffix to the branch name.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Review by kbukum1 — APPROVED** [review]
LGTM

**Comment by Nishnha** [comment]
This was tested on staging and had some issues. 

I created a branch so that it would have the same name as a lodash bump Dependabot PR https://github.com/dsp-testing/dependabot-all-updates-test-staging/compare/main...dependabot/npm_and_yarn/lodash-4.17.21

Then I added the lodash package to main and ran a Dependabot update for npm:
https://github.com/dsp-testing/dependabot-all-updates-test-staging/actions/runs/10689578285/job/29631996579

The logs say lodash was updated, but the job page says Dependabot encountered an error while creating the PR 

Screenshot 2024-09-03 at 3 53 18 PM

So I'm going to abort deploying this to main. It's only been deployed to staging so far so it's okay if someone overwrites those changes.

**Comment by Nishnha** [comment]
Also no new sentry errors so we might have to pull the PR creation error info through splunk

**Comment by Nishnha** [comment]
I see this error in splunk : `log_message: Failed to create pull request: exception caught: unknown keyword: :existing_branches`

https://splunk.githubapp.com/en-US/app/gh_reference_app/search?q=search%20index%3Dcatchall%20878769050&earliest=-24h%40h&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=Standard&sid=1725393775.231699_298589E4-13B4-4DF5-B9F5-79D50DC5251B

**Pull request merged**
