### PR TITLE
fix k8s files with dot in their name are ignored

### PR DESCRIPTION
**Pull request by negrel**
Related to #7008

### CODE REVIEW

**Review by landongrindheim — APPROVED** [review]

**Comment by jeffwidman** [comment]
Could you add a test to ensure we don't regress in the future?

If you're not sure how let me know and I can find an example when I'm at my computer (on my phone right now)

**Comment by negrel** [comment]
Yes, it depends on the type of test you want. An example would be great!

**Comment by jeffwidman** [comment]
I suspect it's as simple as adding some additional test cases this array?

https://github.com/dependabot/dependabot-core/blob/a4556cf9956dc765930a75b707d8d877d9e5e215/docker/spec/dependabot/docker/file_fetcher_spec.rb#L272-L286

**Review by jeffwidman — CHANGES_REQUESTED** [review]
Marking as requested changes so it's clear form PR overview page that this is blocked on needing the test (which looks straightforward)

**Comment by jeffwidman** [comment]
@negrel @mctofu should this be closed now that https://github.com/dependabot/dependabot-core/pull/8862 is merged?

Looking at the diff, it looks like that PR has a superset of what's tested here.

**Comment by Nishnha** [comment]
> @negrel @mctofu should this be closed now that #8862 is merged?
> 
> Looking at the diff, it looks like that PR has a superset of what's tested here.

Looks like it. Thanks for the heads up!

**Comment by negrel** [comment]
LGTM

**Pull request closed without merging**
