### PR TITLE
Elixir: Handle regex versions in FileParser

### PR DESCRIPTION
**Pull request by greysteil**
That.

### CODE REVIEW

**Comment by greysteil** [comment]
@stevedomin / @bernardd - I fear I may have murdered several Elixirs during the writing of this. It works, but any chance one of you could give me a pointer on how to make it idiomatic?

**Comment by bernardd** [comment]
I'd be inclined to change this:

```elixir
   defp build_dependency(nil, dep) do
    req = if Regex.regex?(dep.requirement), do: Regex.source(dep.requirement), else: dep.requirement
    req = if byte_size(req) == 0, do: nil, else: req
```

to something more like this:

```elixir
  defp build_dependency(nil, %{requirement: requirement} = dep) do
    req = cond do
      Regex.regex?(requirement) -> Regex.source(requirement)
      "" -> nil
      true -> requirement
    end
```

I'm not sure you'd call it "idiomatic" as such, but it's a bit easier to read at least :)

**Comment by stevedomin** [comment]
@bernardd's new version looks great

**Comment by greysteil** [comment]
Awesome, thanks guys!

**Comment by greysteil** [comment]
@bernardd - FYI, I tailed the logs while Dependabot was updating your app and it looks like everything is working now. Let me know if those PRs aren't perfect, though!

**Pull request merged**
