### PR TITLE
Upgrade to PHP 7.4

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/dependabot/dependabot-core/issues/1730

### CODE REVIEW

**Comment by FabianKoestring** [comment]
👍 for merging this as soon as possible.

**Comment by FabianKoestring** [comment]
Is https://github.com/marketplace/dependabot-preview updated automatically or only this repository. 😕

**Comment by feelepxyz** [comment]
Yeah will be, we’re pushing a release out, will be out later today.

**Comment by FabianKoestring** [comment]
> Yeah will be, we’re pushing a release out, will be out later today.

Perfect! Thanks

**Comment by FabianKoestring** [comment]
> Yeah will be, we’re pushing a release out, will be out later today.

Will the dependabot-preview Service on Github always be the newest version of this repository?

**Comment by feelepxyz** [comment]
@FabianKoestring yeah should be but takes some time for all the tests and images to build. This should be out, still having issues?

**Comment by FabianKoestring** [comment]
> @FabianKoestring yeah should be but takes some time for all the tests and images to build. This should be out, still having issues?

No, just asking. Thanks

**Pull request merged**
