### PR TITLE
Added pnpm_9 support to dependabot.

### PR DESCRIPTION
**Pull request by thavaahariharangit**
### What are you trying to accomplish?

I have added support to pnpm 9 version

### Anything you want to highlight for special attention from reviewers?

Added packageManager property to package.json. This will not only enable the support for pnpm 9 but also for the future versions

### How will you know you've accomplished your goal?

wrote Junit test with appropriate fixtures. To prove provided solution works as expected

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
In general (and while I believe `packageManager`is a good thing), I believe Dependabot should not enforce any style on user's manifests. I believe the underlying issue here is some bug in cases when users do not specify the `packageManager` field in their `package.json` file, correct? If that's the case, I think we should instead try to address that bug.

**Comment by thavaahariharangit** [comment]
> In general (and while I believe `packageManager`is a good thing), I believe Dependabot should not enforce any style on user's manifests. I believe the underlying issue here is some bug in cases when users do not specify the `packageManager` field in their `package.json` file, correct? If that's the case, I think we should instead try to address that bug.

Hi @deivid-rodriguez this is not the bug, I am trying to implement this as a feature pnpm 9 support. This will set the pnpm version to package.json based on the pnpm version given in package-lock.json.

**Comment by deivid-rodriguez** [comment]
Reading the latest comments in https://github.com/dependabot/dependabot-core/issues/9684, it seems like adding `packageManager` is a workaround to fix that issue. The way I see it, this means enforcing workaround on everyone, but doesn't explain why the original bug happening.

Even if this is intentionally changed as a feature (I disagree, but it's Dependabot's team choice), I think it'd be good to dig into https://github.com/dependabot/dependabot-core/issues/9684 regardless. I can try have a look.

**Comment by deivid-rodriguez** [comment]
So I looked into it and fixing that bug "just" requires the default PNPM version run by Dependabot to be upgraded. That makes sense, since it explains why Dependabot works for people using `packageManager` (corepack will automatically download and use PNPM 9). I can create a PR updating PNPM to see what CI thinks.

**Comment by deivid-rodriguez** [comment]
I created https://github.com/dependabot/dependabot-core/pull/10073 explaining what's going on in #9684.

**Comment by honeyankit** [comment]
@thavaahariharangit We can close this PR, since the fix for the PNPM9 is deployed in the below PR:
https://github.com/dependabot/dependabot-core/pull/10073

**Pull request closed without merging**
