### PR TITLE
Strictly type `BranchNamer::Base`

### PR DESCRIPTION
**Pull request by JamieMagee**
This can be marked as `strong` once https://github.com/sorbet/sorbet/pull/7523 is merged.

### CODE REVIEW

**Review by jakecoffman — APPROVED** [review]

**Comment by jakecoffman** [comment]
@JamieMagee merged main and it broke!

**Comment by jakecoffman** [comment]
Fixed here: https://github.com/dependabot/dependabot-core/pull/8649

**Review by jakecoffman — APPROVED** [review]

**Comment by JamieMagee** [comment]
That was a rollercoaster of emotions! Thank you for finding and fixing the issue.

**Comment by jakecoffman** [comment]
Software Development can be exciting! 🎢

**Pull request merged**
