### PR TITLE
Bundler: Bump bundler from 2.3.18 to 2.3.19

### PR DESCRIPTION
**Pull request by jurre**
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2319-july-27-2022

### CODE REVIEW

**Comment by jeffwidman** [comment]
@jurre would it make sense to first merge https://github.com/dependabot/dependabot-core/pull/4973 and then do this?

Either way there will be merge conflicts, and they'd be a lot easier to deal with here since it would become a one-line change vs there it'd be a multi-line fixup.

**Comment by deivid-rodriguez** [comment]
Regardless of which one is merged first, there seems to be a problem with the latest Bundler that makes one spec fail... 🤔. I'll have a look.

**Comment by deivid-rodriguez** [comment]
Issue bisected and working on a fix now 👍.

**Comment by jurre** [comment]
Going to close this out because of https://github.com/dependabot/dependabot-core/pull/5479 for now

**Comment by deivid-rodriguez** [comment]
Great! The regression in 2.3.19 should be fixed by https://github.com/rubygems/rubygems/pull/5812, so it should be all good for Bundler 2.3.20 when it's released.

**Pull request closed without merging**
