### PR TITLE
Enhancement: Use job matrix

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses a job matrix

Follows #2363.

### CODE REVIEW

**Comment by localheinz** [comment]
@feelepxyz @jurre 

Looks like the jobs aren't running - see #2373 (and all other pull requests rebased on current `main`).

**Comment by localheinz** [comment]
Closing in favor of #2375.

**Comment by jurre** [comment]
Thanks for this improvement @localheinz was easier to pull your commit into my branch to get it to build but appreciate your work a lot 💯

**Comment by localheinz** [comment]
@jurre 

You are much welcome!

👍

**Pull request closed without merging**
