### PR TITLE
Reparse dependencies after each batch when performing grouped updates

### PR DESCRIPTION
**Pull request by Nishnha**
Fixes https://github.com/dependabot/dependabot-core/issues/7238

This PR attempts to address the root cause of npm transitive dependencies generating `NoChangeErrors` during grouped updates.

Here's the error we're seeing:

```
2023/05/05 11:49:01 INFO Checking if @typescript-eslint/typescript-estree 5.27.1 needs updating
2023/05/05 11:49:02 INFO Latest version is 5.59.2
2023/05/05 11:49:03 INFO Requirements to unlock own
2023/05/05 11:49:03 INFO Requirements update strategy widen_ranges
2023/05/05 11:49:03 INFO Updating @typescript-eslint/typescript-estree from 5.27.1 to 5.59.1
2023/05/05 11:49:03 ERROR Error processing @typescript-eslint/typescript-estree (Dependabot::NpmAndYarn::FileUpdater::GroupedSubDependencyUpToDate)
2023/05/05 11:49:03 ERROR Subdependency is already up-to-date
2023/05/05 11:49:03 ERROR /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:59:in `updated_dependency_files'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:85:in `generate_dependency_files'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:36:in `run'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:25:in `create_from'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:70:in `create_change_for'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:33:in `block in compile_all_dependency_changes_for'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:23:in `each'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:23:in `compile_all_dependency_changes_for'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:78:in `block in run_grouped_dependency_updates'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:75:in `each'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:75:in `run_grouped_dependency_updates'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:43:in `perform'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
2023/05/05 11:49:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
2023/05/05 11:49:03 ERROR bin/update_files.rb:23:in `<main>'
```

Compare updates for the same groups for when we re-parse dependencies after each update in a grouped update PR:

```
+------------------------------------------------------------------------------------------------------------------------------------+
|                                                Changes to Dependabot Pull Requests                                                 |
+---------+--------------------------------------------------------------------------------------------------------------------------+
| created | fetch-factory ( from 0.0.1 to 0.2.1 )                                                                                    |
| created | babel-jest ( from 28.1.1 to 29.5.0 )                                                                                     |
| created | babel-jest ( from 28.1.1 to 29.5.0 ), diff-sequences ( from 28.1.1 to 29.4.3 ), eslint-plugin-jest ( from 26.5.3 to 2... |
| created | eslint-plugin-jest ( from 26.5.3 to 27.2.1 )                                                                             |
| created | @types/node ( from 18.16.2 to 20.1.0 )                                                                                   |
| created | caniuse-lite ( from 1.0.30001481 to 1.0.30001486 )                                                                       |
| created | core-js-compat ( from 3.30.1 to 3.30.2 )                                                                                 |
| created | electron-to-chromium ( from 1.4.377 to 1.4.385 )                                                                         |
| created | espree ( from 9.5.1 to 9.5.2 )                                                                                           |
+---------+--------------------------------------------------------------------------------------------------------------------------+
```

versus when we don't:

```
+------------------------------------------------------------------------------------------------------------------------------------+
|                                                Changes to Dependabot Pull Requests                                                 |
+---------+--------------------------------------------------------------------------------------------------------------------------+
| created | fetch-factory ( from 0.0.1 to 0.2.1 )                                                                                    |
| created | babel-jest ( from 28.1.1 to 29.5.0 ), @babel/compat-data ( from 7.21.4 to 7.21.7 ), @babel/generator ( from 7.21.4 to... |
| created | babel-jest ( from 28.1.1 to 29.5.0 ), diff-sequences ( from 28.1.1 to 29.4.3 ), eslint-plugin-jest ( from 26.5.3 to 2... |
| created | eslint-plugin-jest ( from 26.5.3 to 27.2.1 )                                                                             |
| created | @types/node ( from 18.16.2 to 18.16.3 )                                                                                  |
| created | caniuse-lite ( from 1.0.30001481 to 1.0.30001482 )                                                                       |
| created | electron-to-chromium ( from 1.4.377 to 1.4.382 )                                                                         |
+---------+--------------------------------------------------------------------------------------------------------------------------+
Dependabot encountered '7' error(s) during execution, please check the logs for more details.
+------------------------------------------------------+
|            Dependencies failed to update             |
+--------------------------------------+---------------+
| babel-plugin-polyfill-corejs3        | unknown_error |
| @typescript-eslint/scope-manager     | unknown_error |
| @typescript-eslint/types             | unknown_error |
| @typescript-eslint/typescript-estree | unknown_error |
| @typescript-eslint/utils             | unknown_error |
| @typescript-eslint/visitor-keys      | unknown_error |
| @typescript-eslint/type-utils        | unknown_error |
+--------------------------------------+---------------+
```

(there are some extra dependencies that show up but that is because they have recent updates)

### CODE REVIEW

**Comment by Nishnha** [comment]
I also noticed re-parsing dependencies changes the `requirements to unlock`

In the case of `@typescript-eslint/typescript-estree`, the requirements changed from `:own` to `:update_not_possible`

```
2023/05/10 09:06:40 INFO Checking if @typescript-eslint/typescript-estree 5.59.1 needs updating
2023/05/10 09:06:44 INFO Latest version is 5.59.5
2023/05/10 09:06:48 INFO Requirements to unlock update_not_possible
2023/05/10 09:06:48 INFO Requirements update strategy widen_ranges
2023/05/10 09:06:48 INFO No update possible for @typescript-eslint/typescript-estree 5.59.1
```

I do believe the `:update_not_possible` requirement is correct since the Dependency version is locked by a parent dependency (which has already been updated to its latest version!)

**Comment by Nishnha** [comment]
Another thing that was suggested was, instead of re-parsing all of the dependencies from the updated dependency files, we can check whether the dependency being updated is in the `all_updated_dependencies` list.

While this should work for dependencies being updated, transitive dependencies that are removed would not appear in the `all_updated_dependencies` list.

Also, I think the re-parsing approach means we don't have to worry about additional edge cases from other package managers

**Comment by deivid-rodriguez** [comment]
To clarify what I mean with that last suggestion, my understanding is that after each step, we get an `updated_dependencies` array that we aggregate on to `all_updated_dependencies`. An if a transitive dependency gets removed, it would still show up in `updated_dependencies`, just with the `#removed?` attribute set. So I think it'd be possible to properly keep `all_updated_dependencies` up to date and accurate.

That said, your approach is perfectly valid too, but I'd add a note about `all_updated_dependencies` not being fully reliable in that case?

**Comment by deivid-rodriguez** [comment]
I just saw this comment:

> # FIXME: all_updated_dependencies may need to be de-duped

which actually addresses my concern. Yes, I think it'd needed deduping but also in a way, that last dependency added stays, so that if a transitive dependency is bumped, and then removed, it shows as removed in the final result.

**Comment by brrygrdn** [comment]
> I just saw this comment:
>
>> FIXME: all_updated_dependencies may need to be de-duped
>
>which actually addresses my concern. Yes, I think it'd needed deduping but also in a way, that last dependency added stays, so that if a transitive dependency is bumped, and then removed, it shows as removed in the final result.

I was thinking combining this with [a todo from my last PR](https://github.com/dependabot/dependabot-core/blob/8a8aeaacfd0ab0b372a4f4c35d1075578bd032a6/updater/lib/dependabot/updater/group_update_creation.rb#L23-L26) to take a similar approach to managing the running dependency list.

But I was just thinking that rather maintain a running list we could do a final reparse of the updated dependency files and compare it to the original dependency list to work out what changed once at the last?

**Review by brrygrdn — APPROVED** [review]
As discussed on the thread, I think we still have another pass at dependency de-duping to be done, but this definitely remediates the problem of dependencies being removed and throwing errors in subsequent steps, so let :shipit:

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Pull request merged**
