### PR TITLE
Maven, Gradle: Special case display name for undescriptive artifact IDs

### PR DESCRIPTION
**Pull request by greysteil**
Fixes https://github.com/dependabot/feedback/issues/513.

### CODE REVIEW

**Comment by greysteil** [comment]
@TylerCarberry, @RohanNagar - any others you've seen?

**Comment by RohanNagar** [comment]
That's the only one I've seen myself, thanks for the quick fix!

**Comment by TylerCarberry** [comment]
Same, only one

**Comment by honnix** [comment]
What is the reason we don't take the full string as `groupId:artifactId`? For Maven and Gradle the combination is unique, otherwise it may be confusing? Is it intended to make the PR title shorter?

**Pull request merged**
