### PR TITLE
NuGet `FileUpdater.only_deleted_lines?` should ignore white-space lines

### LINKED ISSUE #10323: Updates to dotnet-tools.json with white-space lines cause "Passed `nil` into T.must" errors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

v0.267.0

### Language version

_No response_

### Manifest location and content before the Dependabot update

https://github.com/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/blob/main/DotNetTools/.config/dotnet-tools.json

### dependabot.yml content

N/A, updated using dry-run.rb

### Updated dependency

dotnet-ef from 7.0.8 to 8.0.7

### What you expected to see, versus what you actually saw

**Expected:**
dotnet-ef should be updated to 8.0.7 in dotnet-tools.json.

**Actual:**
Error is thrown, dependency is not updated.
```log
=== dotnet-ef (7.0.8)
 => checking for updates 2/2
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/0.0.1-alpha/3.1.28.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/0.0.1-alpha/3.1.28.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/3.1.29/6.0.23.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/3.1.29/6.0.23.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/6.0.24/9.0.0-preview.6.24327.4.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/6.0.24/9.0.0-preview.6.24327.4.json
I, [2024-07-31T11:39:30.550657 #4598]  INFO -- : Filtered out 59 pre-release versions
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/7.0.8/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/7.0.8/dotnet-ef.nuspec
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
 => latest available version is 8.0.7
 => latest allowed version is 7.0.8
 => requirements to unlock: all
 => requirements update strategy: 
Finding updated dependencies for dotnet-ef.
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test --solution-or-project /home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj --dependency dotnet-ef --new-version 8.0.7 --previous-version 7.0.8 --result-output-path /tmp/update-result.json --verbose
  Updating [DotNetTools/.config/dotnet-tools.json] file.
    Saved [DotNetTools/.config/dotnet-tools.json].
  No global.json file found.
Running for project file [DotNetTools/CaseManagement/Common/Common.csproj]
Updating project [/home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj]
  Running for SDK-style project
    Package [dotnet-ef] Does not exist as a dependency in [/home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj].
Update complete.
  Writing update result to [/tmp/update-result.json].
I, [2024-07-31T11:39:33.925840 #4598]  INFO -- : update result: {
  "ErrorType": null,
  "ErrorDetails": null
}
Fixing mismatched Windows line endings for [.config/dotnet-tools.json].
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)

      raise TypeError.new("Passed `nil` into T.must")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:174:in `message'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from bin/dry-run.rb:728:in `block in <main>'
        from bin/dry-run.rb:620:in `each'
        from bin/dry-run.rb:620:in `<main>'
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

Repo:
https://github.com/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/tree/main/DotNetTools

Dry run command:
```bash
bin/dry-run.rb nuget rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test --dir="/DotNetTools"
```

### PR DESCRIPTION
**Pull request by rhyskoedijk**
### What are you trying to accomplish?

See https://github.com/dependabot/dependabot-core/issues/10323#issuecomment-2260360100 for what has changed and why.
Fixes #10323.

### Anything you want to highlight for special attention from reviewers?

N/A

### How will you know you've accomplished your goal?

The following update works without any errors
```bash
bin/dry-run.rb nuget rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test --dir="/DotNetTools"
```

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by abdulapopoola** [comment]
Thank you so much @rhyskoedijk , could you please add a test to ensure this scenario doesn't regress silently in the future?

**Comment by rhyskoedijk** [comment]
@abdulapopoola tests added

**Comment by brettfo** [comment]
@rhyskoedijk Funny enough this PR actually fixes an issue I was investigating earlier today.

I've been thinking about it and I think we can simplify the testing quite a bit by making the `only_deleted_lines?` method shared/static and public; that way it can be tested directly instead of going through the whole process.  I'm happy to help with that aspect if you'd like; I'm fairly new to Ruby, but I'm comfortable with it in this repo, particularly the unit testing.

**Comment by rhyskoedijk** [comment]
> I'm happy to help with that aspect if you'd like;

Feel free, please. I'm also pretty new to Ruby so help on the tests would be appreicated.

**Comment by brettfo** [comment]
> > I'm happy to help with that aspect if you'd like;
> 
> Feel free, please. I'm also pretty new to Ruby so help on the tests would be appreicated.

Sure thing, I'll start on that now.  Assuming I have access, I'll push commits to your branch.  If I don't have access I'll create a new PR.  ETA, 2 hours or so.

**Comment by brettfo** [comment]
> > I'm happy to help with that aspect if you'd like;
> 
> Feel free, please. I'm also pretty new to Ruby so help on the tests would be appreicated.

I didn't have permissions, so I created a new PR here (#10332) with the original commit history.

@rhyskoedijk I had to change the inner function a bit, so I'd appreciate if you could take a look and make sure I got it right, including the test cases.

And thank you again for identifying the issue and figuring out the proper fix.

**Comment by rhyskoedijk** [comment]
Superseded by #10332

**Pull request closed without merging**
