### PR TITLE
grouped security updates

### PR DESCRIPTION
**Pull request by jakecoffman**
This is a grouped security updates prototype.

It detects a group by seeing multiple dependencies are passed into a security update job. Then it creates a grouping on-the-fly to generate a single PR instead of the usual multiple PRs. 

This is a feature in development, so there's no way to exercise it without flags set in the service.

### CODE REVIEW

**Review by jurre — APPROVED** [review]
Approving this so I can deploy it to staging

@jakecoffman could be nice to throw some feature flag checks in here so we could deploy it to prod if we wanted?

**Comment by jakecoffman** [comment]
I can do that. I was wondering if it was necessary though? If a security job can only come through with a single dependency specified in the job then I think we're good without a feature flag.

**Comment by jurre** [comment]
> I can do that. I was wondering if it was necessary though? If a security job can only come through with a single dependency specified in the job then I think we're good without a feature flag.

Yeah that's fair!

**Comment by jakecoffman** [comment]
I queried all update jobs and verified security jobs never have more than one dependency. So this shouldn't interfere with existing logic, and doesn't need a feature flag.

**Review by jurre — APPROVED** [review]

**Pull request merged**
