### PR TITLE
Elixir version upgrades

### PR DESCRIPTION
**Pull request by baseballlover723**
updates for

- Erlang deb package: 1.0 -> 2.0
- Elixir: 1.11.4 -> 1.12.2
- Erlang: 23.3.1 -> 24.0.4

### CODE REVIEW

**Review by Nishnha — APPROVED** [review]
LGTM 👍🏾

**Comment by jurre** [comment]
I think @mctofu and I actually ran into some certificate errors when running this in production

**Comment by Nishnha** [comment]
@baseballlover723 Thank you for your contribution!

Newer versions of Elixir are causing issues with the way we run Dependabot in production. For this reason we've pinned it to the latest working version. Unfortunately we have to avoid upgrading Elixir at the moment.

Closing the PR.

**Comment by jurre** [comment]
FYI we're having issues with the OTP version, so that needs to stay at 23, I think the rest of this should be safe to update.

I'm documenting the pinned version for future reference: https://github.com/dependabot/dependabot-core/pull/4092

**Pull request merged**
