### PR TITLE
Pip compile fix

### PR DESCRIPTION
**Pull request by JimNero009**
Changes the behaviour of the pip-compile command when updating dependencies to respect any 'ignored_versions' passed to dependabot.

### CODE REVIEW

**Comment by JimNero009** [comment]
I'm not sure that would work? Since we need to shell out to pip-compile to do the heavy lifting, it is that call that needs context on what versions are and are not allowed. So if I have a requirement like '>4,<6' in my ignored_versions, then somewhere down the line we will have to convert that to '<=4, >=6' to this call anyway? Or am I misunderstanding the suggestion?

**Comment by jeffwidman** [comment]
👋 Hey there, sorry for the again slow followup. The team has been buried the last few years with the acquisition of Dependabot and then scaling up to match GitHub scale. But we're starting to have a few spare cycles to go through the backlog.

Before I spend any time reviewing this, I wanted to first check is it still a feature you're interested in working on? If so, do you mind fixing the emerge conflicts?

**Comment by JimNero009** [comment]
Things have moved on for me, sadly, and I can't in good conscience say I will get back to this in any reasonable time frame. Stepping aside for another member of the awesome community.

**Comment by jeffwidman** [comment]
Thanks Jim for the prompt response. At least we got https://github.com/dependabot/dependabot-core/pull/1463 merged for you.

**Pull request closed without merging**
