### PR TITLE
Update Swift Dockerfile to use Swift 6.0.1

### PR DESCRIPTION
**Pull request by tonyarnold**
### What are you trying to accomplish?

The Swift Project has recently released Swift 6.0, and I would like Dependabot to continue working with my projects once I have updated them to this language version.

### How will you know you've accomplished your goal?

Dependabot will be able to interact with Swift packages using the Swift 6.0 tools.

### CODE REVIEW

**Comment by jurre** [comment]
Thanks @tonyarnold! Do you happen to know if this version is backwards compatible? The tests are passing so I'd assume so, but I've been out of the Swift game for a bit now so figured I'd check with you.

**Comment by tonyarnold** [comment]
To a point, yes. How do other language support modules handle major version updates?

**Comment by jurre** [comment]
It depends a little bit on the ecosystem/language tbh, in some cases we have some workarounds to make versions backwards compatible, in exceptional cases we have first class support for multiple versions. In _most_ cases things are backwards compatible enough to work in most cases and/or upgrading is easy enough for customers

**Comment by tonyarnold** [comment]
My understanding is that Swift 6.0 can interact with Swift Packages that specify older tools versions via `// swift-tools-version:5.10` and similar, so this _should_ be safe to move forward with.

**Comment by StuClift** [comment]
Is there something the community can do to get this over the line?

**Comment by ffried** [comment]
This would also fix #10754

**Review by abdulapopoola — APPROVED** [review]

**Pull request merged**
