### PR TITLE
Treat `-pre` version suffix as prerelease.

### PR DESCRIPTION
**Pull request by dbrant**
### What are you trying to accomplish?

Certain projects release packages with pre-release versions that have a suffix of `-pre`_N_, which doesn't seem to get caught by dependabot as a prerelease, and gets submitted in a pull request as a stable package.

example prerelease:
https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.2-pre0

example erroneous pull request:
https://github.com/wikimedia/apps-android-wikipedia/pull/4806

### CODE REVIEW

**Comment by abdulapopoola** [comment]
Thanks a lot @dbrant , could you please add a test and we can get this over the line :)

**Comment by dbrant** [comment]
> Thanks a lot @dbrant , could you please add a test and we can get this over the line :)

whoops, of course -- how about now?

**Review by abdulapopoola — APPROVED** [review]

**Comment by abdulapopoola** [comment]
Merged and deployed! Thanks @dbrant !!

**Comment by deivid-rodriguez** [comment]
For what it's worth, we discussed this in the past at https://github.com/dependabot/dependabot-core/pull/6747 and decided not to deviate from what `maven` documents at https://maven.apache.org/pom.html#Version_Order_Specification. And `-pre` is not mentioned at all in there.

Funny enough, when we rejected adding "-preview", I actually mentioned "-pre" explicitly:

> That said, I also feel package authors should stick to what their package manager supports, and not use their own versioning. Because now if another package author decides to name their prerelease versions as "pre", then we'll need to support that and when that stops?

**Comment by deivid-rodriguez** [comment]
Well, it was not really a [clear decision](https://github.com/dependabot/dependabot-core/pull/6747#issuecomment-1450002942), I totally understand taking the pragmatic approach over the correct, consistent one. Just saying that if we decide to do this, we may also want to reopen #6747.

**Comment by dbrant** [comment]
@jonjanego Thanks for the note, and no worries -- it looks like we'll need to convince the MapLibre developers to adopt more standard prerelease versions instead.

**Comment by sultan** [comment]
The Dependabot team has decided to align strictly with Maven qualifiers:
* https://github.com/dependabot/dependabot-core/discussions/10626

This alignment makes sense for consistency across tools. Yet recurring issues show that Maven’s current handling of qualifiers is incomplete, impacting multiple companies and users:
* https://github.com/apache/maven/issues/8891
* https://github.com/dependabot/dependabot-core/pull/6747
* https://github.com/dependabot/dependabot-core/pull/10207

These issues need to be addressed upstream in Maven Resolver. I am working to encourage Maven to adopt a fix through this PR:
* https://github.com/apache/maven-resolver/pull/1683

The voice of users and teams such as Dependabot can strongly influence Maven’s willingness to integrate this into Maven 4.

Proposed ordering:
* alpha < beta < milestone < pr = pre = preview < rc = cr < dev < snapshot < final = ga = release < sp

I edited the documentation to discourage the use of certain qualifiers:
* The use of pr, pre, preview is discouraged
* The use of cr is discouraged (use rc instead)
* The use of dev is discouraged
* The use of final, ga, release is discouraged (use no qualifier instead)
* The use of sp is discouraged (increment patch version instead)

As long as discouraged qualifiers continue to be used in practice, tools will still need to support them. Once they are phased out, however, support can be safely dropped.

Optional inclusions:
* ea (early access), edr, pfd (drafts), mr

Target PR to support:
* https://github.com/apache/maven-resolver/pull/1683

Supporting this upstream effort helps turn recurring patches into a durable solution for the ecosystem. You can help by adding your voice on the Maven Resolver PR — for example, by sharing which qualifiers affect your projects, or by confirming that consistent ordering would reduce the need for local workarounds. Demonstrating real impact from tools like Dependabot makes it harder for Maven to ignore these changes.

Thanks for your input.

**Pull request merged**
