### PR TITLE
Fix crash when updating sha-pinned images with no "latest" tag

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
If there's no latest tag, we can't update sha pinned images since we don't know which SHA is the latest.

Previously Dependabot would show the error "Pull request already exists for library/alpine-3 with latest version latest" even if that wasn't the case.

```
updater | 2023/08/29 00:21:53 INFO <job_714994438> Checking if library/alpine-3 latest needs updating
updater | 2023/08/29 00:21:53 INFO <job_714994438> Latest version is latest
  proxy | 2023/08/29 00:21:53 [018] HEAD https://registry.opensource.zalan.do:443/v2/library/alpine-3/manifests/latest
  proxy | 2023/08/29 00:21:53 [018] 200 https://registry.opensource.zalan.do:443/v2/library/alpine-3/manifests/latest
updater | 2023/08/29 00:21:53 INFO <job_714994438> Pull request already exists for library/alpine-3 with latest version latest
```

Fixes (part of) #7387.

### CODE REVIEW

**Review by Nishnha — APPROVED** [review]

**Comment by janschill** [comment]
Ran into this issue as well. Anything stopping this from getting merged?

**Comment by abdulapopoola** [comment]
@deivid-rodriguez is this deployable?

**Comment by abdulapopoola** [comment]
@janschill this is now deployed

**Comment by deivid-rodriguez** [comment]
Honestly I don't recall, but I believe while a harmless change, it did not fix the original issue reported in #7387, that's why I had not merged it.

**Pull request merged**
