### PR TITLE
Fix `lockfile-only` versioning strategy not creating some updates that are expected (v2)

### LINKED ISSUE #5569: Dependabot cannot update two top-level bundler dependencies with an equality version constraint between them
**Package ecosystem**
Bundler
**Package manager version**
Both v1 and v2
**Manifest location and content before the Dependabot update**
Gemfile: https://github.com/Bo98/dependabot-sorbet-test/blob/main/Gemfile

```rb
source "https://rubygems.org"

gem "sorbet-runtime"

group :development, optional: true do
  gem "sorbet-static-and-runtime"
end
```

Gemfile.lock: https://github.com/Bo98/dependabot-sorbet-test/blob/main/Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.10175)
      sorbet-static (= 0.5.10175)
    sorbet-runtime (0.5.10175)
    sorbet-static (0.5.10175-universal-darwin-14)
    sorbet-static-and-runtime (0.5.10175)
      sorbet (= 0.5.10175)
      sorbet-runtime (= 0.5.10175)

PLATFORMS
  ruby

DEPENDENCIES
  sorbet-runtime
  sorbet-static-and-runtime
```

**dependabot.yml content**
https://github.com/Bo98/dependabot-sorbet-test/blob/main/.github/dependabot.yml
**Updated dependency**
sorbet-runtime and sorbet-static-and-runtime to latest (0.5.10346 at time of writing)
**What you expected to see, versus what you actually saw**
Expected: Both sorbet-runtime and sorbet-static-and-runtime is updated.
Actual: Neither is updated.
**Native package manager behavior**
Bundler v1 has an odd warning but otherwise works (nothing was removed like it claims):

```
$ bundle update sorbet-runtime sorbet-static-and-runtime --conservative
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies........
Using bundler 1.17.3
Using sorbet-runtime 0.5.10346 (was 0.5.10175)
Bundler attempted to update sorbet-static-and-runtime but it was removed from the bundle
Bundle updated!
```

Bundler v2 only works without `--conservative`:

```
$ bundle update sorbet-runtime sorbet-static-and-runtime --conservative
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.11
Using sorbet-runtime 0.5.10175
Bundler attempted to update sorbet-runtime but its version stayed the same
Bundle updated!

$ bundle update sorbet-runtime sorbet-static-and-runtime
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.11
Using sorbet-runtime 0.5.10346 (was 0.5.10175)
Bundle updated!
```

---

I suspect the answer here is that this scenario is unsupported, given each top-level dependency has its own policies such as version ignore ranges which probably complicates trying to support scenarios like this. Though given this pattern will start to gain popularity (`sorbet-static-and-runtime` did not exist a few months ago), I thought it's worth at least documenting in an issue.

### LINKED ISSUE #5890: non-sense dependency updates
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

1

### Language version

Nodejs 14

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```yaml
version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.GH_PACKAGES_RW_SECRET }}

updates:
  - package-ecosystem: 'npm' 
    directory: '/' 
    registries:
      - npm-github
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - 'dependencies'
      - 'untracked work'
    commit-message:
      prefix: 'chore'
      include: 'scope'
 ```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

PR title:
```
chore(deps): bump dd-trace from 0.31.4 to 3.5.0
```

yarn.lock changes:
```diff
lru-cache@^7.10.1:
-  version "7.10.1"
-  resolved "https://registry.yarnpkg.com/lru-cache/-/lru-cache-7.10.1.tgz#db577f42a94c168f676b638d15da8fb073448cab"
-  integrity sha512-BQuhQxPuRl79J5zSXRP+uNzPOyZw2oFI9JLRQ80XswSvg21KMKNtQza9eF42rfI/3Z40RvzBdXgziEkudzjo8A==
+  version "7.14.0"
+  resolved "https://registry.yarnpkg.com/lru-cache/-/lru-cache-7.14.0.tgz#21be64954a4680e303a09e9468f880b98a0b3c7f"
+  integrity sha512-EIRtP1GrSJny0dqb50QXRUNBxHJhcpxHC++M5tD7RYbvLLn5KVWKsbyswSSqDuU15UFi3bgTQIY8nhDMeF6aDQ==
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

image
image
image

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #5892: Incorrect bundler updates after #5581
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.3.5

### Language version

2.7.6

### Manifest location and content before the Dependabot update

/Gemfile

excerpt:
```
gem 'oj', '3.13.14'
gem 'sassc', '2.0.1', require: false
gem 'active_model_serializers', '~> 0.8.3'
```

### dependabot.yml content

excerpt:

```yml
- package-ecosystem: bundler
  versioning-strategy: lockfile-only
  allow:
    - dependency-type: direct
    - dependency-type: indirect
```

### Updated dependency

`sassc` updated from the locked version (2.0.1) to 2.4.0 https://github.com/discourse/discourse/pull/18617
`oj` updated from the locked version (3.13.14) to 3.13.21 https://github.com/discourse/discourse/pull/18614
`active_model_serializers` updated from the locked version (~> 0.8.3 that resolved to 0.8.4) to 0.10.13 https://github.com/discourse/discourse/pull/18610

### What you expected to see, versus what you actually saw

Before that PR (#5581) Dependabot was correctly ignoring those dependencies. The PRs it now creates update the lockfile versions agains what's in the Gemfile.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Trying to retry #5581, but in a correct way now.

Fixes #5569.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This PR is now rebased and green again 🎉.

Still left to do is the verify that both the original problem and the regression that motivated the original revert no longer happen with this PR.

**Comment by deivid-rodriguez** [comment]
I verified that #5569 is still happening, and that this PR is still fixing it. And also that this PR does not reintroduce https://github.com/dependabot/dependabot-core/issues/5892.

So setting this as ready!

**Comment by deivid-rodriguez** [comment]
I extracted one change to [a separate PR](https://github.com/dependabot/dependabot-core/pull/7109) so this should be a bit more digestible now.

**Review by jeffwidman — APPROVED** [review]
This looks 👍 to me, with the caveat that it touches a lot of code and I didn't spend time to deeply investigate every bit.

But what I can see makes sense, and there's reasonable CI around it, so I think we should 🚢 and if anything comes up we can course correct as needed.

**Pull request merged**
