### PR TITLE
[minor] Fix typo in Azure client - Availaible -> Available

### PR DESCRIPTION
**Pull request by GiriB**
A typo went undetected in #2908 :(

### CODE REVIEW

**Review by jurre — APPROVED** [review]
😄 totally missed this in the review

**Comment by jurre** [comment]
Any idea why all the specs are failing? 🤔

**Comment by GiriB** [comment]
@jurre Nope. :( Most of the breaks are unrelated to the change. Could it be a transient issue? Is there a way to re-run the specs?

**Comment by GiriB** [comment]
@jurre Is `main` broken? See this PR - #2911 . I created a PR with a dummy text file and the still the CI checks are failing. 

Also, unrelated to this, I saw that my earlier PR was not squashed merge, which I think it should have.
image

**Comment by jurre** [comment]
> Could it be a transient issue? Is there a way to re-run the specs? 

I've already tried to a few times, doesn't seem to do the trick.

> @jurre Is main broken? See this PR - #2911 . I created a PR with a dummy text file and the still the CI checks are failing.

It might be an issue with CI and forks, double checking..

> Also, unrelated to this, I saw that my earlier PR was not squashed merge, which I think it should have.

We typically don't squash merge, I personally try to squash commits before requesting a review so the commits make sense

**Comment by jurre** [comment]
Something definitely seems up with our CI, going to look into it

**Comment by jurre** [comment]
@GiriB if you rebase the suite should pass 🤞

**Comment by GiriB** [comment]
@jurre Done!

**Pull request merged**
