### PR TITLE
Bump yarn to 4.5.3

### PR DESCRIPTION
**Pull request by jeffwidman**
### What are you trying to accomplish?

I'm debugging in this area, and want to make sure I'm working off the latest upstream changes.

### CODE REVIEW

**Comment by yeikel** [comment]
Closes https://github.com/dependabot/dependabot-core/pull/8265

**Comment by jeffwidman** [comment]
This is the failing test: 

https://github.com/dependabot/dependabot-core/blob/8f037cf1be97f2a0c1f383d74479ebe2a48e0c17/npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb#L855-L871

Full commit including lockfiles: https://github.com/dependabot/dependabot-core/commit/1dcda58569f95d079d3b239876a12f10205406a3

Interestingly, it doesn't fail in Yarn `4.3.1` as seen in:
* https://github.com/dependabot/dependabot-core/pull/8265

Poking through the changelog between 4.3.1 and 4.5.3, this seems to be relevant upstream PR:
* https://github.com/yarnpkg/berry/pull/6517

My understanding of peer dependency handling in Yarn is hazy at best, but after reading the PR description, it _looks_ like the algorithm changed and now the peer dependency can be updated and not necessarily held back. 

That would explain this test failure:
https://github.com/dependabot/dependabot-core/actions/runs/12307737164/job/34351931150?pr=11123#step:5:56

**Comment by jeffwidman** [comment]
@yeikel does ☝️ sound reasonable to you? I am not very familiar with Yarn Berry or peer dependencies in the yarn ecosystem...

**Review by yeikel — COMMENTED** [review]
> @yeikel does ☝️ sound reasonable to you? I am not very familiar with Yarn Berry or peer dependencies in the yarn ecosystem...

Yes it does. Your analysis seems correct to me.

**Review by pavera — APPROVED** [review]

**Pull request merged**
