### PR TITLE
chore(python): target latest python 3.12.5 version

### PR DESCRIPTION
**Pull request by Greesb**
Closes https://github.com/dependabot/dependabot-core/issues/10469

### CODE REVIEW

**Comment by kbukum1** [comment]
Can you update the PR according to the followings? 

- Python: We can't approve this version `3.12.5` since according to the official website, https://www.python.org/doc/versions  the stable version is still `3.12.4`
- Poetry: We can approve the version to latest stable version since the stable version is `1.8.3`  according to the https://pypi.org/project/poetry/

**Review by kbukum1 — COMMENTED** [review]
@Greesb , 
Can you update the PR according to the followings? 

- Python: We can't approve this version `3.12.5` since according to the official website, https://www.python.org/doc/versions  the stable version is still `3.12.4`
- Poetry: We can approve the version to latest stable version, `1.8.3`  according to the https://pypi.org/project/poetry/

**Comment by Greesb** [comment]
> @Greesb , 
> Can you update the PR according to the followings? 
> 
> - Python: We can't approve this version `3.12.5` since according to the official website, https://www.python.org/doc/versions  the stable version is still `3.12.4`
> - Poetry: We can approve the version to latest stable version, `1.8.3`  according to the https://pypi.org/project/poetry/

@kbukum1 I'm not sure using https://www.python.org/doc/versions as a reference for the latest stable python version is valid.
https://docs.python.org/3/ references the doc of python 3.12.5, and the links in the sidebar of the same site to `python 3.12 (stable)` also sends to the python 3.12.5 version.

The 3.12 version as a whole is stable, the `.4` or `.5` should not matter afaik.

**Comment by kbukum1** [comment]
> > @Greesb ,
> > Can you update the PR according to the followings?
> > 
> > * Python: We can't approve this version `3.12.5` since according to the official website, https://www.python.org/doc/versions  the stable version is still `3.12.4`
> > * Poetry: We can approve the version to latest stable version, `1.8.3`  according to the https://pypi.org/project/poetry/
> 
> @kbukum1 I'm not sure using https://www.python.org/doc/versions as a reference for the latest stable python version is valid. https://docs.python.org/3/ references the doc of python 3.12.5, and the links in the sidebar of the same site to `python 3.12 (stable)` also sends to the python 3.12.5 version.
> 
> The 3.12 version as a whole is stable, the `.4` or `.5` should not matter afaik.

Thank you @Greesb for the information. After checking the doc I found that python versions page is not up-to-date. Also created an issue for the document. 

I am going to approve this PR.

**Review by kbukum1 — APPROVED** [review]
LGTM

**Pull request merged**
