### PR TITLE
Bundler: update bundler to 2.2.33

### PR DESCRIPTION
**Pull request by jurre**
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2233-december-7-2021

Includes a security fix around how git commands are executed

### CODE REVIEW

**Review by landongrindheim — APPROVED** [review]
🥇

**Comment by jurre** [comment]
Seems like this is causing a bunch of test failures, likely that one of our native helpers or patches that use internal bundler code use a method that has changed. Will take a look tomorrow

**Comment by Nishnha** [comment]
> Seems like this is causing a bunch of test failures, likely that one of our native helpers or patches that use internal bundler code use a method that has changed. Will take a look tomorrow

I remember this PR was failing bundler1 and bundler2 tests. What changed so that they were able to pass?

**Comment by jurre** [comment]
Unfortunately the bundler 1 suite is flaky in general, nothing to do with the changes here

**Pull request merged**
